import type { ElementType } from "react"
import {
  Activity,
  BarChart3,
  Bell,
  Bot,
  Briefcase,
  Building2,
  Contact,
  Database,
  Gauge,
  HelpCircle,
  KeyRound,
  Layers,
  ListFilter,
  Megaphone,
  Music2,
  PieChart,
  Settings,
  Shield,
  Sparkles,
  User,
  Wrench,
} from "lucide-react"

export const MOBILE_MORE_NAV_ICONS: Record<string, ElementType> = {
  Alerts: Bell,
  Waterfall: ListFilter,
  Mediation: Layers,
  Monitoring: Gauge,
  Activity: Activity,
  "My Reports": PieChart,
  "Meta Ads": Megaphone,
  "TikTok Ads": Music2,
  "AI Assistant": Bot,
  Organizations: Building2,
  Jobs: Briefcase,
  Permissions: Shield,
  Commission: BarChart3,
  "Data Accounts": KeyRound,
  "Data Sources": Database,
  "WF Config": Settings,
  Insights: Sparkles,
  Profile: User,
  Help: HelpCircle,
  Settings: Settings,
  "vCard Generator": Contact,
  Maintenance: Wrench,
}
