"use client"

import { useEffect, useState } from "react"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Textarea } from "@/components/ui/textarea"
import { Badge } from "@/components/ui/badge"
import { Switch } from "@/components/ui/switch"
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select"
import { Popover, PopoverContent, PopoverTrigger } from "@/components/ui/popover"
import { Command, CommandEmpty, CommandGroup, CommandInput, CommandItem, CommandList } from "@/components/ui/command"
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs"
import { Button } from "@/components/ui/button"
import { useToast } from "@/hooks/use-toast"
import { metaReferenceApi, metaRequestsApi } from "@/lib/api/meta-ads"
import { createEmptyCarouselCard, createEmptyFlexibleAsset } from "@/lib/meta-ads/mappers"
import { getSelectionPreviewSource } from "@/lib/meta-ads/media-preview"
import type { MetaAppMappingDto, MetaFacebookPageReferenceDto, MetaFacebookPostReferenceDto, MetaReferenceMediaDto, MetaRequestAssetSelectionState } from "@/types/meta-ads"
import { ImageIcon, Smartphone, Video, GalleryHorizontal, FileText, AlertTriangle, Check, CheckCircle2, ChevronsUpDown, Loader2, Plus, Trash2, Wand2 } from "lucide-react"
import type { RequestFormState } from "./create-request-content"
import { buildCreativeName, useAutoGeneratedNameField } from "./naming"
import { ProtectedMediaImage } from "../shared/protected-media-image"
import { MetaMediaPickerDialog } from "./meta-media-picker-dialog"
import { MetaVideoPreviewDialog } from "./meta-video-preview-dialog"

const ctaOptions = [
  "LEARN_MORE", "SHOP_NOW", "DOWNLOAD", "INSTALL_MOBILE_APP", "USE_MOBILE_APP",
  "SIGN_UP", "GET_OFFER", "BOOK_TRAVEL", "CONTACT_US", "WATCH_MORE"
]


function buildMetaLibrarySelectionPatch(media: MetaReferenceMediaDto, adAccountId?: number | null): Partial<MetaRequestAssetSelectionState> {
  return {
    mode: "meta_ref",
    metaRefSource: "from_meta",
    imageHash: media.assetType === "IMAGE" ? (media.hash ?? "") : "",
    imageUrl: "",
    videoId: media.assetType === "VIDEO" ? (media.videoId ?? media.id) : "",
    uploadedAssetId: null,
    uploadedAssetName: "",
    uploadedAssetPreviewUrl: "",
    metaPreviewUrl: media.thumbnailUrl ?? "",
    metaPreviewRequiresAuth: !!media.requiresAuth,
    metaPlayableUrl: media.playableUrl ?? "",
    metaAssetId: media.id,
    metaAssetName: media.name ?? "",
    metaAssetType: media.assetType,
    metaAdAccountId: adAccountId != null ? String(adAccountId) : "",
  }
}

function clearMetaReferenceDecoration(patch?: Partial<MetaRequestAssetSelectionState>): Partial<MetaRequestAssetSelectionState> {
  return {
    uploadedAssetId: null,
    uploadedAssetName: "",
    uploadedAssetPreviewUrl: "",
    ...patch,
    metaPreviewUrl: "",
    metaPreviewRequiresAuth: false,
    metaPlayableUrl: "",
    metaAssetId: "",
    metaAssetName: "",
    metaAssetType: "",
    metaAdAccountId: "",
  }
}
const maxCreativeTextVariations = 5

function getExistingPostOptionLabel(post: MetaFacebookPostReferenceDto) {
  const primaryText = (post.message?.trim() || post.story?.trim() || post.id).replace(/\s+/g, " ")
  return primaryText.length > 72 ? `${primaryText.slice(0, 72)}...` : primaryText
}

function formatExistingPostDate(createdTime?: string | null) {
  if (!createdTime) return null
  const parsed = new Date(createdTime)
  return Number.isNaN(parsed.getTime()) ? null : parsed.toLocaleDateString("en-GB")
}

interface Props {
  form: RequestFormState
  onChange: (patch: Partial<RequestFormState>) => void
  facebookPages: MetaFacebookPageReferenceDto[]
  facebookPagesLoading?: boolean
  facebookPagesMessage?: string | null
  facebookPageSource: "promote_pages" | "access_token_all"
  onFacebookPageSourceChange: (source: "promote_pages" | "access_token_all") => void
  selectedAppMapping?: MetaAppMappingDto | null
  adAccountId?: number | null
}

export function CreativeSection({
  form,
  onChange,
  facebookPages,
  facebookPagesLoading = false,
  facebookPagesMessage,
  facebookPageSource,
  onFacebookPageSourceChange,
  selectedAppMapping,
  adAccountId,
}: Props) {
  const { toast } = useToast()
  const [uploadingKey, setUploadingKey] = useState<string | null>(null)
  const [pagePickerOpen, setPagePickerOpen] = useState(false)
  const [pageEntryMode, setPageEntryMode] = useState<"picker" | "manual">("picker")
  const [existingPostPickerOpen, setExistingPostPickerOpen] = useState(false)
  const [existingPostEntryMode, setExistingPostEntryMode] = useState<"picker" | "manual">("picker")
  const [facebookPagePosts, setFacebookPagePosts] = useState<MetaFacebookPostReferenceDto[]>([])
  const [facebookPagePostsLoading, setFacebookPagePostsLoading] = useState(false)
  const [facebookPagePostsMessage, setFacebookPagePostsMessage] = useState<string | null>(null)
  const completion = getCreativeCompletion(form)
  const previewImage = getPreviewImage(form)
  const generatedCreativeName = buildCreativeName(form, selectedAppMapping)
  const { isAutoEnabled: isAutoNameEnabled, setIsAutoEnabled, applyGeneratedName, markManual } = useAutoGeneratedNameField(
    form.creativeName,
    generatedCreativeName,
    (value) => onChange({ creativeName: value })
  )
  const selectedExistingPost = facebookPagePosts.find((post) => post.id === form.existingPostId)

  useEffect(() => {
    if (form.creativeType !== "EXISTING_POST" || existingPostEntryMode === "manual") {
      setExistingPostPickerOpen(false)
      return
    }

    if (!adAccountId) {
      setFacebookPagePosts([])
      setFacebookPagePostsMessage("Select a Meta ad account before loading Facebook posts.")
      setFacebookPagePostsLoading(false)
      return
    }

    const pageId = form.facebookPageId.trim()
    if (!pageId) {
      setFacebookPagePosts([])
      setFacebookPagePostsMessage("Select a Facebook Page before choosing an existing post.")
      setFacebookPagePostsLoading(false)
      return
    }

    let isCancelled = false

    const loadPosts = async () => {
      try {
        setFacebookPagePostsLoading(true)
        setFacebookPagePostsMessage(null)
        const result = await metaReferenceApi.getFacebookPagePosts(adAccountId, pageId, { limit: 50 })
        if (isCancelled) return
        setFacebookPagePosts(result.items)
        setFacebookPagePostsMessage(null)
      } catch (error) {
        if (isCancelled) return
        const message = error instanceof Error ? error.message : "Failed to load Facebook posts."
        setFacebookPagePosts([])
        setFacebookPagePostsMessage(message)
      } finally {
        if (!isCancelled) {
          setFacebookPagePostsLoading(false)
        }
      }
    }

    loadPosts()
    return () => {
      isCancelled = true
    }
  }, [adAccountId, existingPostEntryMode, form.creativeType, form.facebookPageId])

  const handleMediaPatch = (field: keyof RequestFormState, patch: Partial<MetaRequestAssetSelectionState>) => {
    const current = form[field] as MetaRequestAssetSelectionState
    onChange({ [field]: { ...current, ...patch } } as Partial<RequestFormState>)
  }

  const handleMediaModeChange = (field: keyof RequestFormState, mode: MetaRequestAssetSelectionState["mode"]) => {
    const current = form[field] as MetaRequestAssetSelectionState
    onChange({ [field]: { ...current, mode } } as Partial<RequestFormState>)
  }


  const handleMetaSelection = (field: keyof RequestFormState, media: MetaReferenceMediaDto) => {
    handleMediaPatch(field, buildMetaLibrarySelectionPatch(media, adAccountId))
  }

  const handleCarouselMetaSelection = (index: number, media: MetaReferenceMediaDto) => {
    updateCarouselCardImage(index, buildMetaLibrarySelectionPatch(media, adAccountId))
  }
  const handleUpload = async (field: keyof RequestFormState, kind: "image" | "video", file: File | null) => {
    if (!file) return
    try {
      setUploadingKey(`${String(field)}:${file.name}`)
      const asset = await metaRequestsApi.uploadAsset(file, kind)
      handleMediaPatch(field, {
        mode: "uploaded_asset",
        uploadedAssetId: asset.id,
        uploadedAssetName: asset.fileName,
        uploadedAssetPreviewUrl: kind === "image" ? URL.createObjectURL(file) : "",
        metaPlayableUrl: "",
        imageHash: "",
        imageUrl: "",
        videoId: "",
      })
      toast({ title: `${kind === "image" ? "Image" : "Video"} uploaded`, description: asset.fileName })
    } catch (error) {
      const message = error instanceof Error ? error.message : "Upload failed."
      toast({ title: "Upload failed", description: message, variant: "destructive" })
    } finally {
      setUploadingKey(null)
    }
  }

  const updateCarouselCard = (index: number, patch: Partial<RequestFormState["carouselCards"][number]>) => {
    onChange({ carouselCards: form.carouselCards.map((card, cardIndex) => (cardIndex === index ? { ...card, ...patch } : card)) })
  }

  const updateCarouselCardImage = (index: number, patch: Partial<MetaRequestAssetSelectionState>) => {
    onChange({ carouselCards: form.carouselCards.map((card, cardIndex) => (cardIndex === index ? { ...card, image: { ...card.image, ...patch } } : card)) })
  }

  const handleCarouselUpload = async (index: number, file: File | null) => {
    if (!file) return
    try {
      setUploadingKey(`carousel:${index}:${file.name}`)
      const asset = await metaRequestsApi.uploadAsset(file, "image")
      updateCarouselCardImage(index, {
        mode: "uploaded_asset",
        uploadedAssetId: asset.id,
        uploadedAssetName: asset.fileName,
        uploadedAssetPreviewUrl: URL.createObjectURL(file),
        metaPlayableUrl: "",
        imageHash: "",
        imageUrl: "",
      })
      toast({ title: "Image uploaded", description: asset.fileName })
    } catch (error) {
      const message = error instanceof Error ? error.message : "Upload failed."
      toast({ title: "Upload failed", description: message, variant: "destructive" })
    } finally {
      setUploadingKey(null)
    }
  }


  const updateFlexibleAsset = (index: number, patch: Partial<RequestFormState["flexibleAssets"][number]>) => {
    onChange({ flexibleAssets: form.flexibleAssets.map((asset, assetIndex) => (assetIndex === index ? { ...asset, ...patch } : asset)) })
  }

  const updateFlexibleAssetMedia = (
    index: number,
    field: "image" | "video" | "thumbnail",
    patch: Partial<MetaRequestAssetSelectionState>
  ) => {
    onChange({
      flexibleAssets: form.flexibleAssets.map((asset, assetIndex) => (assetIndex === index ? { ...asset, [field]: { ...asset[field], ...patch } } : asset)),
    })
  }

  const handleFlexibleMetaSelection = (index: number, field: "image" | "video" | "thumbnail", media: MetaReferenceMediaDto) => {
    updateFlexibleAssetMedia(index, field, buildMetaLibrarySelectionPatch(media, adAccountId))
  }

  const handleFlexibleUpload = async (index: number, kind: "image" | "video" | "thumbnail", file: File | null) => {
    if (!file) return

    try {
      setUploadingKey(`flexible:${index}:${kind}:${file.name}`)
      const asset = await metaRequestsApi.uploadAsset(file, kind === "video" ? "video" : "image")
      updateFlexibleAssetMedia(index, kind, {
        mode: "uploaded_asset",
        uploadedAssetId: asset.id,
        uploadedAssetName: asset.fileName,
        uploadedAssetPreviewUrl: kind === "video" ? "" : URL.createObjectURL(file),
        metaPlayableUrl: "",
        imageHash: "",
        imageUrl: "",
        videoId: "",
      })
      toast({ title: `${kind === "video" ? "Video" : "Image"} uploaded`, description: asset.fileName })
    } catch (error) {
      const message = error instanceof Error ? error.message : "Upload failed."
      toast({ title: "Upload failed", description: message, variant: "destructive" })
    } finally {
      setUploadingKey(null)
    }
  }

  const updateTextVariations = (
    valuesField: "singleImagePrimaryTexts" | "singleImageHeadlines" | "singleVideoPrimaryTexts" | "singleVideoHeadlines",
    firstField: "singleImagePrimaryText" | "singleImageHeadline" | "singleVideoPrimaryText" | "singleVideoHeadline",
    values: string[]
  ) => {
    const nextValues = normalizeVariationRows(values)
    onChange({
      [valuesField]: nextValues,
      [firstField]: getFirstFilledVariation(nextValues),
    } as Partial<RequestFormState>)
  }

  return (
    <Card className="border-slate-200">
      <CardHeader className="pb-3">
        <div className="flex items-center justify-between gap-3">
          <CardTitle className="text-sm font-semibold text-slate-900 flex items-center gap-2">
            <ImageIcon className="w-4 h-4 text-slate-500" />
            Creative
          </CardTitle>
          <div className="flex items-center gap-2">
            <Badge variant="outline" className="text-[10px] text-slate-500 border-slate-300 font-mono px-2 py-0.5">{form.creativeType}</Badge>
            <Badge className={completion.complete ? "bg-green-100 text-green-700 text-[10px] px-2 py-0.5 gap-1" : "bg-amber-100 text-amber-700 text-[10px] px-2 py-0.5 gap-1"}>
              {completion.complete ? <CheckCircle2 className="w-2.5 h-2.5" /> : <AlertTriangle className="w-2.5 h-2.5" />}
              {completion.complete ? "Complete" : "Incomplete"}
            </Badge>
          </div>
        </div>
        <p className="text-[11px] text-slate-400 mt-1">Draft the Meta creative here. Uploaded media stays in Mediation Pro until execute time.</p>
      </CardHeader>
      <CardContent>
        <div className="grid grid-cols-[1fr_220px] gap-6">
          <div className="space-y-4">
            <div className="grid grid-cols-3 gap-4">
              <div className="space-y-1.5 col-span-2">
                <div className="flex items-center justify-between gap-3">
                  <Label className="text-xs font-medium text-slate-700">Creative Name <span className="text-red-500">*</span></Label>
                  <div className="flex items-center gap-2 text-[11px] text-slate-600">
                    <Wand2 className="w-3.5 h-3.5 text-slate-400" />
                    <span>Auto-generate</span>
                    <Switch checked={isAutoNameEnabled} onCheckedChange={(checked) => {
                      setIsAutoEnabled(checked)
                      if (checked) applyGeneratedName()
                    }} />
                  </div>
                </div>
                <Input
                  value={form.creativeName}
                  onChange={(event) => {
                    markManual()
                    onChange({ creativeName: event.target.value })
                  }}
                  placeholder="e.g. WeatherApp_US_IMG_v1"
                  className="h-9 text-sm"
                />
                <div className="rounded-md border border-slate-200 bg-slate-50 px-3 py-2 space-y-1.5">
                  <p className="text-[11px] text-slate-500">Pattern: <code className="rounded bg-white px-1 py-0.5">APP_GEO_CREATIVE_v1</code></p>
                  <p className={`text-xs font-mono ${generatedCreativeName ? "text-slate-700" : "text-slate-400 italic"}`}>
                    {generatedCreativeName || "Select an app and geo targeting to generate a creative name."}
                  </p>
                  {!isAutoNameEnabled && generatedCreativeName ? (
                    <button
                      type="button"
                      onClick={applyGeneratedName}
                      className="text-[11px] font-medium text-blue-600 hover:text-blue-700"
                    >
                      Use generated name
                    </button>
                  ) : null}
                </div>
              </div>
              <div className="space-y-1.5">
                <Label className="text-xs font-medium text-slate-700">Creative Type</Label>
                <Select value={form.creativeType} onValueChange={(value) => onChange({ creativeType: value as RequestFormState["creativeType"] })}>
                  <SelectTrigger className="h-9 text-sm"><SelectValue /></SelectTrigger>
                  <SelectContent>
                    <SelectItem value="SINGLE_IMAGE">Single Image</SelectItem>
                    <SelectItem value="SINGLE_VIDEO">Single Video</SelectItem>
                    <SelectItem value="CAROUSEL_IMAGE">Carousel</SelectItem>
                    <SelectItem value="FLEXIBLE">Flexible</SelectItem>
                    <SelectItem value="EXISTING_POST">Existing Post</SelectItem>
                  </SelectContent>
                </Select>
              </div>
            </div>
            <div className="grid grid-cols-2 gap-4">
              <div className="space-y-1.5">
                <div className="flex items-start justify-between gap-3">
                  <Label className="text-xs font-medium text-slate-700">Facebook Page ID <span className="text-red-500">*</span></Label>
                  <div className="flex items-center gap-2">
                    <Button
                      type="button"
                      variant={pageEntryMode === "manual" ? "default" : "outline"}
                      size="sm"
                      className="h-7 px-2 text-[11px]"
                      onClick={() => setPageEntryMode(pageEntryMode === "manual" ? "picker" : "manual")}
                    >
                      {pageEntryMode === "manual" ? "Use Picker" : "Enter ID Manually"}
                    </Button>
                    <Button
                      type="button"
                      variant="outline"
                      size="sm"
                      className="h-7 px-2 text-[11px]"
                      onClick={() => onFacebookPageSourceChange(facebookPageSource === "promote_pages" ? "access_token_all" : "promote_pages")}
                      disabled={!form.adAccountId || facebookPagesLoading || pageEntryMode === "manual"}
                    >
                      {facebookPageSource === "promote_pages" ? "Load All Token Pages" : "Use Promote Pages"}
                    </Button>
                  </div>
                </div>
                {pageEntryMode === "manual" ? (
                  <Input
                    value={form.facebookPageId}
                    onChange={(event) => onChange({ facebookPageId: event.target.value })}
                    placeholder="Enter Facebook Page ID manually"
                    className="h-9 text-sm font-mono"
                  />
                ) : (
                  <Popover open={pagePickerOpen} onOpenChange={setPagePickerOpen}>
                    <PopoverTrigger asChild>
                      <Button type="button" variant="outline" role="combobox" aria-expanded={pagePickerOpen} className="h-9 w-full justify-between text-sm font-normal">
                        {form.facebookPageId
                          ? (() => {
                              const selectedPage = facebookPages.find((page) => page.id === form.facebookPageId)
                              return selectedPage ? `${selectedPage.name} (${selectedPage.id})` : form.facebookPageId
                            })()
                          : (facebookPagesLoading ? "Loading pages..." : "Select Facebook page...")}
                        <ChevronsUpDown className="ml-2 h-4 w-4 shrink-0 opacity-50" />
                      </Button>
                    </PopoverTrigger>
                    <PopoverContent className="w-[420px] p-0" align="start">
                      <Command>
                        <CommandInput placeholder="Search page name or ID..." />
                        <CommandList>
                          <CommandEmpty>{facebookPagesMessage || (facebookPagesLoading ? "Loading pages..." : (facebookPageSource === "access_token_all" ? "No Facebook pages found for the current access token." : "No Facebook pages found for this ad account."))}</CommandEmpty>
                          <CommandGroup>
                            {facebookPages.map((page) => (
                              <CommandItem
                                key={page.id}
                                value={`${page.name} ${page.id} ${page.category ?? ""}`}
                                onSelect={() => {
                                  onChange({ facebookPageId: page.id })
                                  setPagePickerOpen(false)
                                }}
                              >
                                <Check className={`mr-2 h-4 w-4 ${form.facebookPageId === page.id ? "opacity-100" : "opacity-0"}`} />
                                <div className="min-w-0">
                                  <div className="text-sm font-medium truncate">{page.name}</div>
                                  <div className="text-[11px] text-slate-400 font-mono truncate">{page.id}{page.category ? ` - ${page.category}` : ""}</div>
                                </div>
                              </CommandItem>
                            ))}
                          </CommandGroup>
                        </CommandList>
                      </Command>
                    </PopoverContent>
                  </Popover>
                )}
                <p className="text-[11px] text-slate-500">
                  {pageEntryMode === "manual"
                    ? "Manual mode lets you paste a Facebook Page ID even when it is not returned by Meta page lookup."
                    : (facebookPageSource === "access_token_all"
                        ? "Showing all pages accessible by the current access token."
                        : "Showing promote pages scoped to the selected ad account.")}
                </p>
                {facebookPagesMessage && pageEntryMode !== "manual" ? <p className="text-[11px] text-red-600">{facebookPagesMessage}</p> : null}
                {!facebookPagesMessage && !facebookPagesLoading && facebookPages.length === 0 && pageEntryMode !== "manual" ? <p className="text-[11px] text-amber-700">{facebookPageSource === "access_token_all" ? "No accessible Facebook pages were found for the current access token." : "No accessible Facebook pages were found for the selected ad account."}</p> : null}
              </div>
              <div className="space-y-1.5">
                <Label className="text-xs font-medium text-slate-700">Instagram Actor ID</Label>
                <Input value={form.instagramActorId} onChange={(event) => onChange({ instagramActorId: event.target.value })} placeholder="Optional" className="h-9 text-sm" />
              </div>
            </div>

            <Tabs value={form.creativeType} onValueChange={(value) => onChange({ creativeType: value as RequestFormState["creativeType"] })}>
              <TabsList className="h-10 bg-slate-100 p-1 w-fit">
                <TabsTrigger value="SINGLE_IMAGE" className="text-xs px-3 data-[state=active]:bg-white"><ImageIcon className="w-3.5 h-3.5 mr-1.5" />Single Image</TabsTrigger>
                <TabsTrigger value="SINGLE_VIDEO" className="text-xs px-3 data-[state=active]:bg-white"><Video className="w-3.5 h-3.5 mr-1.5" />Single Video</TabsTrigger>
                <TabsTrigger value="CAROUSEL_IMAGE" className="text-xs px-3 data-[state=active]:bg-white"><GalleryHorizontal className="w-3.5 h-3.5 mr-1.5" />Carousel</TabsTrigger>
                <TabsTrigger value="FLEXIBLE" className="text-xs px-3 data-[state=active]:bg-white"><GalleryHorizontal className="w-3.5 h-3.5 mr-1.5" />Flexible</TabsTrigger>
                <TabsTrigger value="EXISTING_POST" className="text-xs px-3 data-[state=active]:bg-white"><FileText className="w-3.5 h-3.5 mr-1.5" />Existing Post</TabsTrigger>
              </TabsList>

              <TabsContent value="SINGLE_IMAGE" className="mt-4 space-y-4">
                <TextVariationEditor
                  label="Primary Text"
                  values={form.singleImagePrimaryTexts}
                  required
                  multiline
                  placeholder="Enter primary text variation"
                  onChange={(values) => updateTextVariations("singleImagePrimaryTexts", "singleImagePrimaryText", values)}
                />
                <TextVariationEditor
                  label="Headline"
                  values={form.singleImageHeadlines}
                  required
                  placeholder="Enter headline variation"
                  onChange={(values) => updateTextVariations("singleImageHeadlines", "singleImageHeadline", values)}
                />
                <div className="grid grid-cols-2 gap-4">
                  <div className="space-y-1.5">
                    <Label className="text-xs font-medium text-slate-700">Description</Label>
                    <Input value={form.singleImageDescription} onChange={(event) => onChange({ singleImageDescription: event.target.value })} className="h-9 text-sm" />
                  </div>
                  <div className="space-y-1.5">
                    <Label className="text-xs font-medium text-slate-700">Call To Action <span className="text-red-500">*</span></Label>
                    <Select value={form.singleImageCallToAction} onValueChange={(value) => onChange({ singleImageCallToAction: value })}>
                      <SelectTrigger className="h-9 text-sm"><SelectValue /></SelectTrigger>
                      <SelectContent>{ctaOptions.map((cta) => <SelectItem key={cta} value={cta}>{cta}</SelectItem>)}</SelectContent>
                    </Select>
                  </div>
                </div>
                <div className="space-y-1.5">
                  <Label className="text-xs font-medium text-slate-700">Link URL</Label>
                  <Input value={form.singleImageLinkUrl} onChange={(event) => onChange({ singleImageLinkUrl: event.target.value })} placeholder="https://example.com" className="h-9 text-sm" />
                  <p className="text-[11px] text-slate-400">Enter a valid absolute URL starting with http:// or https://. Leave blank to use the app mapping fallback URL.</p>
                </div>
                <MediaSourceEditor title="Image" kind="image" selection={form.singleImageImage} uploading={uploadingKey?.startsWith("singleImageImage") ?? false} allowExternalUrl adAccountId={adAccountId ?? null} onModeChange={(mode) => handleMediaModeChange("singleImageImage", mode)} onPatch={(patch) => handleMediaPatch("singleImageImage", patch)} onUpload={(file) => handleUpload("singleImageImage", "image", file)} onMetaSelect={(media) => handleMetaSelection("singleImageImage", media)} />
              </TabsContent>

              <TabsContent value="SINGLE_VIDEO" className="mt-4 space-y-4">
                <TextVariationEditor
                  label="Primary Text"
                  values={form.singleVideoPrimaryTexts}
                  required
                  multiline
                  placeholder="Enter primary text variation"
                  onChange={(values) => updateTextVariations("singleVideoPrimaryTexts", "singleVideoPrimaryText", values)}
                />
                <TextVariationEditor
                  label="Headline"
                  values={form.singleVideoHeadlines}
                  required
                  placeholder="Enter headline variation"
                  onChange={(values) => updateTextVariations("singleVideoHeadlines", "singleVideoHeadline", values)}
                />
                <div className="grid grid-cols-2 gap-4">
                  <div className="space-y-1.5">
                    <Label className="text-xs font-medium text-slate-700">Description</Label>
                    <Input value={form.singleVideoDescription} onChange={(event) => onChange({ singleVideoDescription: event.target.value })} className="h-9 text-sm" />
                  </div>
                  <div className="space-y-1.5">
                    <Label className="text-xs font-medium text-slate-700">Call To Action <span className="text-red-500">*</span></Label>
                    <Select value={form.singleVideoCallToAction} onValueChange={(value) => onChange({ singleVideoCallToAction: value })}>
                      <SelectTrigger className="h-9 text-sm"><SelectValue /></SelectTrigger>
                      <SelectContent>{ctaOptions.map((cta) => <SelectItem key={cta} value={cta}>{cta}</SelectItem>)}</SelectContent>
                    </Select>
                  </div>
                </div>
                <div className="space-y-1.5">
                  <Label className="text-xs font-medium text-slate-700">Link URL</Label>
                  <Input value={form.singleVideoLinkUrl} onChange={(event) => onChange({ singleVideoLinkUrl: event.target.value })} placeholder="https://example.com" className="h-9 text-sm" />
                  <p className="text-[11px] text-slate-400">Enter a valid absolute URL starting with http:// or https://. Leave blank to use the app mapping fallback URL.</p>
                </div>
                <MediaSourceEditor title="Video" kind="video" selection={form.singleVideoVideo} uploading={uploadingKey?.startsWith("singleVideoVideo") ?? false} adAccountId={adAccountId ?? null} onModeChange={(mode) => handleMediaModeChange("singleVideoVideo", mode)} onPatch={(patch) => handleMediaPatch("singleVideoVideo", patch)} onUpload={(file) => handleUpload("singleVideoVideo", "video", file)} onMetaSelect={(media) => handleMetaSelection("singleVideoVideo", media)} />
                <MediaSourceEditor title="Thumbnail" kind="image" selection={form.singleVideoThumbnail} uploading={uploadingKey?.startsWith("singleVideoThumbnail") ?? false} allowExternalUrl optional adAccountId={adAccountId ?? null} onModeChange={(mode) => handleMediaModeChange("singleVideoThumbnail", mode)} onPatch={(patch) => handleMediaPatch("singleVideoThumbnail", patch)} onUpload={(file) => handleUpload("singleVideoThumbnail", "image", file)} onMetaSelect={(media) => handleMetaSelection("singleVideoThumbnail", media)} />
              </TabsContent>

              <TabsContent value="CAROUSEL_IMAGE" className="mt-4 space-y-4">
                <div className="grid grid-cols-2 gap-4">
                  <div className="space-y-1.5">
                    <Label className="text-xs font-medium text-slate-700">Primary Text</Label>
                    <Textarea rows={3} value={form.carouselPrimaryText} onChange={(event) => onChange({ carouselPrimaryText: event.target.value })} className="text-sm resize-none" />
                  </div>
                  <div className="space-y-1.5">
                    <Label className="text-xs font-medium text-slate-700">Call To Action <span className="text-red-500">*</span></Label>
                    <Select value={form.carouselCallToAction} onValueChange={(value) => onChange({ carouselCallToAction: value })}>
                      <SelectTrigger className="h-9 text-sm"><SelectValue /></SelectTrigger>
                      <SelectContent>{ctaOptions.map((cta) => <SelectItem key={cta} value={cta}>{cta}</SelectItem>)}</SelectContent>
                    </Select>
                  </div>
                </div>
                <div className="space-y-3">
                  <div className="flex items-center justify-between">
                    <div>
                      <p className="text-xs font-medium text-slate-700">Carousel Cards</p>
                      <p className="text-[11px] text-slate-400">Use 2-10 image cards.</p>
                    </div>
                    <Button type="button" variant="outline" size="sm" className="h-8 text-xs" onClick={() => onChange({ carouselCards: [...form.carouselCards, createEmptyCarouselCard()] })} disabled={form.carouselCards.length >= 10}>
                      <Plus className="w-3.5 h-3.5 mr-1" />Add Card
                    </Button>
                  </div>
                  {form.carouselCards.map((card, index) => (
                    <div key={card.id} className="rounded-lg border border-slate-200 p-3 space-y-3 bg-slate-50">
                      <div className="flex items-center justify-between">
                        <p className="text-xs font-semibold text-slate-700">Card {index + 1}</p>
                        <Button type="button" variant="ghost" size="sm" className="h-7 text-xs text-red-600" onClick={() => onChange({ carouselCards: form.carouselCards.filter((_, cardIndex) => cardIndex !== index) })} disabled={form.carouselCards.length <= 2}>
                          <Trash2 className="w-3.5 h-3.5 mr-1" />Remove
                        </Button>
                      </div>
                      <div className="grid grid-cols-2 gap-4">
                        <div className="space-y-1.5">
                          <Label className="text-xs font-medium text-slate-700">Headline <span className="text-red-500">*</span></Label>
                          <Input value={card.headline} onChange={(event) => updateCarouselCard(index, { headline: event.target.value })} className="h-9 text-sm" />
                        </div>
                        <div className="space-y-1.5">
                          <Label className="text-xs font-medium text-slate-700">Link URL</Label>
                          <Input value={card.linkUrl} onChange={(event) => updateCarouselCard(index, { linkUrl: event.target.value })} placeholder="https://example.com" className="h-9 text-sm" />
                          <p className="text-[11px] text-slate-400">Use a valid absolute URL or leave blank to use the app mapping fallback URL.</p>
                        </div>
                      </div>
                      <div className="space-y-1.5">
                        <Label className="text-xs font-medium text-slate-700">Description</Label>
                        <Input value={card.description} onChange={(event) => updateCarouselCard(index, { description: event.target.value })} className="h-9 text-sm" />
                      </div>
                      <InlineMediaSourceEditor selection={card.image} uploading={uploadingKey?.startsWith(`carousel:${index}:`) ?? false} adAccountId={adAccountId ?? null} onModeChange={(mode) => updateCarouselCardImage(index, { mode })} onPatch={(patch) => updateCarouselCardImage(index, patch)} onUpload={(file) => handleCarouselUpload(index, file)} onMetaSelect={(media) => handleCarouselMetaSelection(index, media)} />
                    </div>
                  ))}
                </div>
              </TabsContent>


              <TabsContent value="FLEXIBLE" className="mt-4 space-y-4">
                <div className="rounded-lg border border-blue-100 bg-blue-50/60 p-3 text-[11px] text-blue-700">
                  Flexible lets Meta choose the best-performing format from the images and videos you provide in one group.
                </div>
                <TextVariationEditor
                  label="Primary Text"
                  values={form.flexiblePrimaryTexts}
                  required
                  multiline
                  placeholder="Enter primary text variation"
                  onChange={(values) => onChange({ flexiblePrimaryTexts: normalizeVariationRows(values) })}
                />
                <TextVariationEditor
                  label="Headline"
                  values={form.flexibleHeadlines}
                  required
                  placeholder="Enter headline variation"
                  onChange={(values) => onChange({ flexibleHeadlines: normalizeVariationRows(values) })}
                />
                <div className="grid grid-cols-2 gap-4">
                  <div className="space-y-1.5">
                    <Label className="text-xs font-medium text-slate-700">Call To Action <span className="text-red-500">*</span></Label>
                    <Select value={form.flexibleCallToAction} onValueChange={(value) => onChange({ flexibleCallToAction: value })}>
                      <SelectTrigger className="h-9 text-sm"><SelectValue /></SelectTrigger>
                      <SelectContent>{ctaOptions.map((cta) => <SelectItem key={cta} value={cta}>{cta}</SelectItem>)}</SelectContent>
                    </Select>
                  </div>
                  <div className="space-y-1.5">
                    <Label className="text-xs font-medium text-slate-700">Link URL</Label>
                    <Input value={form.flexibleLinkUrl} onChange={(event) => onChange({ flexibleLinkUrl: event.target.value })} placeholder="https://example.com" className="h-9 text-sm" />
                    <p className="text-[11px] text-slate-400">Enter a valid absolute URL starting with http:// or https://. Leave blank to use the app mapping fallback URL.</p>
                  </div>
                </div>
                <div className="space-y-3">
                  <div className="flex items-center justify-between">
                    <div>
                      <p className="text-xs font-medium text-slate-700">Flexible Assets</p>
                      <p className="text-[11px] text-slate-400">Add at least 1 image or video for the flexible group.</p>
                    </div>
                    <Button type="button" variant="outline" size="sm" className="h-8 text-xs" onClick={() => onChange({ flexibleAssets: [...form.flexibleAssets, createEmptyFlexibleAsset()] })}>
                      <Plus className="w-3.5 h-3.5 mr-1" />Add Asset
                    </Button>
                  </div>
                  {form.flexibleAssets.map((asset, index) => (
                    <div key={asset.id} className="rounded-lg border border-slate-200 bg-slate-50 p-3 space-y-3">
                      <div className="flex items-center justify-between gap-3">
                        <p className="text-xs font-semibold text-slate-700">Asset {index + 1}</p>
                        <div className="flex items-center gap-2">
                          <Select value={asset.assetType} onValueChange={(value) => updateFlexibleAsset(index, { assetType: value as "IMAGE" | "VIDEO" })}>
                            <SelectTrigger className="h-8 w-[150px] text-xs"><SelectValue /></SelectTrigger>
                            <SelectContent>
                              <SelectItem value="IMAGE">Image</SelectItem>
                              <SelectItem value="VIDEO">Video</SelectItem>
                            </SelectContent>
                          </Select>
                          <Button type="button" variant="ghost" size="sm" className="h-8 text-xs text-red-600" onClick={() => onChange({ flexibleAssets: form.flexibleAssets.filter((_, assetIndex) => assetIndex !== index) })} disabled={form.flexibleAssets.length <= 1}>
                            <Trash2 className="w-3.5 h-3.5 mr-1" />Remove
                          </Button>
                        </div>
                      </div>
                      {asset.assetType === "VIDEO" ? (
                        <div className="space-y-3">
                          <MediaSourceEditor title="Video Asset" kind="video" selection={asset.video} uploading={uploadingKey?.startsWith(`flexible:${index}:video:`) ?? false} adAccountId={adAccountId ?? null} onModeChange={() => {}} onPatch={(patch) => updateFlexibleAssetMedia(index, "video", patch)} onUpload={(file) => handleFlexibleUpload(index, "video", file)} onMetaSelect={(media) => handleFlexibleMetaSelection(index, "video", media)} />
                          <MediaSourceEditor title="Thumbnail" kind="image" selection={asset.thumbnail} uploading={uploadingKey?.startsWith(`flexible:${index}:thumbnail:`) ?? false} allowExternalUrl optional adAccountId={adAccountId ?? null} onModeChange={() => {}} onPatch={(patch) => updateFlexibleAssetMedia(index, "thumbnail", patch)} onUpload={(file) => handleFlexibleUpload(index, "thumbnail", file)} onMetaSelect={(media) => handleFlexibleMetaSelection(index, "thumbnail", media)} />
                        </div>
                      ) : (
                        <MediaSourceEditor title="Image Asset" kind="image" selection={asset.image} uploading={uploadingKey?.startsWith(`flexible:${index}:image:`) ?? false} allowExternalUrl adAccountId={adAccountId ?? null} onModeChange={() => {}} onPatch={(patch) => updateFlexibleAssetMedia(index, "image", patch)} onUpload={(file) => handleFlexibleUpload(index, "image", file)} onMetaSelect={(media) => handleFlexibleMetaSelection(index, "image", media)} />
                      )}
                    </div>
                  ))}
                </div>
              </TabsContent>
              <TabsContent value="EXISTING_POST" className="mt-4 space-y-4">
                <div className="space-y-1.5">
                  <div className="flex items-start justify-between gap-3">
                    <Label className="text-xs font-medium text-slate-700">Source Post ID <span className="text-red-500">*</span></Label>
                    <Button
                      type="button"
                      variant={existingPostEntryMode === "manual" ? "default" : "outline"}
                      size="sm"
                      className="h-7 px-2 text-[11px]"
                      onClick={() => setExistingPostEntryMode(existingPostEntryMode === "manual" ? "picker" : "manual")}
                    >
                      {existingPostEntryMode === "manual" ? "Use Picker" : "Enter ID Manually"}
                    </Button>
                  </div>

                  {existingPostEntryMode === "manual" ? (
                    <Input
                      value={form.existingPostId}
                      onChange={(event) => onChange({ existingPostId: event.target.value })}
                      placeholder="Enter object_story_id manually"
                      className="h-9 text-sm font-mono"
                    />
                  ) : (
                    <Popover open={existingPostPickerOpen} onOpenChange={setExistingPostPickerOpen}>
                      <PopoverTrigger asChild>
                        <Button type="button" variant="outline" role="combobox" aria-expanded={existingPostPickerOpen} className="h-9 w-full justify-between text-sm font-normal">
                          <span className="min-w-0 flex-1 truncate text-left">
                            {form.existingPostId
                              ? (selectedExistingPost ? getExistingPostOptionLabel(selectedExistingPost) : `Selected post ${form.existingPostId}`)
                              : (facebookPagePostsLoading ? "Loading posts..." : "Select a Facebook post...")}
                          </span>
                          <ChevronsUpDown className="ml-2 h-4 w-4 shrink-0 opacity-50" />
                        </Button>
                      </PopoverTrigger>
                      <PopoverContent className="w-[460px] p-0" align="start">
                        <Command>
                          <CommandInput placeholder="Search post text, story, or post ID..." />
                          <CommandList>
                            <CommandEmpty>{facebookPagePostsMessage || (facebookPagePostsLoading ? "Loading posts..." : "No Facebook posts found for this page.")}</CommandEmpty>
                            <CommandGroup>
                              {facebookPagePosts.map((post) => (
                                <CommandItem
                                  key={post.id}
                                  value={`${post.id} ${post.message ?? ""} ${post.story ?? ""} ${post.type ?? ""} ${post.statusType ?? ""}`}
                                  onSelect={() => {
                                    onChange({ existingPostId: post.id })
                                    setExistingPostPickerOpen(false)
                                  }}
                                >
                                  <Check className={`mr-2 h-4 w-4 ${form.existingPostId === post.id ? "opacity-100" : "opacity-0"}`} />
                                  <div className="min-w-0 flex-1">
                                    <div className="text-sm font-medium truncate">{getExistingPostOptionLabel(post)}</div>
                                    <div className="text-[11px] text-slate-400 font-mono truncate">
                                      {post.id}
                                      {formatExistingPostDate(post.createdTime) ? ` - ${formatExistingPostDate(post.createdTime)}` : ""}
                                      {post.type ? ` - ${post.type}` : ""}
                                    </div>
                                  </div>
                                </CommandItem>
                              ))}
                            </CommandGroup>
                          </CommandList>
                        </Command>
                      </PopoverContent>
                    </Popover>
                  )}

                  <p className="text-[11px] text-slate-400">
                    {existingPostEntryMode === "manual"
                      ? "Manual mode lets you paste object_story_id directly, including posts not returned in the recent page post picker."
                      : "Picker mode loads recent posts from the selected Facebook Page. Switch to manual mode for older or unavailable posts."}
                  </p>
                  {existingPostEntryMode !== "manual" && facebookPagePostsMessage ? <p className="text-[11px] text-red-600">{facebookPagePostsMessage}</p> : null}
                  {existingPostEntryMode !== "manual" && !facebookPagePostsMessage && !facebookPagePostsLoading && facebookPagePosts.length === 0 ? <p className="text-[11px] text-amber-700">No recent posts were returned for the selected Facebook Page.</p> : null}
                  {existingPostEntryMode !== "manual" && form.existingPostId && !selectedExistingPost && !facebookPagePostsLoading ? (
                    <p className="text-[11px] text-amber-700">The current post ID is not in the loaded recent posts. Switch to manual mode if you want to keep using it.</p>
                  ) : null}
                  {selectedExistingPost ? (
                    <div className="rounded-md border border-slate-200 bg-slate-50 px-3 py-2 space-y-1.5">
                      <p className="text-xs font-medium text-slate-700 line-clamp-2">{selectedExistingPost.message?.trim() || selectedExistingPost.story?.trim() || selectedExistingPost.id}</p>
                      <div className="flex flex-wrap gap-x-3 gap-y-1 text-[11px] text-slate-500">
                        <span className="font-mono">{selectedExistingPost.id}</span>
                        {formatExistingPostDate(selectedExistingPost.createdTime) ? <span>{formatExistingPostDate(selectedExistingPost.createdTime)}</span> : null}
                        {selectedExistingPost.type ? <span>{selectedExistingPost.type}</span> : null}
                      </div>
                      {selectedExistingPost.permalinkUrl ? (
                        <a href={selectedExistingPost.permalinkUrl} target="_blank" rel="noreferrer" className="text-[11px] font-medium text-blue-600 hover:text-blue-700">
                          Open post
                        </a>
                      ) : null}
                    </div>
                  ) : null}
                </div>
              </TabsContent>
            </Tabs>

            <div className="bg-slate-50 border border-slate-200 rounded-lg p-3">
              <p className="text-[11px] font-semibold text-slate-600 uppercase tracking-wide mb-2">Creative Checklist</p>
              <div className="grid grid-cols-2 gap-2 text-[11px]">
                {completion.items.map((item) => (
                  <div key={item.label} className={`flex items-center gap-1.5 ${item.ok ? "text-green-700" : "text-amber-700"}`}>
                    {item.ok ? <CheckCircle2 className="w-3 h-3 text-green-600" /> : <AlertTriangle className="w-3 h-3 text-amber-600" />}
                    <span>{item.label}</span>
                  </div>
                ))}
              </div>
            </div>
          </div>

          <div className="flex flex-col items-center">
            <p className="text-[11px] text-slate-400 mb-2 font-medium uppercase tracking-wide">Preview</p>
            <div className="w-44 rounded-2xl border-2 border-slate-300 bg-white shadow-sm overflow-hidden">
              <div className="bg-slate-100 px-3 py-1.5 flex items-center gap-2">
                <div className="w-1.5 h-1.5 rounded-full bg-slate-400" />
                <div className="w-1.5 h-1.5 rounded-full bg-slate-400" />
                <div className="w-1.5 h-1.5 rounded-full bg-slate-400" />
              </div>
              <div className="p-2 space-y-1.5">
                <div className="w-full h-20 bg-slate-100 rounded flex items-center justify-center border border-slate-200 overflow-hidden">
                  {previewImage.url ? (
                    <ProtectedMediaImage
                      src={previewImage.url}
                      requiresAuth={previewImage.requiresAuth}
                      alt="Creative preview"
                      className="w-full h-full object-cover rounded"
                    />
                  ) : form.creativeType === "SINGLE_VIDEO" ? <Video className="w-6 h-6 text-slate-300" /> : form.creativeType === "EXISTING_POST" ? <FileText className="w-6 h-6 text-slate-300" /> : <ImageIcon className="w-6 h-6 text-slate-300" />}
                </div>
                <div className="space-y-0.5">
                  <p className="text-[10px] font-semibold text-slate-900 leading-tight line-clamp-2">{getPreviewHeadline(form) || "Creative headline"}</p>
                  <p className="text-[9px] text-slate-500 leading-tight line-clamp-2">{getPreviewMessage(form) || "Creative preview will update as you fill the form."}</p>
                </div>
                <div className="pt-0.5"><div className="bg-blue-600 rounded text-center py-1"><span className="text-[9px] text-white font-semibold">{getPreviewCta(form)}</span></div></div>
                <p className="text-[8px] text-slate-400">Sponsored</p>
              </div>
            </div>
            <div className="flex items-center gap-1 mt-2 text-[10px] text-slate-400"><Smartphone className="w-3 h-3" /><span>Preview only</span></div>
          </div>
        </div>
      </CardContent>
    </Card>
  )
}

function MediaSourceEditor({
  title,
  kind,
  selection,
  uploading,
  allowExternalUrl,
  optional,
  adAccountId,
  onModeChange,
  onPatch,
  onUpload,
  onMetaSelect,
}: {
  title: string
  kind: "image" | "video"
  selection: MetaRequestAssetSelectionState
  uploading?: boolean
  allowExternalUrl?: boolean
  optional?: boolean
  adAccountId?: number | null
  onModeChange: (mode: MetaRequestAssetSelectionState["mode"]) => void
  onPatch: (patch: Partial<MetaRequestAssetSelectionState>) => void
  onUpload: (file: File | null) => void
  onMetaSelect: (media: MetaReferenceMediaDto) => void
}) {
  const [pickerOpen, setPickerOpen] = useState(false)
  const [previewOpen, setPreviewOpen] = useState(false)
  const editorMode = selection.mode === "uploaded_asset"
    ? "uploaded_asset"
    : selection.mode === "external_url"
      ? "external_url"
      : selection.metaRefSource === "from_meta"
        ? "from_meta"
        : "manual"

  const options = kind === "video"
    ? [
        { value: "from_meta", label: "From Meta" },
        { value: "manual", label: "Manual" },
        { value: "uploaded_asset", label: "Upload" },
      ]
    : [
        { value: "from_meta", label: "From Meta" },
        { value: "manual", label: "Manual" },
        ...(allowExternalUrl ? [{ value: "external_url", label: "External URL" }] : []),
        { value: "uploaded_asset", label: "Upload" },
      ]

  const preview = getSelectionPreviewSource(selection)

  const handleEditorModeChange = (value: string) => {
    if (value === "uploaded_asset") {
      onPatch(clearMetaReferenceDecoration({
        mode: "uploaded_asset",
        metaRefSource: "manual",
        imageHash: "",
        imageUrl: "",
        videoId: "",
      }))
      return
    }

    if (value === "external_url") {
      onPatch(clearMetaReferenceDecoration({
        mode: "external_url",
        metaRefSource: "manual",
        imageHash: "",
        videoId: "",
      }))
      return
    }

    onPatch(value === "from_meta"
      ? clearMetaReferenceDecoration({ mode: "meta_ref", metaRefSource: "from_meta", imageHash: "", imageUrl: "", videoId: "" })
      : clearMetaReferenceDecoration({ mode: "meta_ref", metaRefSource: "manual" }))
  }

  return (
    <div className="space-y-2 rounded-lg border border-slate-200 bg-slate-50 p-3">
      <div className="flex items-center justify-between gap-3">
        <Label className="text-xs font-medium text-slate-700">{title} {optional ? <span className="text-slate-400 font-normal">(optional)</span> : <span className="text-red-500">*</span>}</Label>
        <Select value={editorMode} onValueChange={handleEditorModeChange}>
          <SelectTrigger className="h-8 w-[160px] text-xs"><SelectValue /></SelectTrigger>
          <SelectContent>{options.map((option) => <SelectItem key={option.value} value={option.value}>{option.label}</SelectItem>)}</SelectContent>
        </Select>
      </div>
      {editorMode === "uploaded_asset" ? (
        <div className="space-y-2">
          <Input type="file" accept={kind === "image" ? "image/*" : "video/*"} className="h-9 text-sm" onChange={(event) => onUpload(event.target.files?.[0] ?? null)} />
          {uploading ? <p className="text-[11px] text-slate-500 flex items-center gap-1"><Loader2 className="w-3 h-3 animate-spin" /> Uploading...</p> : null}
          {selection.uploadedAssetId ? <p className="text-[11px] text-green-700">Stored asset: {selection.uploadedAssetName || `Asset #${selection.uploadedAssetId}`}</p> : null}
        </div>
      ) : editorMode === "external_url" ? (
        <div className="space-y-1.5">
          <Label className="text-[11px] text-slate-500">Image URL</Label>
          <Input value={selection.imageUrl} onChange={(event) => onPatch(clearMetaReferenceDecoration({ imageUrl: event.target.value, metaRefSource: "manual" }))} className="h-9 text-sm" />
        </div>
      ) : editorMode === "manual" ? (
        <div className="space-y-1.5">
          <Label className="text-[11px] text-slate-500">{kind === "video" ? "Meta Video ID" : "Meta Image Hash"}</Label>
          <Input
            value={kind === "video" ? selection.videoId : selection.imageHash}
            onChange={(event) => onPatch(clearMetaReferenceDecoration(kind === "video"
              ? { videoId: event.target.value, metaRefSource: "manual" }
              : { imageHash: event.target.value, metaRefSource: "manual", imageUrl: "" }))}
            className="h-9 text-sm font-mono"
          />
        </div>
      ) : (
        <div className="space-y-3 rounded-md border border-slate-200 bg-white p-3">
          <div className="flex flex-wrap items-center justify-between gap-3">
            <div className="space-y-1">
              <p className="text-xs font-medium text-slate-700">Browse Meta library</p>
              <p className="text-[11px] text-slate-500">Search existing {kind === "video" ? "videos" : "images"} from the selected Meta ad account.</p>
            </div>
            <Button type="button" variant="outline" size="sm" className="h-8 text-xs" onClick={() => setPickerOpen(true)} disabled={!adAccountId}>
              From Meta
            </Button>
          </div>
          {!adAccountId ? (
            <p className="text-[11px] text-amber-600">Select a Meta ad account first to browse media from Meta.</p>
          ) : null}
          {selection.metaAssetId || preview.url ? (
            <div className="flex items-start gap-3 rounded-md border border-slate-200 bg-slate-50 p-3">
              <div className="h-16 w-16 overflow-hidden rounded-md bg-slate-100">
                {preview.url ? (
                  <ProtectedMediaImage
                    src={preview.url}
                    requiresAuth={preview.requiresAuth}
                    alt={selection.metaAssetName || selection.metaAssetId || title}
                    className="h-full w-full object-cover"
                    fallback={<div className="flex h-full items-center justify-center text-slate-400">{kind === "video" ? <Video className="h-5 w-5" /> : <ImageIcon className="h-5 w-5" />}</div>}
                  />
                ) : (
                  <div className="flex h-full items-center justify-center text-slate-400">{kind === "video" ? <Video className="h-5 w-5" /> : <ImageIcon className="h-5 w-5" />}</div>
                )}
              </div>
              <div className="min-w-0 flex-1 space-y-1">
                <p className="truncate text-xs font-medium text-slate-800">{selection.metaAssetName || (kind === "video" ? selection.videoId : selection.imageHash) || "No Meta asset selected"}</p>
                <p className="truncate font-mono text-[11px] text-slate-500">{kind === "video" ? (selection.videoId || selection.metaAssetId || "-") : (selection.imageHash || selection.metaAssetId || "-")}</p>
              </div>
              {kind === "video" ? (
                <Button
                  type="button"
                  variant="outline"
                  size="sm"
                  className="h-8 text-xs"
                  onClick={() => setPreviewOpen(true)}
                  disabled={!selection.metaPlayableUrl && !preview.url}
                >
                  Preview video
                </Button>
              ) : null}
            </div>
          ) : (
            <p className="text-[11px] text-slate-500">No Meta asset selected yet.</p>
          )}
          <MetaMediaPickerDialog
            open={pickerOpen}
            onOpenChange={setPickerOpen}
            adAccountId={adAccountId ?? null}
            targetKind={kind}
            selectedAssetId={selection.metaAssetId || (kind === "video" ? selection.videoId : selection.imageHash) || null}
            onSelect={onMetaSelect}
          />
          {kind === "video" ? (
            <MetaVideoPreviewDialog
              open={previewOpen}
              onOpenChange={setPreviewOpen}
              title={selection.metaAssetName || selection.videoId || title}
              playableUrl={selection.metaPlayableUrl}
              thumbnailUrl={preview.url}
              requiresAuth={preview.requiresAuth}
            />
          ) : null}
        </div>
      )}
    </div>
  )
}

function InlineMediaSourceEditor({
  selection,
  uploading,
  adAccountId,
  onModeChange,
  onPatch,
  onUpload,
  onMetaSelect,
}: {
  selection: MetaRequestAssetSelectionState
  uploading?: boolean
  adAccountId?: number | null
  onModeChange: (mode: MetaRequestAssetSelectionState["mode"]) => void
  onPatch: (patch: Partial<MetaRequestAssetSelectionState>) => void
  onUpload: (file: File | null) => void
  onMetaSelect: (media: MetaReferenceMediaDto) => void
}) {
  const [pickerOpen, setPickerOpen] = useState(false)
  const editorMode = selection.mode === "uploaded_asset"
    ? "uploaded_asset"
    : selection.mode === "external_url"
      ? "external_url"
      : selection.metaRefSource === "from_meta"
        ? "from_meta"
        : "manual"

  const preview = getSelectionPreviewSource(selection)

  const handleEditorModeChange = (value: string) => {
    if (value === "uploaded_asset") {
      onPatch(clearMetaReferenceDecoration({
        mode: "uploaded_asset",
        metaRefSource: "manual",
        imageHash: "",
        imageUrl: "",
      }))
      return
    }

    if (value === "external_url") {
      onPatch(clearMetaReferenceDecoration({ mode: "external_url", metaRefSource: "manual", imageHash: "" }))
      return
    }

    onPatch(value === "from_meta"
      ? clearMetaReferenceDecoration({ mode: "meta_ref", metaRefSource: "from_meta", imageHash: "", imageUrl: "", videoId: "" })
      : clearMetaReferenceDecoration({ mode: "meta_ref", metaRefSource: "manual" }))
  }

  return (
    <div className="space-y-2 rounded-md border border-slate-200 bg-white p-3">
      <div className="flex items-center justify-between gap-3">
        <Label className="text-xs font-medium text-slate-700">Card Image <span className="text-red-500">*</span></Label>
        <Select value={editorMode} onValueChange={handleEditorModeChange}>
          <SelectTrigger className="h-8 w-[160px] text-xs"><SelectValue /></SelectTrigger>
          <SelectContent>
            <SelectItem value="from_meta">From Meta</SelectItem>
            <SelectItem value="manual">Manual</SelectItem>
            <SelectItem value="external_url">External URL</SelectItem>
            <SelectItem value="uploaded_asset">Upload</SelectItem>
          </SelectContent>
        </Select>
      </div>
      {editorMode === "uploaded_asset" ? (
        <div className="space-y-2">
          <Input type="file" accept="image/*" className="h-9 text-sm" onChange={(event) => onUpload(event.target.files?.[0] ?? null)} />
          {uploading ? <p className="text-[11px] text-slate-500 flex items-center gap-1"><Loader2 className="w-3 h-3 animate-spin" /> Uploading...</p> : null}
          {selection.uploadedAssetId ? <p className="text-[11px] text-green-700">Stored asset: {selection.uploadedAssetName || `Asset #${selection.uploadedAssetId}`}</p> : null}
        </div>
      ) : editorMode === "external_url" ? (
        <Input value={selection.imageUrl} onChange={(event) => onPatch(clearMetaReferenceDecoration({ imageUrl: event.target.value, metaRefSource: "manual" }))} className="h-9 text-sm" />
      ) : editorMode === "manual" ? (
        <Input value={selection.imageHash} onChange={(event) => onPatch(clearMetaReferenceDecoration({ imageHash: event.target.value, metaRefSource: "manual", imageUrl: "" }))} className="h-9 text-sm font-mono" />
      ) : (
        <div className="space-y-3 rounded-md border border-slate-200 bg-slate-50 p-3">
          <div className="flex flex-wrap items-center justify-between gap-3">
            <p className="text-[11px] text-slate-500">Pick an image from Meta for this carousel card.</p>
            <Button type="button" variant="outline" size="sm" className="h-8 text-xs" onClick={() => setPickerOpen(true)} disabled={!adAccountId}>From Meta</Button>
          </div>
          {preview.url ? (
            <div className="flex items-center gap-3 rounded-md border border-slate-200 bg-white p-2">
              <div className="h-14 w-14 overflow-hidden rounded-md bg-slate-100">
                <ProtectedMediaImage src={preview.url} requiresAuth={preview.requiresAuth} alt={selection.metaAssetName || selection.imageHash || "Card image"} className="h-full w-full object-cover" fallback={<div className="flex h-full items-center justify-center text-slate-400"><ImageIcon className="h-4 w-4" /></div>} />
              </div>
              <div className="min-w-0 flex-1">
                <p className="truncate text-xs font-medium text-slate-800">{selection.metaAssetName || selection.imageHash || "Meta image selected"}</p>
                <p className="truncate font-mono text-[11px] text-slate-500">{selection.imageHash || selection.metaAssetId || "-"}</p>
              </div>
            </div>
          ) : (
            <p className="text-[11px] text-slate-500">No Meta image selected yet.</p>
          )}
          <MetaMediaPickerDialog
            open={pickerOpen}
            onOpenChange={setPickerOpen}
            adAccountId={adAccountId ?? null}
            targetKind="image"
            selectedAssetId={selection.metaAssetId || selection.imageHash || null}
            onSelect={onMetaSelect}
          />
        </div>
      )}
    </div>
  )
}

function TextVariationEditor({
  label,
  values,
  required,
  multiline,
  placeholder,
  onChange,
}: {
  label: string
  values: string[]
  required?: boolean
  multiline?: boolean
  placeholder?: string
  onChange: (values: string[]) => void
}) {
  const rows = normalizeVariationRows(values)

  return (
    <div className="space-y-2 rounded-lg border border-slate-200 bg-slate-50 p-3">
      <div className="flex items-center justify-between gap-3">
        <div>
          <Label className="text-xs font-medium text-slate-700">{label} {required ? <span className="text-red-500">*</span> : null}</Label>
          <p className="text-[11px] text-slate-400">Add up to {maxCreativeTextVariations} variations. Meta can rotate these variations at delivery time.</p>
        </div>
        <Button
          type="button"
          variant="outline"
          size="sm"
          className="h-8 text-xs"
          onClick={() => onChange([...rows, ""])}
          disabled={rows.length >= maxCreativeTextVariations}
        >
          <Plus className="mr-1 h-3.5 w-3.5" />Add text
        </Button>
      </div>
      <div className="space-y-2">
        {rows.map((value, index) => (
          <div key={`${label}-${index}`} className="flex items-start gap-2">
            <div className="min-w-0 flex-1">
              {multiline ? (
                <Textarea
                  rows={3}
                  value={value}
                  placeholder={placeholder || `${label} ${index + 1}`}
                  onChange={(event) => {
                    const nextValues = [...rows]
                    nextValues[index] = event.target.value
                    onChange(nextValues)
                  }}
                  className="text-sm resize-none bg-white"
                />
              ) : (
                <Input
                  value={value}
                  placeholder={placeholder || `${label} ${index + 1}`}
                  onChange={(event) => {
                    const nextValues = [...rows]
                    nextValues[index] = event.target.value
                    onChange(nextValues)
                  }}
                  className="h-9 text-sm bg-white"
                />
              )}
            </div>
            <Button
              type="button"
              variant="ghost"
              size="sm"
              className="mt-1 h-8 px-2 text-red-600"
              onClick={() => onChange(rows.filter((_, rowIndex) => rowIndex !== index))}
              disabled={rows.length <= 1}
            >
              <Trash2 className="h-3.5 w-3.5" />
            </Button>
          </div>
        ))}
      </div>
    </div>
  )
}

function getCreativeCompletion(form: RequestFormState) {
  if (form.creativeType === "SINGLE_VIDEO") {
    const items = [
      { label: "Creative name", ok: !!form.creativeName },
      { label: "Facebook Page ID", ok: !!form.facebookPageId },
      { label: "Message", ok: hasAnyTextVariation(form.singleVideoPrimaryTexts, form.singleVideoPrimaryText) },
      { label: "Headline", ok: hasAnyTextVariation(form.singleVideoHeadlines, form.singleVideoHeadline) },
      { label: "CTA", ok: !!form.singleVideoCallToAction },
      { label: "Video source", ok: !!(form.singleVideoVideo.uploadedAssetId || form.singleVideoVideo.videoId) },
    ]
    return { complete: items.every((item) => item.ok), items }
  }
  if (form.creativeType === "CAROUSEL_IMAGE") {
    const items = [
      { label: "Creative name", ok: !!form.creativeName },
      { label: "Facebook Page ID", ok: !!form.facebookPageId },
      { label: "CTA", ok: !!form.carouselCallToAction },
      { label: "At least 2 cards", ok: form.carouselCards.length >= 2 },
      { label: "Cards complete", ok: form.carouselCards.every((card) => !!card.headline && !!(card.image.uploadedAssetId || card.image.imageHash || card.image.imageUrl)) },
    ]
    return { complete: items.every((item) => item.ok), items }
  }
  if (form.creativeType === "FLEXIBLE") {
    const items = [
      { label: "Creative name", ok: !!form.creativeName },
      { label: "Facebook Page ID", ok: !!form.facebookPageId },
      { label: "Primary text", ok: hasAnyTextVariation(form.flexiblePrimaryTexts) },
      { label: "Headline", ok: hasAnyTextVariation(form.flexibleHeadlines) },
      { label: "CTA", ok: !!form.flexibleCallToAction },
      { label: "Link URL or app fallback", ok: true },
      { label: "At least 1 asset", ok: form.flexibleAssets.length >= 1 },
      {
        label: "Assets complete",
        ok: form.flexibleAssets.length > 0 && form.flexibleAssets.every((asset) => asset.assetType === "VIDEO"
          ? !!(asset.video.uploadedAssetId || asset.video.videoId)
          : !!(asset.image.uploadedAssetId || asset.image.imageHash || asset.image.imageUrl)),
      },
    ]
    return { complete: items.every((item) => item.ok), items }
  }
  if (form.creativeType === "EXISTING_POST") {
    const items = [
      { label: "Creative name", ok: !!form.creativeName },
      { label: "Facebook Page ID", ok: !!form.facebookPageId },
      { label: "Source Post ID", ok: !!form.existingPostId },
    ]
    return { complete: items.every((item) => item.ok), items }
  }
  const items = [
    { label: "Creative name", ok: !!form.creativeName },
    { label: "Facebook Page ID", ok: !!form.facebookPageId },
    { label: "Message", ok: hasAnyTextVariation(form.singleImagePrimaryTexts, form.singleImagePrimaryText) },
    { label: "Headline", ok: hasAnyTextVariation(form.singleImageHeadlines, form.singleImageHeadline) },
    { label: "CTA", ok: !!form.singleImageCallToAction },
    { label: "Image source", ok: !!(form.singleImageImage.uploadedAssetId || form.singleImageImage.imageHash || form.singleImageImage.imageUrl) },
  ]
  return { complete: items.every((item) => item.ok), items }
}

function normalizeVariationRows(values?: string[]): string[] {
  const nextValues = Array.isArray(values) ? values.slice(0, maxCreativeTextVariations) : []
  return nextValues.length > 0 ? nextValues : [""]
}

function getFirstFilledVariation(values?: string[], fallback = ""): string {
  const found = normalizeVariationRows(values)
    .map((value) => value.trim())
    .find((value) => value.length > 0)
  return found || fallback
}

function hasAnyTextVariation(values?: string[], fallback = ""): boolean {
  return !!getFirstFilledVariation(values, fallback)
}

function getPreviewImage(form: RequestFormState): { url: string; requiresAuth: boolean } {
  if (form.creativeType === "SINGLE_VIDEO") return getSelectionPreviewSource(form.singleVideoThumbnail)
  if (form.creativeType === "CAROUSEL_IMAGE") return getSelectionPreviewSource(form.carouselCards[0]?.image)
  if (form.creativeType === "FLEXIBLE") {
    const firstAsset = form.flexibleAssets[0]
    if (!firstAsset) return { url: "", requiresAuth: false }
    return firstAsset.assetType === "VIDEO" ? getSelectionPreviewSource(firstAsset.thumbnail) : getSelectionPreviewSource(firstAsset.image)
  }
  return getSelectionPreviewSource(form.singleImageImage)
}

function getPreviewHeadline(form: RequestFormState): string {
  if (form.creativeType === "SINGLE_VIDEO") return getFirstFilledVariation(form.singleVideoHeadlines, form.singleVideoHeadline)
  if (form.creativeType === "CAROUSEL_IMAGE") return form.carouselCards[0]?.headline || ""
  if (form.creativeType === "FLEXIBLE") return getFirstFilledVariation(form.flexibleHeadlines)
  if (form.creativeType === "EXISTING_POST") return form.existingPostId ? `Existing Post ${form.existingPostId}` : "Existing post preview"
  return getFirstFilledVariation(form.singleImageHeadlines, form.singleImageHeadline)
}

function getPreviewMessage(form: RequestFormState): string {
  if (form.creativeType === "SINGLE_VIDEO") return getFirstFilledVariation(form.singleVideoPrimaryTexts, form.singleVideoPrimaryText)
  if (form.creativeType === "CAROUSEL_IMAGE") return form.carouselPrimaryText || `${form.carouselCards.length} carousel cards`
  if (form.creativeType === "FLEXIBLE") return getFirstFilledVariation(form.flexiblePrimaryTexts) || `${form.flexibleAssets.length} flexible assets`
  if (form.creativeType === "EXISTING_POST") return "Existing post preview will be resolved from Meta post at execution time."
  return getFirstFilledVariation(form.singleImagePrimaryTexts, form.singleImagePrimaryText)
}

function getPreviewCta(form: RequestFormState): string {
  if (form.creativeType === "SINGLE_VIDEO") return formatCta(form.singleVideoCallToAction)
  if (form.creativeType === "CAROUSEL_IMAGE") return formatCta(form.carouselCallToAction)
  if (form.creativeType === "FLEXIBLE") return formatCta(form.flexibleCallToAction)
  if (form.creativeType === "EXISTING_POST") return "OPEN POST"
  return formatCta(form.singleImageCallToAction)
}

function formatCta(value: string): string {
  return value ? value.replaceAll("_", " ") : "LEARN MORE"
}























