"use client"

import { useState } from "react"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Textarea } from "@/components/ui/textarea"
import { Button } from "@/components/ui/button"
import { Switch } from "@/components/ui/switch"
import { Tv, ChevronDown, ChevronUp, Wand2 } from "lucide-react"
import type { RequestFormState } from "./create-request-content"
import { buildAdName, useAutoGeneratedNameField } from "./naming"

interface Props {
  form: RequestFormState
  onChange: (patch: Partial<RequestFormState>) => void
}

export function AdSection({ form, onChange }: Props) {
  const [advancedOpen, setAdvancedOpen] = useState(false)
  const generatedAdName = buildAdName(form)
  const { isAutoEnabled: isAutoNameEnabled, setIsAutoEnabled, applyGeneratedName, markManual } = useAutoGeneratedNameField(
    form.adName,
    generatedAdName,
    (value) => onChange({ adName: value })
  )

  return (
    <Card className="border-slate-200">
      <CardHeader className="pb-3">
        <CardTitle className="text-sm font-semibold text-slate-900 flex items-center gap-2">
          <Tv className="w-4 h-4 text-slate-500" />
          Ad
        </CardTitle>
      </CardHeader>
      <CardContent className="space-y-4">
        <div className="space-y-1.5">
          <div className="flex items-center justify-between gap-3">
            <Label className="text-xs font-medium text-slate-700">Ad Name <span className="text-red-500">*</span></Label>
            <div className="flex items-center gap-2 text-[11px] text-slate-600">
              <Wand2 className="w-3.5 h-3.5 text-slate-400" />
              <span>Auto-generate</span>
              <Switch checked={isAutoNameEnabled} onCheckedChange={(checked) => {
                setIsAutoEnabled(checked)
                if (checked) applyGeneratedName()
              }} />
            </div>
          </div>
          <Input
            placeholder="e.g. US_18-65_ALL_AUTO_IMG"
            className="h-9 text-sm"
            value={form.adName}
            onChange={e => {
              markManual()
              onChange({ adName: e.target.value })
            }}
          />
          <div className="rounded-md border border-slate-200 bg-slate-50 px-3 py-2 space-y-1.5">
            <p className="text-[11px] text-slate-500">Pattern: <code className="rounded bg-white px-1 py-0.5">ADSET_CREATIVE</code></p>
            <p className={`text-xs font-mono ${generatedAdName ? "text-slate-700" : "text-slate-400 italic"}`}>
              {generatedAdName || "Complete ad set naming first to generate an ad name."}
            </p>
            {!isAutoNameEnabled && generatedAdName ? (
              <button
                type="button"
                onClick={applyGeneratedName}
                className="text-[11px] font-medium text-blue-600 hover:text-blue-700"
              >
                Use generated name
              </button>
            ) : null}
          </div>
        </div>

        {/* Advanced collapsible */}
        <div className="border border-slate-200 rounded-lg overflow-hidden">
          <button
            type="button"
            onClick={() => setAdvancedOpen(v => !v)}
            className="w-full flex items-center justify-between px-4 py-2.5 bg-slate-50 hover:bg-slate-100 transition-colors"
          >
            <span className="text-xs font-medium text-slate-600">Advanced Settings</span>
            {advancedOpen ? <ChevronUp className="w-4 h-4 text-slate-400" /> : <ChevronDown className="w-4 h-4 text-slate-400" />}
          </button>
          {advancedOpen && (
            <div className="px-4 py-3 space-y-1.5">
              <Label className="text-xs font-medium text-slate-700">Tracking Specs JSON <span className="text-slate-400 font-normal">(optional)</span></Label>
              <Textarea
                placeholder={'[{"action.type":["app_install"],"app":[1234567890]}]'}
                className="text-xs font-mono resize-none"
                rows={4}
                value={form.trackingSpecs}
                onChange={e => onChange({ trackingSpecs: e.target.value })}
              />
              <p className="text-[11px] text-slate-400">Raw JSON array for tracking specs. Leave empty if not required.</p>
            </div>
          )}
        </div>
      </CardContent>
    </Card>
  )
}

