"use client"

import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Badge } from "@/components/ui/badge"
import { Switch } from "@/components/ui/switch"
import { Checkbox } from "@/components/ui/checkbox"
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select"
import { Megaphone, X, Info, AlertTriangle, Wand2 } from "lucide-react"
import type { RequestFormState } from "./create-request-content"
import type { MetaAppMappingDto, MetaBidStrategyPresetDto, MetaObjectivePresetDto } from "@/types/meta-ads"
import {
  bidStrategyRequiresBidAmount,
  bidStrategyRequiresRoasGoal,
  getAllowedPerformanceGoalsForBidStrategy,
  getAllowedPerformanceGoalTypes,
  getBidStrategyDisabledReason,
  isBidStrategyCompatible,
  isBidStrategySupported,
  isPerformanceGoalCompatibleWithBidStrategy,
  resolveOptimizationGoal,
} from "./constants"
import { buildCampaignName, useAutoGeneratedNameField } from "./naming"
import { resolveMetaAppMappingPlatform } from "./platform"

const specialAdCategoryOptions = ["CREDIT", "EMPLOYMENT", "HOUSING", "ISSUES_ELECTIONS_POLITICS"]

interface Props {
  form: RequestFormState
  onChange: (patch: Partial<RequestFormState>) => void
  objectives: MetaObjectivePresetDto[]
  bidStrategies: MetaBidStrategyPresetDto[]
  currencyCode?: string | null
  selectedAppMapping?: MetaAppMappingDto | null
}

export function CampaignSettingsSection({ form, onChange, objectives, bidStrategies, currencyCode, selectedAppMapping }: Props) {
  const currency = (currencyCode ?? "USD").trim() || "USD"
  const isCBO = form.budgetStrategy === "CBO"
  const bidAmountRequired = bidStrategyRequiresBidAmount(form.bidStrategy)
  const roasGoalRequired = bidStrategyRequiresRoasGoal(form.bidStrategy)
  const selectedBidStrategySupported = isBidStrategySupported(form.bidStrategy)
  const selectedBidStrategyCompatible = isBidStrategyCompatible(form.performanceGoalType, form.bidStrategy)
  const selectedBidStrategy = bidStrategies.find((strategy) => strategy.key === form.bidStrategy)
  const selectedAppPlatform = resolveMetaAppMappingPlatform(selectedAppMapping)
  const isAppPromotionObjective = form.campaignObjective.trim().toUpperCase() === "OUTCOME_APP_PROMOTION"
  const canEnableSkan = selectedAppPlatform === "IOS" && isAppPromotionObjective
  const skanDisabledReason = selectedAppPlatform !== "IOS"
    ? "iOS 14+ / SKAN chỉ áp dụng cho app iOS."
    : !isAppPromotionObjective
      ? "iOS 14+ / SKAN chỉ áp dụng cho objective App Promotion."
      : ""
  const selectedBidStrategyLabel = selectedBidStrategy?.key === "LOWEST_COST_WITHOUT_CAP" && form.performanceGoalType === "VALUE"
    ? selectedBidStrategy.contextualValueLabel || selectedBidStrategy.metaUiLabel || selectedBidStrategy.label
    : selectedBidStrategy?.metaUiLabel || selectedBidStrategy?.label
  const generatedCampaignName = buildCampaignName(form, selectedAppMapping)
  const { isAutoEnabled: isAutoNameEnabled, setIsAutoEnabled, applyGeneratedName, markManual } = useAutoGeneratedNameField(
    form.campaignName,
    generatedCampaignName,
    (value) => onChange({ campaignName: value })
  )

  const toggleCategory = (category: string) => {
    const current = form.specialAdCategories
    onChange({
      specialAdCategories: current.includes(category)
        ? current.filter((value) => value !== category)
        : [...current, category],
    })
  }

  const handleBidStrategyChange = (value: string) => {
    const allowedByStrategy = getAllowedPerformanceGoalsForBidStrategy(value)
    const allowedByObjective = getAllowedPerformanceGoalTypes(form.campaignObjective)
    const nextGoalType = isPerformanceGoalCompatibleWithBidStrategy(form.performanceGoalType, value)
      ? form.performanceGoalType
      : (allowedByStrategy.find((goal) => allowedByObjective.includes(goal))
        ?? allowedByStrategy[0]
        ?? form.performanceGoalType)

    onChange({
      bidStrategy: value,
      performanceGoalType: nextGoalType,
      optimizationGoal: resolveOptimizationGoal(nextGoalType),
      bidAmount: bidStrategyRequiresBidAmount(value) ? form.bidAmount : "",
      roasAverageFloor: bidStrategyRequiresRoasGoal(value) ? form.roasAverageFloor : "",
    })
  }

  return (
    <Card>
      <CardHeader className="pb-3">
        <CardTitle className="flex items-center gap-2 text-sm font-semibold text-foreground">
          <Megaphone className="h-4 w-4 text-muted-foreground" />
          Campaign Settings
        </CardTitle>
      </CardHeader>
      <CardContent className="space-y-4">
        <div className="space-y-1.5">
          <div className="flex flex-col gap-2 sm:flex-row sm:items-center sm:justify-between">
            <Label className="text-xs font-medium text-foreground">
              Campaign Name <span className="text-destructive">*</span>
            </Label>
            <div className="flex items-center gap-2 text-[11px] text-muted-foreground">
              <Wand2 className="h-3.5 w-3.5 text-muted-foreground" />
              <span>Auto-generate</span>
              <Switch checked={isAutoNameEnabled} onCheckedChange={(checked) => {
                setIsAutoEnabled(checked)
                if (checked) applyGeneratedName()
              }} />
            </div>
          </div>
          <Input
            placeholder="{AppName}_{Country}_{Platform}_{Objective}_{YYYYMMDD}"
            value={form.campaignName}
            onChange={(event) => {
              markManual()
              onChange({ campaignName: event.target.value })
            }}
            className="h-9 text-sm"
          />
          <div className="space-y-1.5 rounded-md border border-border bg-muted/40 px-3 py-2">
            <p className="text-[11px] text-muted-foreground">Pattern: <code className="rounded bg-background px-1 py-0.5 text-foreground">APP_GEO_PLATFORM_OBJECTIVE_YYYYMMDD</code></p>
            <p className={`font-mono text-xs ${generatedCampaignName ? "text-foreground" : "text-muted-foreground italic"}`}>
              {generatedCampaignName || "Select an app and geo targeting to generate a campaign name."}
            </p>
            {!isAutoNameEnabled && generatedCampaignName ? (
              <button
                type="button"
                onClick={applyGeneratedName}
                className="text-[11px] font-medium text-primary hover:underline"
              >
                Use generated name
              </button>
            ) : null}
          </div>
        </div>

        <div className="grid grid-cols-1 gap-4 sm:grid-cols-2">
          <div className="space-y-1.5">
            <Label className="text-xs font-medium text-foreground">Buying Type</Label>
            <Select value={form.buyingType} onValueChange={(value) => onChange({ buyingType: value })}>
              <SelectTrigger className="h-9 text-sm">
                <SelectValue />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="AUCTION">AUCTION</SelectItem>
                <SelectItem value="RESERVED">RESERVED</SelectItem>
              </SelectContent>
            </Select>
          </div>

          <div className="space-y-1.5">
            <Label className="text-xs font-medium text-foreground">
              Campaign Objective <span className="text-destructive">*</span>
            </Label>
            <Select
              value={form.campaignObjective}
              onValueChange={(value) => onChange({ campaignObjective: value, objective: value })}
            >
              <SelectTrigger className="h-9 text-sm">
                <SelectValue placeholder="Select objective..." />
              </SelectTrigger>
              <SelectContent>
                {objectives.map((objective) => (
                  <SelectItem key={objective.key} value={objective.key}>
                    <div className="py-0.5">
                      <div className="font-mono text-xs">{objective.key}</div>
                      <div className="text-[11px] text-muted-foreground">{objective.label}</div>
                    </div>
                  </SelectItem>
                ))}
              </SelectContent>
            </Select>
          </div>
        </div>

        <div className="space-y-2">
          <Label className="text-xs font-medium text-foreground">
            Budget Strategy <span className="text-destructive">*</span>
          </Label>
          <div className="grid w-full grid-cols-1 overflow-hidden rounded-md border border-border sm:flex sm:w-fit">
            {(["CBO", "ABO"] as const).map((strategy) => (
              <button
                key={strategy}
                type="button"
                onClick={() => onChange({ budgetStrategy: strategy })}
                className={`px-5 py-2 text-xs font-semibold transition-colors ${
                  form.budgetStrategy === strategy
                    ? "bg-primary text-primary-foreground"
                    : "bg-background text-muted-foreground hover:bg-accent hover:text-accent-foreground"
                } ${strategy === "ABO" ? "border-l border-border" : ""}`}
              >
                {strategy === "CBO" ? "Advantage+ campaign budget" : "Ad set budget"}
              </button>
            ))}
          </div>
          <p className="flex items-start gap-1.5 text-[11px] text-muted-foreground">
            <Info className="w-3 h-3 mt-0.5 flex-shrink-0" />
            Use either campaign-level budget or ad set-level budget, not both.
          </p>
        </div>

        <div className="space-y-2 rounded-md border border-border bg-muted/40 px-3 py-3">
          <div className="flex items-start gap-3">
            <Checkbox
              checked={form.isAdSetBudgetSharingEnabled}
              onCheckedChange={(checked) => onChange({ isAdSetBudgetSharingEnabled: checked === true })}
              disabled={isCBO}
              className="mt-0.5"
            />
            <div className="space-y-1">
              <div className="flex items-center gap-2 flex-wrap">
                <Label className="text-sm font-medium text-foreground">
                  Share some of your budget with other ad sets
                </Label>
                {isCBO ? (
                  <Badge className="bg-muted px-1.5 py-0 text-[10px] text-muted-foreground">Only for Ad set budget</Badge>
                ) : (
                  <Badge className="bg-emerald-500/10 px-1.5 py-0 text-[10px] text-emerald-700 dark:text-emerald-400">Default on</Badge>
                )}
              </div>
              <p className="text-[11px] leading-relaxed text-muted-foreground">
                We&apos;ll share up to 20% of your ad set budget with other ad sets within this campaign when it&apos;s likely to improve performance.
              </p>
            </div>
          </div>
        </div>

        <div
          className={`rounded-md border px-3 py-3 ${canEnableSkan ? "border-primary/25 bg-primary/10" : "border-border bg-muted/40"}`}
          title={canEnableSkan ? "Bật thủ công cho campaign iOS 14+ / SKAdNetwork." : skanDisabledReason}
        >
          <div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between">
            <div className="space-y-1">
              <div className="flex items-center gap-2 flex-wrap">
                <Label className="text-sm font-medium text-foreground">iOS 14+ campaign (SKAdNetwork)</Label>
                <Badge className="bg-muted px-1.5 py-0 text-[10px] text-muted-foreground">Manual</Badge>
                {form.isSkadnetworkAttribution ? (
                  <Badge className="bg-primary/10 px-1.5 py-0 text-[10px] text-primary">Enabled</Badge>
                ) : null}
              </div>
              <p className="text-[11px] leading-relaxed text-muted-foreground">
                Bật khi campaign App Promotion cho app iOS cần dùng Meta SKAdNetwork attribution. Nexus không tự bật cờ này.
              </p>
              {!canEnableSkan ? (
                <p className="flex items-start gap-1 text-[11px] text-muted-foreground">
                  <Info className="w-3 h-3 mt-0.5 flex-shrink-0" />
                  {skanDisabledReason || "Chọn iOS app mapping và App Promotion objective để bật."}
                </p>
              ) : null}
            </div>
            <Switch
              checked={form.isSkadnetworkAttribution && canEnableSkan}
              disabled={!canEnableSkan}
              onCheckedChange={(checked) => onChange({ isSkadnetworkAttribution: checked === true })}
            />
          </div>
        </div>
        <div className={`space-y-2 transition-opacity ${isCBO ? "opacity-100" : "opacity-40 pointer-events-none"}`}>
          <div className="flex items-center gap-2">
            <Label className="text-xs font-medium text-foreground">Advantage+ campaign budget</Label>
            {isCBO ? (
              <Badge className="bg-primary/10 px-1.5 py-0 text-[10px] text-primary">CBO</Badge>
            ) : (
              <Badge className="bg-muted px-1.5 py-0 text-[10px] text-muted-foreground">Disabled in ABO mode</Badge>
            )}
          </div>
          <div className="grid grid-cols-1 gap-3 sm:grid-cols-2">
            <div className="space-y-1">
              <Label className="text-[11px] text-muted-foreground">
                Daily Budget <span className="text-destructive">*</span>
              </Label>
              <div className="relative">
                <span className="absolute left-2.5 top-1/2 -translate-y-1/2 text-xs text-muted-foreground">{currency}</span>
                <Input
                  placeholder="0.00"
                  className="pl-12 h-9 text-sm"
                  value={form.campaignDailyBudget}
                  onChange={(event) => onChange({ campaignDailyBudget: event.target.value })}
                  disabled={!isCBO}
                />
              </div>
            </div>
            <div className="space-y-1">
              <Label className="text-[11px] text-muted-foreground">Lifetime Budget</Label>
              <div className="relative">
                <span className="absolute left-2.5 top-1/2 -translate-y-1/2 text-xs text-muted-foreground">{currency}</span>
                <Input
                  placeholder="0.00"
                  className="pl-12 h-9 text-sm"
                  value={form.campaignLifetimeBudget}
                  onChange={(event) => onChange({ campaignLifetimeBudget: event.target.value })}
                  disabled={!isCBO}
                />
              </div>
            </div>
          </div>
        </div>
        <p className="text-[11px] text-muted-foreground">{`Enter budget in normal ${currency} units. Nexus converts it to Meta minor units during execution.`}</p>

        <div className="space-y-1.5">
          <Label className="text-xs font-medium text-foreground">
            Special Ad Categories <span className="font-normal text-muted-foreground">(optional)</span>
          </Label>
          <div className="flex flex-wrap gap-1.5">
            {specialAdCategoryOptions.map((category) => (
              <button
                key={category}
                type="button"
                onClick={() => toggleCategory(category)}
                className={`px-2.5 py-1 rounded text-[11px] font-medium border transition-colors ${
                  form.specialAdCategories.includes(category)
                    ? "border-amber-500/40 bg-amber-500/10 text-amber-800 dark:text-amber-300"
                    : "border-border bg-background text-muted-foreground hover:border-amber-500/40 hover:text-foreground"
                }`}
              >
                {category}
                {form.specialAdCategories.includes(category) ? <X className="w-2.5 h-2.5 inline ml-1" /> : null}
              </button>
            ))}
          </div>
        </div>
        <p className="text-[11px] text-muted-foreground">{`Enter budget in normal ${currency} units. Nexus converts it to Meta minor units during execution.`}</p>

        <div className="space-y-1.5">
          <Label className="text-xs font-medium text-foreground">
            Bid Strategy <span className="text-destructive">*</span>
          </Label>
          <Select value={form.bidStrategy} onValueChange={handleBidStrategyChange}>
            <SelectTrigger className={`h-9 w-full text-sm sm:w-72 ${(bidAmountRequired && !form.bidAmount.trim()) || (roasGoalRequired && !form.roasAverageFloor.trim()) ? "border-amber-500 ring-1 ring-amber-500/40" : ""}`}>
              {selectedBidStrategy ? (
                <div className="min-w-0 text-left">
                  <div className="text-sm font-medium truncate">{selectedBidStrategyLabel}</div>
                  <div className="truncate font-mono text-[10px] text-muted-foreground">{selectedBidStrategy.key}</div>
                </div>
              ) : (
                <SelectValue placeholder="Select..." />
              )}
            </SelectTrigger>
            <SelectContent>
              {bidStrategies.map((strategy) => {
                const disabled = !isBidStrategySupported(strategy.key)
                return (
                  <SelectItem key={strategy.key} value={strategy.key} disabled={disabled}>
                    <div className="py-0.5">
                      <div className={`text-sm font-medium ${disabled ? "text-muted-foreground line-through" : ""}`}>{strategy.key === "LOWEST_COST_WITHOUT_CAP" && form.performanceGoalType === "VALUE" ? strategy.contextualValueLabel || strategy.metaUiLabel || strategy.label : strategy.metaUiLabel || strategy.label}</div>
                      <div className="font-mono text-[11px] text-muted-foreground">{strategy.key}</div>
                    </div>
                  </SelectItem>
                )
              })}
            </SelectContent>
          </Select>
          {roasGoalRequired ? (
            <div className="space-y-1.5">
              <Label className="text-xs font-medium text-foreground">
                ROAS Goal <span className="text-destructive">*</span>
              </Label>
              <div className="relative w-full sm:w-48">
                <Input
                  type="number"
                  min="0"
                  step="0.01"
                  placeholder="2.0"
                  className={`h-9 pr-8 text-sm ${!form.roasAverageFloor.trim() ? "border-amber-500 ring-1 ring-amber-500/40" : ""}`}
                  value={form.roasAverageFloor}
                  onChange={(event) => onChange({ roasAverageFloor: event.target.value })}
                />
                <span className="absolute right-2.5 top-1/2 -translate-y-1/2 text-xs text-muted-foreground">x</span>
              </div>
              <p className="flex items-start gap-1 text-[11px] text-muted-foreground">
                <Info className="w-3 h-3 mt-0.5 flex-shrink-0" />
                Enter target ROAS as a multiplier. Example: 2.0 means 2.0x ROAS.
              </p>
            </div>
          ) : null}
          {selectedBidStrategy ? (
            <div className={`space-y-1 rounded-md border px-3 py-2 ${selectedBidStrategySupported && selectedBidStrategyCompatible ? "border-border bg-muted/40" : "border-amber-500/25 bg-amber-500/10"}`}>
              <p className={`text-[11px] font-semibold ${selectedBidStrategySupported && selectedBidStrategyCompatible ? "text-foreground" : "text-amber-800 dark:text-amber-300"}`}>{selectedBidStrategyLabel} ({selectedBidStrategy.key})</p>
              <p className={`text-[11px] leading-relaxed ${selectedBidStrategySupported && selectedBidStrategyCompatible ? "text-muted-foreground" : "text-amber-800 dark:text-amber-200"}`}>{selectedBidStrategy.description}</p>
              {(!selectedBidStrategySupported || !selectedBidStrategyCompatible) ? <p className="text-[11px] text-amber-800 dark:text-amber-200">{getBidStrategyDisabledReason(selectedBidStrategy.key, form.performanceGoalType)}</p> : null}
            </div>
          ) : null}
          <p className="text-[11px] text-muted-foreground">Some options are unavailable because they require additional fields or are not yet supported in Nexus.</p>
          {bidAmountRequired ? (
            <p className="flex items-start gap-1 text-[11px] text-amber-700 dark:text-amber-300">
              <AlertTriangle className="w-3 h-3 mt-0.5 flex-shrink-0" />
              This bid strategy requires a Bid Amount in the ad set section.
            </p>
          ) : roasGoalRequired ? (
            <p className="flex items-start gap-1 text-[11px] text-amber-700 dark:text-amber-300">
              <AlertTriangle className="w-3 h-3 mt-0.5 flex-shrink-0" />
              ROAS Goal is required for Minimum ROAS bidding.
            </p>
          ) : (
            <p className="text-[11px] text-muted-foreground">Lowest cost without cap can run without a bid amount.</p>
          )}
        </div>
      </CardContent>
    </Card>
  )
}





