"use client"

import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Badge } from "@/components/ui/badge"
import { Switch } from "@/components/ui/switch"
import { Checkbox } from "@/components/ui/checkbox"
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select"
import { Megaphone, X, Info, AlertTriangle, Wand2 } from "lucide-react"
import type { RequestFormState } from "./create-request-content"
import type { MetaAppMappingDto, MetaBidStrategyPresetDto, MetaObjectivePresetDto } from "@/types/meta-ads"
import { bidStrategyRequiresBidAmount, getBidStrategyDisabledReason, isBidStrategyCompatible, isBidStrategySupported } from "./constants"
import { buildCampaignName, useAutoGeneratedNameField } from "./naming"

const specialAdCategoryOptions = ["CREDIT", "EMPLOYMENT", "HOUSING", "ISSUES_ELECTIONS_POLITICS"]

interface Props {
  form: RequestFormState
  onChange: (patch: Partial<RequestFormState>) => void
  objectives: MetaObjectivePresetDto[]
  bidStrategies: MetaBidStrategyPresetDto[]
  currencyCode?: string | null
  selectedAppMapping?: MetaAppMappingDto | null
}

export function CampaignSettingsSection({ form, onChange, objectives, bidStrategies, currencyCode, selectedAppMapping }: Props) {
  const currency = (currencyCode ?? "USD").trim() || "USD"
  const isCBO = form.budgetStrategy === "CBO"
  const bidAmountRequired = bidStrategyRequiresBidAmount(form.bidStrategy)
  const selectedBidStrategySupported = isBidStrategySupported(form.bidStrategy)
  const selectedBidStrategyCompatible = isBidStrategyCompatible(form.performanceGoalType, form.bidStrategy)
  const selectedBidStrategy = bidStrategies.find((strategy) => strategy.key === form.bidStrategy)
  const selectedBidStrategyLabel = selectedBidStrategy?.key === "LOWEST_COST_WITHOUT_CAP" && form.performanceGoalType === "VALUE"
    ? selectedBidStrategy.contextualValueLabel || selectedBidStrategy.metaUiLabel || selectedBidStrategy.label
    : selectedBidStrategy?.metaUiLabel || selectedBidStrategy?.label
  const generatedCampaignName = buildCampaignName(form, selectedAppMapping)
  const { isAutoEnabled: isAutoNameEnabled, setIsAutoEnabled, applyGeneratedName, markManual } = useAutoGeneratedNameField(
    form.campaignName,
    generatedCampaignName,
    (value) => onChange({ campaignName: value })
  )

  const toggleCategory = (category: string) => {
    const current = form.specialAdCategories
    onChange({
      specialAdCategories: current.includes(category)
        ? current.filter((value) => value !== category)
        : [...current, category],
    })
  }

  const handleBidStrategyChange = (value: string) => {
    if (getBidStrategyDisabledReason(value, form.performanceGoalType)) {
      return
    }

    onChange({ bidStrategy: value })
  }

  return (
    <Card className="border-slate-200">
      <CardHeader className="pb-3">
        <CardTitle className="text-sm font-semibold text-slate-900 flex items-center gap-2">
          <Megaphone className="w-4 h-4 text-slate-500" />
          Campaign Settings
        </CardTitle>
      </CardHeader>
      <CardContent className="space-y-4">
        <div className="space-y-1.5">
          <div className="flex items-center justify-between gap-3">
            <Label className="text-xs font-medium text-slate-700">
              Campaign Name <span className="text-red-500">*</span>
            </Label>
            <div className="flex items-center gap-2 text-[11px] text-slate-600">
              <Wand2 className="w-3.5 h-3.5 text-slate-400" />
              <span>Auto-generate</span>
              <Switch checked={isAutoNameEnabled} onCheckedChange={(checked) => {
                setIsAutoEnabled(checked)
                if (checked) applyGeneratedName()
              }} />
            </div>
          </div>
          <Input
            placeholder="{AppName}_{Country}_{Platform}_{Objective}_{YYYYMMDD}"
            value={form.campaignName}
            onChange={(event) => {
              markManual()
              onChange({ campaignName: event.target.value })
            }}
            className="h-9 text-sm"
          />
          <div className="rounded-md border border-slate-200 bg-slate-50 px-3 py-2 space-y-1.5">
            <p className="text-[11px] text-slate-500">Pattern: <code className="rounded bg-white px-1 py-0.5">APP_GEO_PLATFORM_OBJECTIVE_YYYYMMDD</code></p>
            <p className={`text-xs font-mono ${generatedCampaignName ? "text-slate-700" : "text-slate-400 italic"}`}>
              {generatedCampaignName || "Select an app and geo targeting to generate a campaign name."}
            </p>
            {!isAutoNameEnabled && generatedCampaignName ? (
              <button
                type="button"
                onClick={applyGeneratedName}
                className="text-[11px] font-medium text-blue-600 hover:text-blue-700"
              >
                Use generated name
              </button>
            ) : null}
          </div>
        </div>

        <div className="grid grid-cols-2 gap-4">
          <div className="space-y-1.5">
            <Label className="text-xs font-medium text-slate-700">Buying Type</Label>
            <Select value={form.buyingType} onValueChange={(value) => onChange({ buyingType: value })}>
              <SelectTrigger className="h-9 text-sm">
                <SelectValue />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="AUCTION">AUCTION</SelectItem>
                <SelectItem value="RESERVED">RESERVED</SelectItem>
              </SelectContent>
            </Select>
          </div>

          <div className="space-y-1.5">
            <Label className="text-xs font-medium text-slate-700">
              Campaign Objective <span className="text-red-500">*</span>
            </Label>
            <Select
              value={form.campaignObjective}
              onValueChange={(value) => onChange({ campaignObjective: value, objective: value })}
            >
              <SelectTrigger className="h-9 text-sm">
                <SelectValue placeholder="Select objective..." />
              </SelectTrigger>
              <SelectContent>
                {objectives.map((objective) => (
                  <SelectItem key={objective.key} value={objective.key}>
                    <div className="py-0.5">
                      <div className="font-mono text-xs">{objective.key}</div>
                      <div className="text-[11px] text-slate-400">{objective.label}</div>
                    </div>
                  </SelectItem>
                ))}
              </SelectContent>
            </Select>
          </div>
        </div>

        <div className="space-y-2">
          <Label className="text-xs font-medium text-slate-700">
            Budget Strategy <span className="text-red-500">*</span>
          </Label>
          <div className="flex rounded-md overflow-hidden border border-slate-300 w-fit">
            {(["CBO", "ABO"] as const).map((strategy) => (
              <button
                key={strategy}
                type="button"
                onClick={() => onChange({ budgetStrategy: strategy })}
                className={`px-5 py-2 text-xs font-semibold transition-colors ${
                  form.budgetStrategy === strategy
                    ? "bg-blue-600 text-white"
                    : "bg-white text-slate-600 hover:bg-slate-50"
                } ${strategy === "ABO" ? "border-l border-slate-300" : ""}`}
              >
                {strategy === "CBO" ? "Advantage+ campaign budget" : "Ad set budget"}
              </button>
            ))}
          </div>
          <p className="flex items-start gap-1.5 text-[11px] text-slate-500">
            <Info className="w-3 h-3 mt-0.5 flex-shrink-0" />
            Use either campaign-level budget or ad set-level budget, not both.
          </p>
        </div>

        <div className="rounded-md border border-slate-200 bg-slate-50 px-3 py-3 space-y-2">
          <div className="flex items-start gap-3">
            <Checkbox
              checked={form.isAdSetBudgetSharingEnabled}
              onCheckedChange={(checked) => onChange({ isAdSetBudgetSharingEnabled: checked === true })}
              disabled={isCBO}
              className="mt-0.5"
            />
            <div className="space-y-1">
              <div className="flex items-center gap-2 flex-wrap">
                <Label className="text-sm font-medium text-slate-700">
                  Share some of your budget with other ad sets
                </Label>
                {isCBO ? (
                  <Badge className="bg-slate-100 text-slate-500 text-[10px] px-1.5 py-0">Only for Ad set budget</Badge>
                ) : (
                  <Badge className="bg-emerald-100 text-emerald-700 text-[10px] px-1.5 py-0">Default on</Badge>
                )}
              </div>
              <p className="text-[11px] leading-relaxed text-slate-600">
                We&apos;ll share up to 20% of your ad set budget with other ad sets within this campaign when it&apos;s likely to improve performance.
              </p>
            </div>
          </div>
        </div>
        <div className={`space-y-2 transition-opacity ${isCBO ? "opacity-100" : "opacity-40 pointer-events-none"}`}>
          <div className="flex items-center gap-2">
            <Label className="text-xs font-medium text-slate-700">Advantage+ campaign budget</Label>
            {isCBO ? (
              <Badge className="bg-blue-100 text-blue-700 text-[10px] px-1.5 py-0">CBO</Badge>
            ) : (
              <Badge className="bg-slate-100 text-slate-400 text-[10px] px-1.5 py-0">Disabled in ABO mode</Badge>
            )}
          </div>
          <div className="grid grid-cols-2 gap-3">
            <div className="space-y-1">
              <Label className="text-[11px] text-slate-500">
                Daily Budget <span className="text-red-500">*</span>
              </Label>
              <div className="relative">
                <span className="absolute left-2.5 top-1/2 -translate-y-1/2 text-slate-400 text-xs">{currency}</span>
                <Input
                  placeholder="0.00"
                  className="pl-12 h-9 text-sm"
                  value={form.campaignDailyBudget}
                  onChange={(event) => onChange({ campaignDailyBudget: event.target.value })}
                  disabled={!isCBO}
                />
              </div>
            </div>
            <div className="space-y-1">
              <Label className="text-[11px] text-slate-500">Lifetime Budget</Label>
              <div className="relative">
                <span className="absolute left-2.5 top-1/2 -translate-y-1/2 text-slate-400 text-xs">{currency}</span>
                <Input
                  placeholder="0.00"
                  className="pl-12 h-9 text-sm"
                  value={form.campaignLifetimeBudget}
                  onChange={(event) => onChange({ campaignLifetimeBudget: event.target.value })}
                  disabled={!isCBO}
                />
              </div>
            </div>
          </div>
        </div>
        <p className="text-[11px] text-slate-400">{`Enter budget in normal ${currency} units. Nexus converts it to Meta minor units during execution.`}</p>

        <div className="space-y-1.5">
          <Label className="text-xs font-medium text-slate-700">
            Special Ad Categories <span className="text-slate-400 font-normal">(optional)</span>
          </Label>
          <div className="flex flex-wrap gap-1.5">
            {specialAdCategoryOptions.map((category) => (
              <button
                key={category}
                type="button"
                onClick={() => toggleCategory(category)}
                className={`px-2.5 py-1 rounded text-[11px] font-medium border transition-colors ${
                  form.specialAdCategories.includes(category)
                    ? "bg-amber-100 text-amber-800 border-amber-300"
                    : "bg-white text-slate-600 border-slate-300 hover:border-amber-300"
                }`}
              >
                {category}
                {form.specialAdCategories.includes(category) ? <X className="w-2.5 h-2.5 inline ml-1" /> : null}
              </button>
            ))}
          </div>
        </div>
        <p className="text-[11px] text-slate-400">{`Enter budget in normal ${currency} units. Nexus converts it to Meta minor units during execution.`}</p>

        <div className="space-y-1.5">
          <Label className="text-xs font-medium text-slate-700">
            Bid Strategy <span className="text-red-500">*</span>
          </Label>
          <Select value={form.bidStrategy} onValueChange={handleBidStrategyChange}>
            <SelectTrigger className={`h-9 text-sm w-72 ${bidAmountRequired && !form.bidAmount.trim() ? "border-amber-400 ring-1 ring-amber-300" : ""}`}>
              {selectedBidStrategy ? (
                <div className="min-w-0 text-left">
                  <div className="text-sm font-medium truncate">{selectedBidStrategyLabel}</div>
                  <div className="text-[10px] text-slate-400 font-mono truncate">{selectedBidStrategy.key}</div>
                </div>
              ) : (
                <SelectValue placeholder="Select..." />
              )}
            </SelectTrigger>
            <SelectContent>
              {bidStrategies.map((strategy) => {
                const reason = getBidStrategyDisabledReason(strategy.key, form.performanceGoalType)
                const disabled = !!reason
                return (
                  <SelectItem key={strategy.key} value={strategy.key} disabled={disabled}>
                    <div className="py-0.5">
                      <div className={`text-sm font-medium ${disabled ? "text-slate-400 line-through" : ""}`}>{strategy.key === "LOWEST_COST_WITHOUT_CAP" && form.performanceGoalType === "VALUE" ? strategy.contextualValueLabel || strategy.metaUiLabel || strategy.label : strategy.metaUiLabel || strategy.label}</div>
                      <div className="text-[11px] text-slate-400 font-mono">{strategy.key}</div>
                      {reason ? <div className="text-[10px] text-slate-400 leading-relaxed">{reason}</div> : null}
                    </div>
                  </SelectItem>
                )
              })}
            </SelectContent>
          </Select>
          {selectedBidStrategy ? (
            <div className={`rounded-md border px-3 py-2 space-y-1 ${selectedBidStrategySupported && selectedBidStrategyCompatible ? "border-slate-200 bg-slate-50" : "border-amber-200 bg-amber-50"}`}>
              <p className={`text-[11px] font-semibold ${selectedBidStrategySupported && selectedBidStrategyCompatible ? "text-slate-700" : "text-amber-800"}`}>{selectedBidStrategyLabel} ({selectedBidStrategy.key})</p>
              <p className={`text-[11px] leading-relaxed ${selectedBidStrategySupported && selectedBidStrategyCompatible ? "text-slate-500" : "text-amber-800"}`}>{selectedBidStrategy.description}</p>
              {(!selectedBidStrategySupported || !selectedBidStrategyCompatible) ? <p className="text-[11px] text-amber-800">{getBidStrategyDisabledReason(selectedBidStrategy.key, form.performanceGoalType)}</p> : null}
            </div>
          ) : null}
          <p className="text-[11px] text-slate-400">Some options are unavailable because they require additional fields or are not yet supported in Nexus.</p>
          {bidAmountRequired ? (
            <p className="text-[11px] text-amber-700 flex items-start gap-1">
              <AlertTriangle className="w-3 h-3 mt-0.5 flex-shrink-0" />
              This bid strategy requires a Bid Amount in the ad set section.
            </p>
          ) : (
            <p className="text-[11px] text-slate-400">Lowest cost without cap can run without a bid amount.</p>
          )}
        </div>
      </CardContent>
    </Card>
  )
}







