"use client"

import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { Checkbox } from "@/components/ui/checkbox"
import { Switch } from "@/components/ui/switch"
import { Command, CommandEmpty, CommandGroup, CommandInput, CommandItem, CommandList } from "@/components/ui/command"
import { Popover, PopoverContent, PopoverTrigger } from "@/components/ui/popover"
import { metaReferenceApi } from "@/lib/api/meta-ads"
import { cn } from "@/lib/utils"
import { Check, ChevronsUpDown, Globe2, Loader2, MapPin, Users, Wand2, X } from "lucide-react"
import { useEffect, useState } from "react"
import type { MetaGeoCityReferenceDto, MetaGeoRegionDto } from "@/types/meta-ads"
import type { RequestFormState } from "./create-request-content"
import { buildAdSetName, useAutoGeneratedNameField } from "./naming"

const fallbackCountryCodes = [
  "AD", "AE", "AF", "AG", "AI", "AL", "AM", "AO", "AR", "AT", "AU", "AW", "AZ",
  "BA", "BB", "BD", "BE", "BF", "BG", "BH", "BI", "BJ", "BN", "BO", "BR", "BS", "BT", "BW", "BY", "BZ",
  "CA", "CD", "CF", "CG", "CH", "CI", "CL", "CM", "CN", "CO", "CR", "CV", "CY", "CZ",
  "DE", "DJ", "DK", "DM", "DO", "DZ",
  "EC", "EE", "EG", "ES", "ET",
  "FI", "FJ", "FM", "FR",
  "GA", "GB", "GD", "GE", "GH", "GM", "GN", "GQ", "GR", "GT", "GW", "GY",
  "HK", "HN", "HR", "HT", "HU",
  "ID", "IE", "IL", "IN", "IQ", "IS", "IT",
  "JM", "JO", "JP",
  "KE", "KG", "KH", "KI", "KM", "KN", "KR", "KW", "KY", "KZ",
  "LA", "LB", "LC", "LI", "LK", "LR", "LS", "LT", "LU", "LV", "LY",
  "MA", "MC", "MD", "ME", "MG", "MH", "MK", "ML", "MM", "MN", "MO", "MR", "MT", "MU", "MV", "MW", "MX", "MY", "MZ",
  "NA", "NE", "NG", "NI", "NL", "NO", "NP", "NR", "NZ",
  "OM",
  "PA", "PE", "PG", "PH", "PK", "PL", "PT", "PW", "PY",
  "QA",
  "RO", "RS", "RU", "RW",
  "SA", "SB", "SC", "SE", "SG", "SI", "SK", "SL", "SM", "SN", "SO", "SR", "ST", "SV", "SZ",
  "TD", "TG", "TH", "TL", "TN", "TO", "TR", "TT", "TV", "TW", "TZ",
  "UA", "UG", "US", "UY", "UZ",
  "VC", "VE", "VN", "VU",
  "WS",
  "XK",
  "YE",
  "ZA", "ZM", "ZW",
] as const
const publisherPlatformOptions = ["facebook", "instagram", "audience_network", "messenger"]
const fbPositionOptions = ["feed", "right_hand_column", "instant_article", "marketplace", "video_feeds", "story", "search", "instream_video"]
const igPositionOptions = ["stream", "story", "explore", "reels"]

const regionDisplayNames = typeof Intl !== "undefined" && typeof Intl.DisplayNames !== "undefined"
  ? new Intl.DisplayNames(["en"], { type: "region" })
  : null

const resolvedCountryCodes = [...fallbackCountryCodes]

const countryOptions = [...resolvedCountryCodes]
  .map((code) => {
    const name = regionDisplayNames?.of(code) ?? code
    const label = name && name !== code ? `${name} (${code})` : code
    return {
      code,
      label,
      searchValue: `${name} ${code}`,
    }
  })
  .sort((a, b) => a.label.localeCompare(b.label))

const countryLabelMap = Object.fromEntries(countryOptions.map((country) => [country.code, country.label])) as Record<string, string>

function getCountryLabel(countryCode: string) {
  return countryLabelMap[countryCode.toUpperCase()] ?? countryCode.toUpperCase()
}

interface Props {
  form: RequestFormState
  onChange: (patch: Partial<RequestFormState>) => void
  regions: MetaGeoRegionDto[]
  regionsLoading?: boolean
  regionsMessage?: string | null
  metaAdAccountId?: number | null
}

export function AdSetAudienceSection({ form, onChange, regions, regionsLoading = false, regionsMessage, metaAdAccountId }: Props) {
  const [countryPopoverOpen, setCountryPopoverOpen] = useState(false)
  const [cityQuery, setCityQuery] = useState("")
  const [cityResults, setCityResults] = useState<MetaGeoCityReferenceDto[]>([])
  const [cityLoading, setCityLoading] = useState(false)
  const [cityError, setCityError] = useState<string | null>(null)

  const generatedAdSetName = buildAdSetName(form)
  const { isAutoEnabled: isAutoNameEnabled, setIsAutoEnabled, applyGeneratedName, markManual } = useAutoGeneratedNameField(
    form.adSetName,
    generatedAdSetName,
    (value) => onChange({ adSetName: value })
  )

  useEffect(() => {
    if (form.geoMode !== "CITY") {
      setCityResults([])
      setCityError(null)
      setCityLoading(false)
      return
    }

    if (!metaAdAccountId) {
      setCityResults([])
      setCityError("Select a Meta ad account before searching cities.")
      setCityLoading(false)
      return
    }

    const query = cityQuery.trim()
    if (query.length < 2) {
      setCityResults([])
      setCityError(null)
      setCityLoading(false)
      return
    }

    const handle = window.setTimeout(async () => {
      try {
        setCityLoading(true)
        setCityError(null)
        const results = await metaReferenceApi.searchGeoCities(metaAdAccountId, query)
        setCityResults(results)
      } catch (error) {
        const message = error instanceof Error ? error.message : "Failed to search cities."
        setCityResults([])
        setCityError(message)
      } finally {
        setCityLoading(false)
      }
    }, 300)

    return () => window.clearTimeout(handle)
  }, [cityQuery, form.geoMode, metaAdAccountId])

  const handleNameInputChange = (value: string) => {
    markManual()
    onChange({ adSetName: value })
  }

  const setGeoMode = (geoMode: RequestFormState["geoMode"]) => {
    onChange({
      geoMode,
      countries: geoMode === "COUNTRY" ? form.countries : [],
      regionKeys: geoMode === "REGION" ? form.regionKeys : [],
      cityTargets: geoMode === "CITY" ? form.cityTargets : [],
    })
    setCountryPopoverOpen(false)
    setCityQuery("")
    setCityResults([])
    setCityError(null)
  }

  const toggleCountry = (countryCode: string) => {
    const country = countryCode.toUpperCase()
    onChange({
      countries: form.countries.includes(country)
        ? form.countries.filter((value) => value !== country)
        : [...form.countries, country],
    })
  }


  const toggleRegion = (regionKey: string) => {
    const normalized = regionKey.trim().toUpperCase()
    onChange({
      regionKeys: form.regionKeys.includes(normalized)
        ? form.regionKeys.filter((value) => value !== normalized)
        : [...form.regionKeys, normalized],
    })
  }

  const addCity = (city: MetaGeoCityReferenceDto) => {
    if (form.cityTargets.some((item) => item.key === city.key)) return
    onChange({ cityTargets: [...form.cityTargets, city] })
    setCityQuery("")
    setCityResults([])
  }

  const removeCity = (cityKey: string) => {
    onChange({ cityTargets: form.cityTargets.filter((city) => city.key !== cityKey) })
  }

  const togglePlatform = (platform: string) => {
    onChange({
      publisherPlatforms: form.publisherPlatforms.includes(platform)
        ? form.publisherPlatforms.filter((value) => value !== platform)
        : [...form.publisherPlatforms, platform],
    })
  }

  const toggleFbPos = (position: string) => {
    onChange({
      facebookPositions: form.facebookPositions.includes(position)
        ? form.facebookPositions.filter((value) => value !== position)
        : [...form.facebookPositions, position],
    })
  }

  const toggleIgPos = (position: string) => {
    onChange({
      instagramPositions: form.instagramPositions.includes(position)
        ? form.instagramPositions.filter((value) => value !== position)
        : [...form.instagramPositions, position],
    })
  }

  const geoModeDescription = (() => {
    switch (form.geoMode) {
      case "GLOBAL":
        return "Broad targeting. No explicit country or city list will be sent to Meta."
      case "REGION":
        return "Region keys are internal groupings and will be expanded into country codes at execution time."
      case "CITY":
        return "Search city references from Meta and target only the selected locations."
      default:
        return "Select one or more country codes to build geo_locations.countries."
    }
  })()

  return (
    <Card className="border-slate-200">
      <CardHeader className="pb-3">
        <CardTitle className="text-sm font-semibold text-slate-900 flex items-center gap-2">
          <Users className="w-4 h-4 text-slate-500" />
          Ad Set - Audience &amp; Placement
        </CardTitle>
      </CardHeader>
      <CardContent className="space-y-4">
        <div className="space-y-1.5">
          <div className="flex items-center justify-between gap-3">
            <Label className="text-xs font-medium text-slate-700">Ad Set Name <span className="text-red-500">*</span></Label>
            <div className="flex items-center gap-2 text-[11px] text-slate-600">
              <Wand2 className="w-3.5 h-3.5 text-slate-400" />
              <span>Auto-generate</span>
              <Switch checked={isAutoNameEnabled} onCheckedChange={(checked) => {
                setIsAutoEnabled(checked)
                if (checked) applyGeneratedName()
              }} />
            </div>
          </div>
          <Input
            placeholder="e.g. US_18-24_ALL_AUTO"
            className="h-9 text-sm"
            value={form.adSetName}
            onChange={(event) => handleNameInputChange(event.target.value)}
          />
          <div className="rounded-md border border-slate-200 bg-slate-50 px-3 py-2 space-y-1.5">
            <p className="text-[11px] text-slate-500">Pattern: <code className="rounded bg-white px-1 py-0.5">GEO_AGE_GENDER_PLACEMENT</code></p>
            <p className={`text-xs font-mono ${generatedAdSetName ? "text-slate-700" : "text-slate-400 italic"}`}>
              {generatedAdSetName || "Select a geo mode and target to generate an ad set name."}
            </p>
            {!isAutoNameEnabled && generatedAdSetName ? (
              <button
                type="button"
                onClick={applyGeneratedName}
                className="text-[11px] font-medium text-blue-600 hover:text-blue-700"
              >
                Use generated name
              </button>
            ) : null}
          </div>
        </div>

        <div className="space-y-2">
          <div className="flex items-center justify-between gap-3">
            <Label className="text-xs font-medium text-slate-700">Geo Mode <span className="text-red-500">*</span></Label>
            <span className="text-[11px] text-slate-400">One mode only</span>
          </div>
          <div className="flex rounded-md overflow-hidden border border-slate-300 w-fit">
            {(["GLOBAL", "COUNTRY", "REGION", "CITY"] as const).map((mode) => (
              <button
                key={mode}
                type="button"
                onClick={() => setGeoMode(mode)}
                className={`px-3 py-1.5 text-xs font-medium transition-colors ${form.geoMode === mode ? "bg-blue-600 text-white" : "bg-white text-slate-600 hover:bg-slate-50"} ${mode !== "GLOBAL" ? "border-l border-slate-300" : ""}`}
              >
                {mode.charAt(0) + mode.slice(1).toLowerCase()}
              </button>
            ))}
          </div>
          <div className="rounded-md border border-slate-200 bg-slate-50 px-3 py-2 text-[11px] text-slate-500">
            {geoModeDescription}
          </div>
        </div>

        {form.geoMode === "GLOBAL" ? (
          <div className="rounded-lg border border-blue-200 bg-blue-50 px-3 py-3 text-sm text-blue-900 flex items-start gap-2">
            <Globe2 className="w-4 h-4 mt-0.5 flex-shrink-0" />
            <div>
              <p className="font-medium">Global targeting</p>
              <p className="text-[12px] text-blue-800 mt-0.5">This request will not send country or city lists to Meta. App platform, age, gender, and placements still apply.</p>
            </div>
          </div>
        ) : null}

        {form.geoMode === "COUNTRY" ? (
          <div className="space-y-2">
            <Label className="text-xs font-medium text-slate-700">Countries <span className="text-red-500">*</span></Label>
            <Popover open={countryPopoverOpen} onOpenChange={setCountryPopoverOpen}>
              <PopoverTrigger asChild>
                <Button
                  type="button"
                  variant="outline"
                  role="combobox"
                  aria-expanded={countryPopoverOpen}
                  className="h-9 w-full justify-between bg-white px-3 text-left font-normal"
                >
                  <span className="min-w-0 flex-1 truncate text-left text-sm text-slate-700">
                    {form.countries.length === 0
                      ? "Select countries"
                      : form.countries.length <= 2
                        ? form.countries.map((country) => getCountryLabel(country)).join(", ")
                        : `${form.countries.length} countries selected`}
                  </span>
                  <ChevronsUpDown className="ml-2 h-4 w-4 shrink-0 opacity-50" />
                </Button>
              </PopoverTrigger>
              <PopoverContent className="w-[--radix-popover-trigger-width] min-w-[360px] p-0" align="start">
                <Command>
                  <CommandInput placeholder="Search countries by name or code..." />
                  <CommandList>
                    <CommandEmpty>No country found.</CommandEmpty>
                    <CommandGroup heading="Countries">
                      {countryOptions.map((country) => {
                        const isSelected = form.countries.includes(country.code)
                        return (
                          <CommandItem
                            key={country.code}
                            value={country.searchValue}
                            onSelect={() => toggleCountry(country.code)}
                          >
                            <Check className={cn("mr-2 h-4 w-4 shrink-0", isSelected ? "opacity-100" : "opacity-0")} />
                            <span className="min-w-0 flex-1 truncate">{country.label}</span>
                          </CommandItem>
                        )
                      })}
                    </CommandGroup>
                  </CommandList>
                </Command>
              </PopoverContent>
            </Popover>
            <p className="text-[11px] text-slate-500">Select one or more countries. Search by country name or ISO code.</p>
            {form.countries.length > 0 ? (
              <div className="flex flex-wrap gap-1.5">
                {[...form.countries]
                  .sort((left, right) => getCountryLabel(left).localeCompare(getCountryLabel(right)))
                  .map((country) => (
                    <Badge key={country} className="bg-blue-100 text-blue-800 gap-1 pr-1 text-xs max-w-full">
                      <span className="truncate">{getCountryLabel(country)}</span>
                      <button type="button" onClick={() => toggleCountry(country)}>
                        <X className="w-3 h-3" />
                      </button>
                    </Badge>
                  ))}
              </div>
            ) : null}
          </div>
        ) : null}

        {form.geoMode === "REGION" ? (
          <div className="space-y-1.5">
            <Label className="text-xs font-medium text-slate-700">Regions <span className="text-red-500">*</span></Label>
            {regionsLoading ? <p className="text-xs text-slate-500 flex items-center gap-1"><Loader2 className="w-3.5 h-3.5 animate-spin" /> Loading region references...</p> : null}
            {regionsMessage ? <p className="text-xs text-red-600">{regionsMessage}</p> : null}
            {!regionsLoading && !regionsMessage ? (
              <div className="flex flex-wrap gap-1.5">
                {regions.map((region) => (
                  <button
                    key={region.key}
                    type="button"
                    onClick={() => toggleRegion(region.key)}
                    className={`px-2.5 py-1 rounded text-[11px] font-medium border transition-colors ${
                      form.regionKeys.includes(region.key)
                        ? "bg-blue-600 text-white border-blue-600"
                        : "bg-white text-slate-600 border-slate-300 hover:border-blue-300"
                    }`}
                    title={`${region.countryCount} countries`}
                  >
                    {region.label} <span className={`ml-1 ${form.regionKeys.includes(region.key) ? "text-blue-100" : "text-slate-400"}`}>({region.countryCount})</span>
                  </button>
                ))}
              </div>
            ) : null}
            {form.regionKeys.length > 0 ? (
              <div className="flex flex-wrap gap-1.5">
                {form.regionKeys.map((regionKey) => (
                  <Badge key={regionKey} className="bg-blue-100 text-blue-800 gap-1 pr-1 text-xs">
                    {regions.find((region) => region.key === regionKey)?.label ?? regionKey}
                    <button type="button" onClick={() => toggleRegion(regionKey)}>
                      <X className="w-3 h-3" />
                    </button>
                  </Badge>
                ))}
              </div>
            ) : null}
          </div>
        ) : null}

        {form.geoMode === "CITY" ? (
          <div className="space-y-3">
            <div className="space-y-1.5">
              <Label className="text-xs font-medium text-slate-700">Cities <span className="text-red-500">*</span></Label>
              <Input
                placeholder={metaAdAccountId ? "Search city name..." : "Select a Meta ad account first"}
                className="h-9 text-sm"
                value={cityQuery}
                disabled={!metaAdAccountId}
                onChange={(event) => setCityQuery(event.target.value)}
              />
              {cityLoading ? <p className="text-xs text-slate-500 flex items-center gap-1"><Loader2 className="w-3.5 h-3.5 animate-spin" /> Searching Meta cities...</p> : null}
              {cityError ? <p className="text-xs text-red-600">{cityError}</p> : null}
            </div>
            {cityResults.length > 0 ? (
              <div className="rounded-lg border border-slate-200 bg-white max-h-56 overflow-auto divide-y divide-slate-100">
                {cityResults.map((city) => (
                  <button
                    key={city.key}
                    type="button"
                    onClick={() => addCity(city)}
                    className="w-full text-left px-3 py-2 hover:bg-slate-50 transition-colors"
                  >
                    <div className="flex items-start justify-between gap-3">
                      <div className="min-w-0">
                        <p className="text-sm font-medium text-slate-800 truncate">{city.name}</p>
                        <p className="text-[11px] text-slate-500 truncate">{[city.region, city.countryName, city.countryCode].filter(Boolean).join(" - ")}</p>
                      </div>
                      <span className="text-[10px] font-mono text-slate-400">{city.key}</span>
                    </div>
                  </button>
                ))}
              </div>
            ) : null}
            {form.cityTargets.length > 0 ? (
              <div className="flex flex-wrap gap-1.5">
                {form.cityTargets.map((city) => (
                  <Badge key={city.key} className="bg-blue-100 text-blue-800 gap-1 pr-1 text-xs max-w-full">
                    <MapPin className="w-3 h-3" />
                    <span className="truncate">{city.name}{city.countryCode ? ` (${city.countryCode})` : ""}</span>
                    <button type="button" onClick={() => removeCity(city.key)}>
                      <X className="w-3 h-3" />
                    </button>
                  </Badge>
                ))}
              </div>
            ) : null}
          </div>
        ) : null}

        <div className="grid grid-cols-2 gap-4">
          <div className="space-y-1.5">
            <Label className="text-xs font-medium text-slate-700">Age Range</Label>
            <div className="flex items-center gap-2">
              <Input type="number" min={13} max={65} className="h-9 text-sm w-20" value={form.ageMin} onChange={(event) => onChange({ ageMin: Number(event.target.value) })} />
              <span className="text-slate-400 text-sm">-</span>
              <Input type="number" min={13} max={65} className="h-9 text-sm w-20" value={form.ageMax} onChange={(event) => onChange({ ageMax: Number(event.target.value) })} />
            </div>
          </div>

          <div className="space-y-1.5">
            <Label className="text-xs font-medium text-slate-700">Gender</Label>
            <div className="flex rounded-md overflow-hidden border border-slate-300 w-fit">
              {(["ALL", "MALE", "FEMALE"] as const).map((gender) => (
                <button
                  key={gender}
                  type="button"
                  onClick={() => onChange({ gender })}
                  className={`px-3 py-1.5 text-xs font-medium transition-colors ${
                    form.gender === gender ? "bg-blue-600 text-white" : "bg-white text-slate-600 hover:bg-slate-50"
                  } ${gender !== "ALL" ? "border-l border-slate-300" : ""}`}
                >
                  {gender === "ALL" ? "All" : gender.charAt(0) + gender.slice(1).toLowerCase()}
                </button>
              ))}
            </div>
          </div>
        </div>

        <div className="space-y-2">
          <Label className="text-xs font-medium text-slate-700">Placement Mode</Label>
          <div className="flex rounded-md overflow-hidden border border-slate-300 w-fit">
            {(["AUTOMATIC", "MANUAL"] as const).map((mode) => (
              <button
                key={mode}
                type="button"
                onClick={() => onChange({ placementMode: mode })}
                className={`px-4 py-1.5 text-xs font-medium transition-colors ${
                  form.placementMode === mode ? "bg-blue-600 text-white" : "bg-white text-slate-600 hover:bg-slate-50"
                } ${mode === "MANUAL" ? "border-l border-slate-300" : ""}`}
              >
                {mode.charAt(0) + mode.slice(1).toLowerCase()}
              </button>
            ))}
          </div>

          {form.placementMode === "MANUAL" ? (
            <div className="bg-slate-50 border border-slate-200 rounded-lg p-3 space-y-3">
              <p className="text-[11px] text-slate-500">Manual placement values must map cleanly to backend payload fields.</p>
              <div className="space-y-2">
                <p className="text-xs font-medium text-slate-700">Publisher Platforms</p>
                <div className="flex flex-wrap gap-3">
                  {publisherPlatformOptions.map((platform) => (
                    <label key={platform} className="flex items-center gap-1.5 text-xs text-slate-600 cursor-pointer">
                      <Checkbox checked={form.publisherPlatforms.includes(platform)} onCheckedChange={() => togglePlatform(platform)} />
                      {platform}
                    </label>
                  ))}
                </div>
              </div>
              <div className="space-y-2">
                <p className="text-xs font-medium text-slate-700">Facebook Positions</p>
                <div className="flex flex-wrap gap-3">
                  {fbPositionOptions.map((position) => (
                    <label key={position} className="flex items-center gap-1.5 text-xs text-slate-600 cursor-pointer">
                      <Checkbox checked={form.facebookPositions.includes(position)} onCheckedChange={() => toggleFbPos(position)} />
                      {position}
                    </label>
                  ))}
                </div>
              </div>
              <div className="space-y-2">
                <p className="text-xs font-medium text-slate-700">Instagram Positions</p>
                <div className="flex flex-wrap gap-3">
                  {igPositionOptions.map((position) => (
                    <label key={position} className="flex items-center gap-1.5 text-xs text-slate-600 cursor-pointer">
                      <Checkbox checked={form.instagramPositions.includes(position)} onCheckedChange={() => toggleIgPos(position)} />
                      {position}
                    </label>
                  ))}
                </div>
              </div>
            </div>
          ) : null}
        </div>

        <div className="space-y-1.5 opacity-50">
          <Label className="text-xs font-medium text-slate-700">Custom Audience <span className="text-[10px] bg-slate-200 text-slate-500 px-1.5 py-0.5 rounded font-normal ml-1">Coming soon</span></Label>
          <Input disabled placeholder="Custom audience selection" className="h-9 text-sm" />
        </div>
      </CardContent>
    </Card>
  )
}










