"use client"

import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { Checkbox } from "@/components/ui/checkbox"
import { Switch } from "@/components/ui/switch"
import { Command, CommandEmpty, CommandGroup, CommandInput, CommandItem, CommandList } from "@/components/ui/command"
import { Popover, PopoverContent, PopoverTrigger } from "@/components/ui/popover"
import { GeoCountryGroupManager } from "@/components/shared/geo-country-group-manager"
import { metaReferenceApi } from "@/lib/api/meta-ads"
import { cn } from "@/lib/utils"
import { AlertTriangle, Check, ChevronsUpDown, Globe2, Loader2, MapPin, Users, Wand2, X } from "lucide-react"
import { useEffect, useState } from "react"
import type { MetaAdLocaleReferenceDto, MetaGeoCityReferenceDto, GeoCountryGroupDto, MetaGeoRegionDto, MetaRegulationIdentityDto, MetaRegionalRegulationIdentitiesDto } from "@/types/meta-ads"
import type { RequestFormState } from "./create-request-content"
import { buildAdSetName, useAutoGeneratedNameField } from "./naming"

const fallbackCountryCodes = [
  "AD", "AE", "AF", "AG", "AI", "AL", "AM", "AO", "AR", "AT", "AU", "AW", "AZ",
  "BA", "BB", "BD", "BE", "BF", "BG", "BH", "BI", "BJ", "BN", "BO", "BR", "BS", "BT", "BW", "BY", "BZ",
  "CA", "CD", "CF", "CG", "CH", "CI", "CL", "CM", "CN", "CO", "CR", "CV", "CY", "CZ",
  "DE", "DJ", "DK", "DM", "DO", "DZ",
  "EC", "EE", "EG", "ES", "ET",
  "FI", "FJ", "FM", "FR",
  "GA", "GB", "GD", "GE", "GH", "GM", "GN", "GQ", "GR", "GT", "GW", "GY",
  "HK", "HN", "HR", "HT", "HU",
  "ID", "IE", "IL", "IN", "IQ", "IS", "IT",
  "JM", "JO", "JP",
  "KE", "KG", "KH", "KI", "KM", "KN", "KR", "KW", "KY", "KZ",
  "LA", "LB", "LC", "LI", "LK", "LR", "LS", "LT", "LU", "LV", "LY",
  "MA", "MC", "MD", "ME", "MG", "MH", "MK", "ML", "MM", "MN", "MO", "MR", "MT", "MU", "MV", "MW", "MX", "MY", "MZ",
  "NA", "NE", "NG", "NI", "NL", "NO", "NP", "NR", "NZ",
  "OM",
  "PA", "PE", "PG", "PH", "PK", "PL", "PT", "PW", "PY",
  "QA",
  "RO", "RS", "RU", "RW",
  "SA", "SB", "SC", "SE", "SG", "SI", "SK", "SL", "SM", "SN", "SO", "SR", "ST", "SV", "SZ",
  "TD", "TG", "TH", "TL", "TN", "TO", "TR", "TT", "TV", "TW", "TZ",
  "UA", "UG", "US", "UY", "UZ",
  "VC", "VE", "VN", "VU",
  "WS",
  "XK",
  "YE",
  "ZA", "ZM", "ZW",
] as const
const publisherPlatformOptions = ["facebook", "instagram", "audience_network", "messenger"]
const fbPositionOptions = ["feed", "right_hand_column", "instant_article", "marketplace", "video_feeds", "story", "search", "instream_video"]
const igPositionOptions = ["stream", "story", "explore", "reels"]

const regionDisplayNames = typeof Intl !== "undefined" && typeof Intl.DisplayNames !== "undefined"
  ? new Intl.DisplayNames(["en"], { type: "region" })
  : null

const resolvedCountryCodes = [...fallbackCountryCodes]

const countryOptions = [...resolvedCountryCodes]
  .map((code) => {
    const name = regionDisplayNames?.of(code) ?? code
    const label = name && name !== code ? `${name} (${code})` : code
    return {
      code,
      label,
      searchValue: `${name} ${code}`,
    }
  })
  .sort((a, b) => a.label.localeCompare(b.label))

const countryLabelMap = Object.fromEntries(countryOptions.map((country) => [country.code, country.label])) as Record<string, string>

function getCountryLabel(countryCode: string) {
  return countryLabelMap[countryCode.toUpperCase()] ?? countryCode.toUpperCase()
}

type TransparencyCategoryKey = "SG" | "TW" | "OTHER"
type RegulatedCountryKey = "SG" | "TW" | "AU" | "IN" | "TH" | "BR"
type RegulationIdentityField = keyof MetaRegionalRegulationIdentitiesDto

const euCountryCodes = new Set([
  "AT", "BE", "BG", "HR", "CY", "CZ", "DK", "EE", "FI", "FR", "DE", "GR", "HU", "IE", "IT", "LV", "LT", "LU", "MT", "NL", "PL", "PT", "RO", "SK", "SI", "ES", "SE",
])

const transparencyCategories: Array<{
  key: TransparencyCategoryKey
  label: string
  category: string
  beneficiaryField: RegulationIdentityField
  payerField: RegulationIdentityField
}> = [
  { key: "SG", label: "Singapore", category: "SINGAPORE_UNIVERSAL", beneficiaryField: "singaporeUniversalBeneficiary", payerField: "singaporeUniversalPayer" },
  { key: "TW", label: "Taiwan", category: "TAIWAN_UNIVERSAL", beneficiaryField: "taiwanUniversalBeneficiary", payerField: "taiwanUniversalPayer" },
  { key: "OTHER", label: "Other selected locations", category: "AUSTRALIA_FINSERV + INDIA_FINSERV + THAILAND_UNIVERSAL + BRAZIL_REGULATION", beneficiaryField: "universalBeneficiary", payerField: "universalPayer" },
]

// "Other selected locations" gộp 2 nhóm:
// - UNIVERSAL (TH, BR): bắt buộc theo quốc gia, luôn tính.
// - FINSERV (AU, IN): chỉ tính khi người dùng tick "includes financial products".
const otherUniversalCountryCodes = new Set<RegulatedCountryKey>(["TH", "BR"])
const otherFinservCountryCodes = new Set<RegulatedCountryKey>(["AU", "IN"])

function getOtherRegulatedCountryCodes(includesFinancialProducts: boolean): RegulatedCountryKey[] {
  return includesFinancialProducts
    ? [...otherUniversalCountryCodes, ...otherFinservCountryCodes]
    : [...otherUniversalCountryCodes]
}

// Có nước FINSERV (AU/IN) trong target không — dùng để quyết định hiển thị checkbox tài chính.
function hasFinservTargetCountry(form: RequestFormState, countryGroups: GeoCountryGroupDto[]): boolean {
  const excluded = new Set(normalizeCountryCodes(form.excludedCountries))
  if (form.geoMode === "GLOBAL") {
    return [...otherFinservCountryCodes].some((country) => !excluded.has(country))
  }
  if (form.geoMode === "REGION") {
    return form.regionKeys.length > 0
  }

  const countryCodes = (() => {
    if (form.geoMode === "COUNTRY") return normalizeCountryCodes(form.countries)
    if (form.geoMode === "COUNTRY_GROUP") {
      const selected = new Set(form.countryGroupIds)
      return countryGroups.filter((group) => selected.has(group.id)).flatMap((group) => normalizeCountryCodes(group.countryCodes))
    }
    if (form.geoMode === "CITY") return normalizeCountryCodes(form.cityTargets.map((city) => city.countryCode ?? ""))
    return []
  })()

  const targeted = new Set(countryCodes.filter((country) => !excluded.has(country)))
  return [...otherFinservCountryCodes].some((country) => targeted.has(country))
}

function normalizeCountryCodes(values?: string[] | null) {
  return (values ?? [])
    .map((value) => value.trim().toUpperCase())
    .filter((value) => value.length === 2)
}

function getAdTransparencyCategories(form: RequestFormState, countryGroups: GeoCountryGroupDto[]): typeof transparencyCategories {
  const excluded = new Set(normalizeCountryCodes(form.excludedCountries))
  const otherCountries = getOtherRegulatedCountryCodes(form.includesFinancialProducts)
  if (form.geoMode === "GLOBAL") {
    return transparencyCategories.filter((category) => {
      if (category.key === "OTHER") return otherCountries.some((country) => !excluded.has(country))
      return !excluded.has(category.key)
    })
  }

  if (form.geoMode === "REGION") {
    return form.regionKeys.length > 0 ? transparencyCategories : []
  }

  const countryCodes = (() => {
    if (form.geoMode === "COUNTRY") return normalizeCountryCodes(form.countries)
    if (form.geoMode === "COUNTRY_GROUP") {
      const selected = new Set(form.countryGroupIds)
      return countryGroups.filter((group) => selected.has(group.id)).flatMap((group) => normalizeCountryCodes(group.countryCodes))
    }
    if (form.geoMode === "CITY") return normalizeCountryCodes(form.cityTargets.map((city) => city.countryCode ?? ""))
    return []
  })()

  const targeted = new Set(countryCodes.filter((country) => !excluded.has(country)))
  return transparencyCategories.filter((category) => {
    if (category.key === "OTHER") return otherCountries.some((country) => targeted.has(country))
    return targeted.has(category.key)
  })
}

function getRequiredAdTransparencyCategoryKeys(form: RequestFormState): Set<TransparencyCategoryKey> {
  if (form.geoMode !== "COUNTRY") return new Set()

  const excluded = new Set(normalizeCountryCodes(form.excludedCountries))
  const targeted = new Set(normalizeCountryCodes(form.countries).filter((country) => !excluded.has(country)))
  const otherCountries = getOtherRegulatedCountryCodes(form.includesFinancialProducts)
  const required = new Set<TransparencyCategoryKey>()
  if (targeted.has("SG")) required.add("SG")
  if (targeted.has("TW")) required.add("TW")
  if (otherCountries.some((country) => targeted.has(country))) required.add("OTHER")
  return required
}

function targetsEuDsa(form: RequestFormState, countryGroups: GeoCountryGroupDto[]): boolean {
  const excluded = new Set(normalizeCountryCodes(form.excludedCountries))
  if (form.geoMode === "GLOBAL") {
    return [...euCountryCodes].some((country) => !excluded.has(country))
  }
  if (form.geoMode === "REGION") {
    return form.regionKeys.length > 0
  }

  const countryCodes = (() => {
    if (form.geoMode === "COUNTRY") return normalizeCountryCodes(form.countries)
    if (form.geoMode === "COUNTRY_GROUP") {
      const selected = new Set(form.countryGroupIds)
      return countryGroups.filter((group) => selected.has(group.id)).flatMap((group) => normalizeCountryCodes(group.countryCodes))
    }
    if (form.geoMode === "CITY") return normalizeCountryCodes(form.cityTargets.map((city) => city.countryCode ?? ""))
    return []
  })()

  return countryCodes.some((country) => euCountryCodes.has(country) && !excluded.has(country))
}

interface Props {
  form: RequestFormState
  onChange: (patch: Partial<RequestFormState>) => void
  regions: MetaGeoRegionDto[]
  regionsLoading?: boolean
  regionsMessage?: string | null
  countryGroups: GeoCountryGroupDto[]
  countryGroupsLoading?: boolean
  countryGroupsMessage?: string | null
  onCountryGroupsChanged: () => void
  metaAdAccountId?: number | null
  executionIntegrationId?: number | null
  appPlatform?: string | null
}

export function AdSetAudienceSection({
  form,
  onChange,
  regions,
  regionsLoading = false,
  regionsMessage,
  countryGroups,
  countryGroupsLoading = false,
  countryGroupsMessage,
  onCountryGroupsChanged,
  metaAdAccountId,
  executionIntegrationId,
  appPlatform,
}: Props) {
  const [countryPopoverOpen, setCountryPopoverOpen] = useState(false)
  const [excludeCountryPopoverOpen, setExcludeCountryPopoverOpen] = useState(false)
  const [cityQuery, setCityQuery] = useState("")
  const [cityResults, setCityResults] = useState<MetaGeoCityReferenceDto[]>([])
  const [cityLoading, setCityLoading] = useState(false)
  const [cityError, setCityError] = useState<string | null>(null)
  const [languagePopoverOpen, setLanguagePopoverOpen] = useState(false)
  const [languageQuery, setLanguageQuery] = useState("")
  const [languageResults, setLanguageResults] = useState<MetaAdLocaleReferenceDto[]>([])
  const [languageLoading, setLanguageLoading] = useState(false)
  const [languageError, setLanguageError] = useState<string | null>(null)
  const [languageLabels, setLanguageLabels] = useState<Record<number, string>>({})
  const [regulationIdentities, setRegulationIdentities] = useState<MetaRegulationIdentityDto[]>([])
  const [regulationIdentityLoading, setRegulationIdentityLoading] = useState(false)
  const [regulationIdentityError, setRegulationIdentityError] = useState<string | null>(null)

  const generatedAdSetName = buildAdSetName(form)
  const isSkanCampaign = form.isSkadnetworkAttribution === true
  const adTransparencyCategories = getAdTransparencyCategories(form, countryGroups)
  const requiredAdTransparencyCategoryKeys = getRequiredAdTransparencyCategoryKeys(form)
  const showFinancialProductsToggle = hasFinservTargetCountry(form, countryGroups)
  const isEuDsaRequired = targetsEuDsa(form, countryGroups)
  const { isAutoEnabled: isAutoNameEnabled, setIsAutoEnabled, applyGeneratedName, markManual } = useAutoGeneratedNameField(
    form.adSetName,
    generatedAdSetName,
    (value) => onChange({ adSetName: value })
  )

  useEffect(() => {
    if (form.geoMode !== "CITY") {
      setCityResults([])
      setCityError(null)
      setCityLoading(false)
      return
    }

    if (!metaAdAccountId) {
      setCityResults([])
      setCityError("Select a Meta ad account before searching cities.")
      setCityLoading(false)
      return
    }

    const query = cityQuery.trim()
    if (query.length < 2) {
      setCityResults([])
      setCityError(null)
      setCityLoading(false)
      return
    }

    const handle = window.setTimeout(async () => {
      try {
        setCityLoading(true)
        setCityError(null)
        const results = await metaReferenceApi.searchGeoCities(metaAdAccountId, query)
        setCityResults(results)
      } catch (error) {
        const message = error instanceof Error ? error.message : "Failed to search cities."
        setCityResults([])
        setCityError(message)
      } finally {
        setCityLoading(false)
      }
    }, 300)

    return () => window.clearTimeout(handle)
  }, [cityQuery, form.geoMode, metaAdAccountId])

  useEffect(() => {
    if (!languagePopoverOpen) return

    if (!metaAdAccountId) {
      setLanguageResults([])
      setLanguageError("Select a Meta ad account before searching languages.")
      setLanguageLoading(false)
      return
    }

    const query = languageQuery.trim()
    if (query.length === 1) {
      setLanguageResults([])
      setLanguageError(null)
      setLanguageLoading(false)
      return
    }

    const handle = window.setTimeout(async () => {
      try {
        setLanguageLoading(true)
        setLanguageError(null)
        const results = await metaReferenceApi.searchLanguages(metaAdAccountId, query)
        setLanguageResults(results)
        setLanguageLabels((current) => {
          const next = { ...current }
          for (const locale of results) {
            next[locale.key] = locale.name
          }
          return next
        })
      } catch (error) {
        const message = error instanceof Error ? error.message : "Failed to search languages."
        setLanguageResults([])
        setLanguageError(message)
      } finally {
        setLanguageLoading(false)
      }
    }, 250)

    return () => window.clearTimeout(handle)
  }, [languagePopoverOpen, languageQuery, metaAdAccountId])

  useEffect(() => {
    if (!metaAdAccountId || adTransparencyCategories.length === 0) {
      setRegulationIdentities([])
      setRegulationIdentityError(null)
      setRegulationIdentityLoading(false)
      return
    }

    let cancelled = false
    setRegulationIdentityLoading(true)
    setRegulationIdentityError(null)
    metaReferenceApi.getRegulationIdentities(metaAdAccountId, executionIntegrationId)
      .then((items) => {
        if (!cancelled) setRegulationIdentities(items)
      })
      .catch((error) => {
        if (!cancelled) {
          setRegulationIdentities([])
          setRegulationIdentityError(error instanceof Error ? error.message : "Unable to load verified identities.")
        }
      })
      .finally(() => {
        if (!cancelled) setRegulationIdentityLoading(false)
      })

    return () => {
      cancelled = true
    }
  }, [metaAdAccountId, executionIntegrationId, adTransparencyCategories.length])

  const handleNameInputChange = (value: string) => {
    markManual()
    onChange({ adSetName: value })
  }

  const setGeoMode = (geoMode: RequestFormState["geoMode"]) => {
    const nextCountries = geoMode === "COUNTRY" ? form.countries : []
    const nextCityTargets = geoMode === "CITY" ? form.cityTargets : []

    // Filter excluded countries to avoid conflicts
    let nextExcluded = form.excludedCountries || []
    if (geoMode === "COUNTRY") {
      nextExcluded = nextExcluded.filter((c) => !nextCountries.includes(c))
    } else if (geoMode === "CITY") {
      nextExcluded = nextExcluded.filter((c) => !nextCityTargets.some((city) => city.countryCode?.toUpperCase() === c))
    }

    onChange({
      geoMode,
      countries: nextCountries,
      regionKeys: geoMode === "REGION" ? form.regionKeys : [],
      countryGroupIds: geoMode === "COUNTRY_GROUP" ? form.countryGroupIds : [],
      cityTargets: nextCityTargets,
      excludedCountries: nextExcluded,
    })
    setCountryPopoverOpen(false)
    setExcludeCountryPopoverOpen(false)
    setCityQuery("")
    setCityResults([])
    setCityError(null)
  }

  const toggleCountry = (countryCode: string) => {
    const country = countryCode.toUpperCase()
    const isExcluded = form.excludedCountries?.includes(country)
    if (isExcluded) return

    onChange({
      countries: form.countries.includes(country)
        ? form.countries.filter((value) => value !== country)
        : [...form.countries, country],
    })
  }

  const toggleExcludedCountry = (countryCode: string) => {
    const country = countryCode.toUpperCase()
    const isIncluded = form.geoMode === "COUNTRY" && form.countries.includes(country)
    const isCityConflict = form.geoMode === "CITY" && form.cityTargets.some((city) => city.countryCode?.toUpperCase() === country)
    if (isIncluded || isCityConflict) return

    onChange({
      excludedCountries: form.excludedCountries.includes(country)
        ? form.excludedCountries.filter((value) => value !== country)
        : [...form.excludedCountries, country],
    })
  }

  const toggleRegion = (regionKey: string) => {
    const normalized = regionKey.trim().toUpperCase()
    onChange({
      regionKeys: form.regionKeys.includes(normalized)
        ? form.regionKeys.filter((value) => value !== normalized)
        : [...form.regionKeys, normalized],
    })
  }

  const addCity = (city: MetaGeoCityReferenceDto) => {
    if (form.cityTargets.some((item) => item.key === city.key)) return
    if (city.countryCode && form.excludedCountries?.includes(city.countryCode.toUpperCase())) return
    onChange({ cityTargets: [...form.cityTargets, city] })
    setCityQuery("")
    setCityResults([])
  }

  const removeCity = (cityKey: string) => {
    onChange({ cityTargets: form.cityTargets.filter((city) => city.key !== cityKey) })
  }

  const getLanguageLabel = (key: number) => languageLabels[key] ?? `Locale ${key}`

  const toggleLanguage = (locale: MetaAdLocaleReferenceDto) => {
    setLanguageLabels((current) => ({ ...current, [locale.key]: locale.name }))
    const currentKeys = form.localeKeys ?? []
    onChange({
      localeKeys: currentKeys.includes(locale.key)
        ? currentKeys.filter((value) => value !== locale.key)
        : [...currentKeys, locale.key],
    })
  }

  const removeLanguage = (key: number) => {
    onChange({ localeKeys: (form.localeKeys ?? []).filter((value) => value !== key) })
  }

  const updateRegulationIdentity = (field: RegulationIdentityField, value: string | null) => {
    const nextIdentities: MetaRegionalRegulationIdentitiesDto = { ...(form.regionalRegulationIdentities ?? {}) }
    nextIdentities[field] = value
    onChange({
      regionalRegulationIdentities: nextIdentities,
    })
  }

  const getIdentityLabel = (identityId?: string | null) => {
    const normalized = identityId?.trim()
    if (!normalized) return ""
    const found = regulationIdentities.find((identity) => identity.id === normalized)
    return found ? `${found.name} (${found.id})${found.verificationStatus ? ` - ${found.verificationStatus}` : ""}` : normalized
  }

  const getIdentityOptionLabel = (identity: MetaRegulationIdentityDto) => {
    return `${identity.name} (${identity.id})${identity.verificationStatus ? ` - ${identity.verificationStatus}` : ""}`
  }

  const togglePlatform = (platform: string) => {
    onChange({
      publisherPlatforms: form.publisherPlatforms.includes(platform)
        ? form.publisherPlatforms.filter((value) => value !== platform)
        : [...form.publisherPlatforms, platform],
    })
  }

  const toggleFbPos = (position: string) => {
    onChange({
      facebookPositions: form.facebookPositions.includes(position)
        ? form.facebookPositions.filter((value) => value !== position)
        : [...form.facebookPositions, position],
    })
  }

  const toggleIgPos = (position: string) => {
    onChange({
      instagramPositions: form.instagramPositions.includes(position)
        ? form.instagramPositions.filter((value) => value !== position)
        : [...form.instagramPositions, position],
    })
  }

  const geoModeDescription = (() => {
    switch (form.geoMode) {
      case "GLOBAL":
        return "Broad targeting. No explicit country or city list will be sent to Meta."
      case "REGION":
        return "Region keys are internal groupings and will be expanded into country codes at execution time."
      case "COUNTRY_GROUP":
        return "Reusable organization country groups will be expanded into country codes at execution time."
      case "CITY":
        return "Search city references from Meta and target only the selected locations."
      default:
        return "Select one or more country codes to build geo_locations.countries."
    }
  })()

  return (
    <Card className="border-slate-200">
      <CardHeader className="pb-3">
        <CardTitle className="text-sm font-semibold text-slate-900 flex items-center gap-2">
          <Users className="w-4 h-4 text-slate-500" />
          Ad Set - Audience &amp; Placement
        </CardTitle>
      </CardHeader>
      <CardContent className="space-y-4">
        <div className="space-y-1.5">
          <div className="flex items-center justify-between gap-3">
            <Label className="text-xs font-medium text-slate-700">Ad Set Name <span className="text-red-500">*</span></Label>
            <div className="flex items-center gap-2 text-[11px] text-slate-600">
              <Wand2 className="w-3.5 h-3.5 text-slate-400" />
              <span>Auto-generate</span>
              <Switch checked={isAutoNameEnabled} onCheckedChange={(checked) => {
                setIsAutoEnabled(checked)
                if (checked) applyGeneratedName()
              }} />
            </div>
          </div>
          <Input
            placeholder="e.g. US_18-24_ALL_AUTO"
            className="h-9 text-sm"
            value={form.adSetName}
            onChange={(event) => handleNameInputChange(event.target.value)}
          />
          <div className="rounded-md border border-slate-200 bg-slate-50 px-3 py-2 space-y-1.5">
            <p className="text-[11px] text-slate-500">Pattern: <code className="rounded bg-white px-1 py-0.5">GEO_AGE_GENDER_PLACEMENT</code></p>
            <p className={`text-xs font-mono ${generatedAdSetName ? "text-slate-700" : "text-slate-400 italic"}`}>
              {generatedAdSetName || "Select a geo mode and target to generate an ad set name."}
            </p>
            {!isAutoNameEnabled && generatedAdSetName ? (
              <button
                type="button"
                onClick={applyGeneratedName}
                className="text-[11px] font-medium text-blue-600 hover:text-blue-700"
              >
                Use generated name
              </button>
            ) : null}
          </div>
        </div>

        {isSkanCampaign ? (
          <div className="rounded-lg border border-blue-200 bg-blue-50 px-3 py-3 text-sm text-blue-900 flex items-start gap-2">
            <AlertTriangle className="w-4 h-4 mt-0.5 flex-shrink-0 text-blue-600" />
            <div className="space-y-1">
              <p className="font-medium">iOS 14+ / SKAN targeting locked</p>
              <p className="text-[12px] text-blue-800">
                user_os sẽ gửi <code className="rounded bg-white/70 px-1 py-0.5 font-mono">iOS_ver_14.0_and_above</code> + user_device iPhone/iPad/iPod, app gắn ở cấp campaign. Giới hạn 9 campaign iOS 14+/ad account, tối đa 5 ad set/campaign.
              </p>
              {appPlatform ? <p className="text-[11px] text-blue-700">Selected app platform: {appPlatform}</p> : null}
            </div>
          </div>
        ) : null}

        <div className="space-y-2">
          <div className="flex items-center justify-between gap-3">
            <Label className="text-xs font-medium text-slate-700">Geo Mode <span className="text-red-500">*</span></Label>
            <span className="text-[11px] text-slate-400">One mode only</span>
          </div>
          <div className="flex flex-wrap overflow-hidden rounded-md border border-slate-300 w-fit">
            {(["GLOBAL", "COUNTRY", "REGION", "COUNTRY_GROUP", "CITY"] as const).map((mode) => (
              <button
                key={mode}
                type="button"
                onClick={() => setGeoMode(mode)}
                className={`px-3 py-1.5 text-xs font-medium transition-colors ${form.geoMode === mode ? "bg-blue-600 text-white" : "bg-white text-slate-600 hover:bg-slate-50"} ${mode !== "GLOBAL" ? "border-l border-slate-300" : ""}`}
              >
                {mode === "COUNTRY_GROUP" ? "Country Group" : mode.charAt(0) + mode.slice(1).toLowerCase()}
              </button>
            ))}
          </div>
          <div className="rounded-md border border-slate-200 bg-slate-50 px-3 py-2 text-[11px] text-slate-500">
            {geoModeDescription}
          </div>
        </div>

        {form.geoMode === "GLOBAL" ? (
          <div className="rounded-lg border border-blue-200 bg-blue-50 px-3 py-3 text-sm text-blue-900 flex items-start gap-2">
            <Globe2 className="w-4 h-4 mt-0.5 flex-shrink-0" />
            <div>
              <p className="font-medium">Global targeting</p>
              <p className="text-[12px] text-blue-800 mt-0.5">This request will not send country or city lists to Meta. App platform, age, gender, and placements still apply.</p>
            </div>
          </div>
        ) : null}

        {form.geoMode === "COUNTRY" ? (
          <div className="space-y-2">
            <Label className="text-xs font-medium text-slate-700">Countries <span className="text-red-500">*</span></Label>
            <Popover open={countryPopoverOpen} onOpenChange={setCountryPopoverOpen}>
              <PopoverTrigger asChild>
                <Button
                  type="button"
                  variant="outline"
                  role="combobox"
                  aria-expanded={countryPopoverOpen}
                  className="h-9 w-full justify-between bg-white px-3 text-left font-normal"
                >
                  <span className="min-w-0 flex-1 truncate text-left text-sm text-slate-700">
                    {form.countries.length === 0
                      ? "Select countries"
                      : form.countries.length <= 2
                        ? form.countries.map((country) => getCountryLabel(country)).join(", ")
                        : `${form.countries.length} countries selected`}
                  </span>
                  <ChevronsUpDown className="ml-2 h-4 w-4 shrink-0 opacity-50" />
                </Button>
              </PopoverTrigger>
              <PopoverContent className="w-[--radix-popover-trigger-width] min-w-[360px] p-0" align="start">
                <Command>
                  <CommandInput placeholder="Search countries by name or code..." />
                  <CommandList>
                    <CommandEmpty>No country found.</CommandEmpty>
                    <CommandGroup heading="Countries">
                      {countryOptions.map((country) => {
                        const isSelected = form.countries.includes(country.code)
                        const isExcluded = form.excludedCountries?.includes(country.code) ?? false
                        return (
                          <CommandItem
                            key={country.code}
                            value={country.searchValue}
                            onSelect={() => !isExcluded && toggleCountry(country.code)}
                            className={cn(isExcluded && "opacity-50 pointer-events-none")}
                          >
                            <Check className={cn("mr-2 h-4 w-4 shrink-0", isSelected ? "opacity-100" : "opacity-0")} />
                            <span className="min-w-0 flex-1 truncate">{country.label}</span>
                            {isExcluded && <span className="text-[10px] text-red-500 font-medium ml-2">Excluded</span>}
                          </CommandItem>
                        )
                      })}
                    </CommandGroup>
                  </CommandList>
                </Command>
              </PopoverContent>
            </Popover>
            <p className="text-[11px] text-slate-500">Select one or more countries. Search by country name or ISO code.</p>
            {form.countries.length > 0 ? (
              <div className="flex flex-wrap gap-1.5">
                {[...form.countries]
                  .sort((left, right) => getCountryLabel(left).localeCompare(getCountryLabel(right)))
                  .map((country) => (
                    <Badge key={country} className="bg-blue-100 text-blue-800 gap-1 pr-1 text-xs max-w-full">
                      <span className="truncate">{getCountryLabel(country)}</span>
                      <button type="button" onClick={() => toggleCountry(country)}>
                        <X className="w-3 h-3" />
                      </button>
                    </Badge>
                  ))}
              </div>
            ) : null}
          </div>
        ) : null}

        {form.geoMode === "REGION" ? (
          <div className="space-y-1.5">
            <Label className="text-xs font-medium text-slate-700">Regions <span className="text-red-500">*</span></Label>
            {regionsLoading ? <p className="text-xs text-slate-500 flex items-center gap-1"><Loader2 className="w-3.5 h-3.5 animate-spin" /> Loading region references...</p> : null}
            {regionsMessage ? <p className="text-xs text-red-600">{regionsMessage}</p> : null}
            {!regionsLoading && !regionsMessage ? (
              <div className="flex flex-wrap gap-1.5">
                {regions.map((region) => (
                  <button
                    key={region.key}
                    type="button"
                    onClick={() => toggleRegion(region.key)}
                    className={`px-2.5 py-1 rounded text-[11px] font-medium border transition-colors ${
                      form.regionKeys.includes(region.key)
                        ? "bg-blue-600 text-white border-blue-600"
                        : "bg-white text-slate-600 border-slate-300 hover:border-blue-300"
                    }`}
                    title={`${region.countryCount} countries`}
                  >
                    {region.label} <span className={`ml-1 ${form.regionKeys.includes(region.key) ? "text-blue-100" : "text-slate-400"}`}>({region.countryCount})</span>
                  </button>
                ))}
              </div>
            ) : null}
            {form.regionKeys.length > 0 ? (
              <div className="flex flex-wrap gap-1.5">
                {form.regionKeys.map((regionKey) => (
                  <Badge key={regionKey} className="bg-blue-100 text-blue-800 gap-1 pr-1 text-xs">
                    {regions.find((region) => region.key === regionKey)?.label ?? regionKey}
                    <button type="button" onClick={() => toggleRegion(regionKey)}>
                      <X className="w-3 h-3" />
                    </button>
                  </Badge>
                ))}
              </div>
            ) : null}
          </div>
        ) : null}

        {form.geoMode === "COUNTRY_GROUP" ? (
          <GeoCountryGroupManager
            groups={countryGroups}
            loading={countryGroupsLoading}
            message={countryGroupsMessage}
            selectedGroupIds={form.countryGroupIds}
            onSelectedGroupIdsChange={(countryGroupIds) => onChange({ countryGroupIds })}
            onGroupsChanged={onCountryGroupsChanged}
            emptyMessage="No country groups yet. Create one below to reuse it across Meta requests."
            selectionDisabled={!metaAdAccountId}
            selectionDisabledMessage="Select a Meta ad account before choosing country groups."
          />
        ) : null}

        {form.geoMode === "CITY" ? (
          <div className="space-y-3">
            <div className="space-y-1.5">
              <Label className="text-xs font-medium text-slate-700">Cities <span className="text-red-500">*</span></Label>
              <Input
                placeholder={metaAdAccountId ? "Search city name..." : "Select a Meta ad account first"}
                className="h-9 text-sm"
                value={cityQuery}
                disabled={!metaAdAccountId}
                onChange={(event) => setCityQuery(event.target.value)}
              />
              {cityLoading ? <p className="text-xs text-slate-500 flex items-center gap-1"><Loader2 className="w-3.5 h-3.5 animate-spin" /> Searching Meta cities...</p> : null}
              {cityError ? <p className="text-xs text-red-600">{cityError}</p> : null}
            </div>
            {cityResults.length > 0 ? (
              <div className="rounded-lg border border-slate-200 bg-white max-h-56 overflow-auto divide-y divide-slate-100">
                {cityResults.map((city) => {
                  const isExcluded = !!(city.countryCode && form.excludedCountries?.includes(city.countryCode.toUpperCase()))
                  return (
                    <button
                      key={city.key}
                      type="button"
                      disabled={isExcluded}
                      onClick={() => addCity(city)}
                      className={cn(
                        "w-full text-left px-3 py-2 hover:bg-slate-50 transition-colors",
                        isExcluded && "opacity-50 cursor-not-allowed"
                      )}
                    >
                      <div className="flex items-start justify-between gap-3">
                        <div className="min-w-0">
                          <p className="text-sm font-medium text-slate-800 truncate">{city.name}</p>
                          <p className="text-[11px] text-slate-500 truncate">
                            {[city.region, city.countryName, city.countryCode].filter(Boolean).join(" - ")}
                            {isExcluded && " (Country Excluded)"}
                          </p>
                        </div>
                        <span className="text-[10px] font-mono text-slate-400">{city.key}</span>
                      </div>
                    </button>
                  )
                })}
              </div>
            ) : null}
            {form.cityTargets.length > 0 ? (
              <div className="flex flex-wrap gap-1.5">
                {form.cityTargets.map((city) => (
                  <Badge key={city.key} className="bg-blue-100 text-blue-800 gap-1 pr-1 text-xs max-w-full">
                    <MapPin className="w-3 h-3" />
                    <span className="truncate">{city.name}{city.countryCode ? ` (${city.countryCode})` : ""}</span>
                    <button type="button" onClick={() => removeCity(city.key)}>
                      <X className="w-3 h-3" />
                    </button>
                  </Badge>
                ))}
              </div>
            ) : null}
          </div>
        ) : null}

        {isEuDsaRequired ? (
          <div className="space-y-3 pt-2 border-t border-slate-100">
            <div>
              <Label className="text-xs font-medium text-slate-700">EU advertiser and payer details <span className="text-red-500">*</span></Label>
              <p className="text-[11px] text-slate-500 mt-1">
                Enter the advertiser name for EU DSA transparency. This is free text and is sent as dsa_beneficiary/dsa_payor.
              </p>
            </div>
            <div className="rounded-lg border border-slate-200 bg-white p-3 space-y-3">
              <div className="space-y-1.5">
                <Label className="text-[11px] font-medium text-slate-700">Advertiser / Beneficiary <span className="text-red-500">*</span></Label>
                <Input
                  placeholder="e.g. Amobear"
                  className="h-9 text-sm"
                  value={form.dsaBeneficiary ?? ""}
                  onChange={(event) => onChange({ dsaBeneficiary: event.target.value })}
                />
              </div>
              <div className="flex items-center justify-between gap-3 rounded-md bg-slate-50 border border-slate-200 px-2.5 py-2">
                <span className="text-[11px] text-slate-600">The advertiser and payer are different</span>
                <Switch
                  checked={form.dsaPayor != null && form.dsaPayor !== ""}
                  onCheckedChange={(checked) => onChange({ dsaPayor: checked ? (form.dsaPayor || form.dsaBeneficiary || "") : "" })}
                />
              </div>
              {form.dsaPayor ? (
                <div className="space-y-1.5">
                  <Label className="text-[11px] font-medium text-slate-700">Payer</Label>
                  <Input
                    placeholder="e.g. Amobear"
                    className="h-9 text-sm"
                    value={form.dsaPayor ?? ""}
                    onChange={(event) => onChange({ dsaPayor: event.target.value })}
                  />
                </div>
              ) : null}
            </div>
          </div>
        ) : null}

        {showFinancialProductsToggle ? (
          <div className="space-y-2 pt-2 border-t border-slate-100">
            <div className="flex items-start gap-2.5 rounded-lg border border-slate-200 bg-white p-3">
              <Checkbox
                id="includes-financial-products"
                checked={form.includesFinancialProducts}
                onCheckedChange={(checked) => onChange({ includesFinancialProducts: checked === true })}
                className="mt-0.5"
              />
              <div className="space-y-1">
                <Label htmlFor="includes-financial-products" className="text-xs font-medium text-slate-800 cursor-pointer">
                  This ad set includes ads related to financial products and services
                </Label>
                <p className="text-[11px] text-slate-500">
                  Only tick this when the ads are genuinely about financial products/services. Targeting Australia or India will declare the FINSERV regulated category and require a verified advertiser &amp; payer per location. Leave unticked for non-financial apps (e.g. games).
                </p>
                {form.includesFinancialProducts ? (
                  <p className="text-[11px] text-amber-700 bg-amber-50 border border-amber-200 rounded-md px-2.5 py-1.5 flex items-start gap-1.5">
                    <AlertTriangle className="h-3.5 w-3.5 mt-0.5 shrink-0" />
                    <span>Meta may require an additional verification task for these locations before the ads can deliver.</span>
                  </p>
                ) : null}
              </div>
            </div>
          </div>
        ) : null}

        {adTransparencyCategories.length > 0 ? (
          <div className="space-y-3 pt-2 border-t border-slate-100">
            <div className="flex items-start justify-between gap-3">
              <div>
                <Label className="text-xs font-medium text-slate-700">Regional ad transparency <span className="text-red-500">*</span></Label>
                <p className="text-[11px] text-slate-500 mt-1">
                  Select the verified Business Manager advertiser for regulated locations. Value sent to Meta is the BM ID.
                </p>
              </div>
              {regulationIdentityLoading ? (
                <span className="text-[11px] text-slate-500 flex items-center gap-1"><Loader2 className="h-3.5 w-3.5 animate-spin" /> Loading identities</span>
              ) : null}
            </div>
            {regulationIdentityError ? (
              <p className="text-[11px] text-amber-700 bg-amber-50 border border-amber-200 rounded-md px-2.5 py-2">
                Business suggestions are unavailable. Seed fallback should still provide known AMOBEAR business identities.
              </p>
            ) : null}
            {!regulationIdentityLoading && !regulationIdentityError && regulationIdentities.length === 0 ? (
              <p className="text-[11px] text-slate-500 bg-slate-50 border border-slate-200 rounded-md px-2.5 py-2">
                No Business identities were returned for this account.
              </p>
            ) : null}
            <div className="grid gap-3 md:grid-cols-2">
              {adTransparencyCategories.map((category) => {
                const identities = form.regionalRegulationIdentities ?? {}
                const beneficiaryValue = identities[category.beneficiaryField] ?? ""
                const payerValue = identities[category.payerField]
                const payerDifferent = payerValue != null
                const isRequired = requiredAdTransparencyCategoryKeys.has(category.key)
                return (
                  <div key={category.key} className="rounded-lg border border-slate-200 bg-white p-3 space-y-3">
                    <div className="flex items-center justify-between gap-2">
                      <div>
                        <p className="text-xs font-semibold text-slate-800">{category.label}</p>
                        <p className="text-[10px] font-mono text-slate-400">{category.category}</p>
                      </div>
                      <Badge className={isRequired ? "bg-red-50 text-red-700 border-red-200" : "bg-slate-100 text-slate-600 border-slate-200"}>{isRequired ? "Required" : "Optional"}</Badge>
                    </div>
                    <div className="space-y-1.5">
                      <Label className="text-[11px] font-medium text-slate-700">Advertiser / Beneficiary {isRequired ? <span className="text-red-500">*</span> : null}</Label>
                      <select
                        className="h-9 w-full rounded-md border border-slate-300 bg-white px-3 text-sm text-slate-700 disabled:opacity-60"
                        value={beneficiaryValue ?? ""}
                        disabled={regulationIdentities.length === 0}
                        onChange={(event) => updateRegulationIdentity(category.beneficiaryField, event.target.value || null)}
                      >
                        <option value="">Select Business</option>
                        {regulationIdentities.map((identity) => (
                          <option key={identity.id} value={identity.id}>{getIdentityOptionLabel(identity)}</option>
                        ))}
                      </select>
                      {beneficiaryValue ? <p className="text-[10px] text-slate-500 truncate">{getIdentityLabel(beneficiaryValue)}</p> : null}
                    </div>
                    <div className="flex items-center justify-between gap-3 rounded-md bg-slate-50 border border-slate-200 px-2.5 py-2">
                      <span className="text-[11px] text-slate-600">The advertiser and payer are different</span>
                      <Switch
                        checked={payerDifferent}
                        onCheckedChange={(checked) => updateRegulationIdentity(category.payerField, checked ? (payerValue ?? beneficiaryValue ?? "") : null)}
                      />
                    </div>
                    {payerDifferent ? (
                      <div className="space-y-1.5">
                        <Label className="text-[11px] font-medium text-slate-700">Payer</Label>
                        <select
                          className="h-9 w-full rounded-md border border-slate-300 bg-white px-3 text-sm text-slate-700 disabled:opacity-60"
                          value={payerValue ?? ""}
                          disabled={regulationIdentities.length === 0}
                          onChange={(event) => updateRegulationIdentity(category.payerField, event.target.value || null)}
                        >
                          <option value="">Select Business</option>
                          {regulationIdentities.map((identity) => (
                            <option key={identity.id} value={identity.id}>{getIdentityOptionLabel(identity)}</option>
                          ))}
                        </select>
                        {payerValue ? <p className="text-[10px] text-slate-500 truncate">{getIdentityLabel(payerValue)}</p> : null}
                      </div>
                    ) : null}
                  </div>
                )
              })}
            </div>
          </div>
        ) : null}

        {/* Exclude Countries Section */}
        <div className="space-y-2 pt-2 border-t border-slate-100">
          <div className="flex items-center justify-between gap-3">
            <Label className="text-xs font-medium text-slate-700">Exclude Countries</Label>
            <span className="text-[11px] text-slate-400">Optional</span>
          </div>
          <Popover open={excludeCountryPopoverOpen} onOpenChange={setExcludeCountryPopoverOpen}>
            <PopoverTrigger asChild>
              <Button
                type="button"
                variant="outline"
                role="combobox"
                aria-expanded={excludeCountryPopoverOpen}
                className="h-9 w-full justify-between bg-white px-3 text-left font-normal"
              >
                <span className="min-w-0 flex-1 truncate text-left text-sm text-slate-700">
                  {!form.excludedCountries || form.excludedCountries.length === 0
                    ? "Select countries to exclude"
                    : form.excludedCountries.length <= 2
                      ? form.excludedCountries.map((country) => getCountryLabel(country)).join(", ")
                      : `${form.excludedCountries.length} countries excluded`}
                </span>
                <ChevronsUpDown className="ml-2 h-4 w-4 shrink-0 opacity-50" />
              </Button>
            </PopoverTrigger>
            <PopoverContent className="w-[--radix-popover-trigger-width] min-w-[360px] p-0" align="start">
              <Command>
                <CommandInput placeholder="Search countries to exclude..." />
                <CommandList>
                  <CommandEmpty>No country found.</CommandEmpty>
                  <CommandGroup heading="Countries to Exclude">
                    {countryOptions.map((country) => {
                      const isSelected = form.excludedCountries?.includes(country.code) ?? false
                      const isIncluded = form.geoMode === "COUNTRY" && form.countries.includes(country.code)
                      const isCityConflict = form.geoMode === "CITY" && form.cityTargets.some(c => c.countryCode?.toUpperCase() === country.code)
                      const isDisabled = isIncluded || isCityConflict

                      return (
                        <CommandItem
                          key={country.code}
                          value={country.searchValue}
                          onSelect={() => !isDisabled && toggleExcludedCountry(country.code)}
                          className={cn(isDisabled && "opacity-50 pointer-events-none")}
                        >
                          <Check className={cn("mr-2 h-4 w-4 shrink-0", isSelected ? "opacity-100" : "opacity-0")} />
                          <span className="min-w-0 flex-1 truncate">{country.label}</span>
                          {isIncluded && <span className="text-[10px] text-red-500 font-medium ml-2">Currently Included</span>}
                          {isCityConflict && <span className="text-[10px] text-red-500 font-medium ml-2">City Target Conflict</span>}
                        </CommandItem>
                      )
                    })}
                  </CommandGroup>
                </CommandList>
              </Command>
            </PopoverContent>
          </Popover>
          <p className="text-[11px] text-slate-500">Exclude one or more countries from your geo targeting. Excluded countries cannot overlap with included locations.</p>
          {form.excludedCountries && form.excludedCountries.length > 0 ? (
            <div className="flex flex-wrap gap-1.5">
              {[...form.excludedCountries]
                .sort((left, right) => getCountryLabel(left).localeCompare(getCountryLabel(right)))
                .map((country) => (
                  <Badge key={country} className="bg-red-50 text-red-800 border-red-200 gap-1 pr-1 text-xs max-w-full">
                    <span className="truncate">{getCountryLabel(country)}</span>
                    <button type="button" onClick={() => toggleExcludedCountry(country)}>
                      <X className="w-3 h-3 text-red-500 hover:text-red-700" />
                    </button>
                  </Badge>
                ))}
            </div>
          ) : null}
        </div>

        <div className="space-y-2 pt-2 border-t border-slate-100">
          <div className="flex items-center justify-between gap-3">
            <Label className="text-xs font-medium text-slate-700">Target Languages</Label>
            <span className="text-[11px] text-slate-400">Optional</span>
          </div>
          <Popover open={languagePopoverOpen} onOpenChange={setLanguagePopoverOpen}>
            <PopoverTrigger asChild>
              <Button
                type="button"
                variant="outline"
                role="combobox"
                aria-expanded={languagePopoverOpen}
                disabled={!metaAdAccountId}
                className="h-9 w-full justify-between bg-white px-3 text-left font-normal disabled:opacity-60"
              >
                <span className="min-w-0 flex-1 truncate text-left text-sm text-slate-700">
                  {!metaAdAccountId
                    ? "Select a Meta ad account first"
                    : (form.localeKeys ?? []).length === 0
                      ? "All languages"
                      : (form.localeKeys ?? []).length <= 2
                        ? (form.localeKeys ?? []).map((key) => getLanguageLabel(key)).join(", ")
                        : `${(form.localeKeys ?? []).length} languages selected`}
                </span>
                <ChevronsUpDown className="ml-2 h-4 w-4 shrink-0 opacity-50" />
              </Button>
            </PopoverTrigger>
            <PopoverContent className="w-[--radix-popover-trigger-width] min-w-[360px] p-0" align="start">
              <Command shouldFilter={false}>
                <CommandInput
                  placeholder="Search languages, e.g. English..."
                  value={languageQuery}
                  onValueChange={setLanguageQuery}
                />
                <CommandList>
                  {languageLoading ? (
                    <div className="flex items-center gap-2 px-3 py-3 text-xs text-slate-500">
                      <Loader2 className="h-3.5 w-3.5 animate-spin" />
                      Searching Meta languages...
                    </div>
                  ) : null}
                  {languageError ? <p className="px-3 py-2 text-xs text-red-600">{languageError}</p> : null}
                  {!languageLoading && !languageError && languageResults.length === 0 ? (
                    <CommandEmpty>{languageQuery.trim().length === 1 ? "Type at least 2 characters." : "No language found."}</CommandEmpty>
                  ) : null}
                  {languageResults.length > 0 ? (
                    <CommandGroup heading="Languages">
                      {languageResults.map((locale) => {
                        const isSelected = (form.localeKeys ?? []).includes(locale.key)
                        return (
                          <CommandItem
                            key={locale.key}
                            value={`${locale.key} ${locale.name}`}
                            onSelect={() => toggleLanguage(locale)}
                          >
                            <Check className={cn("mr-2 h-4 w-4 shrink-0", isSelected ? "opacity-100" : "opacity-0")} />
                            <span className="min-w-0 flex-1 truncate">{locale.name}</span>
                            <span className="text-[10px] font-mono text-slate-400">{locale.key}</span>
                          </CommandItem>
                        )
                      })}
                    </CommandGroup>
                  ) : null}
                </CommandList>
              </Command>
            </PopoverContent>
          </Popover>
          <p className="text-[11px] text-slate-500">Leave empty to target all languages, which is Meta&apos;s default.</p>
          {(form.localeKeys ?? []).length > 0 ? (
            <div className="flex flex-wrap gap-1.5">
              {[...(form.localeKeys ?? [])]
                .sort((left, right) => getLanguageLabel(left).localeCompare(getLanguageLabel(right)))
                .map((key) => (
                  <Badge key={key} className="bg-violet-50 text-violet-800 border-violet-200 gap-1 pr-1 text-xs max-w-full">
                    <span className="truncate">{getLanguageLabel(key)}</span>
                    <span className="font-mono text-[10px] text-violet-500">{key}</span>
                    <button type="button" onClick={() => removeLanguage(key)}>
                      <X className="w-3 h-3 text-violet-500 hover:text-violet-700" />
                    </button>
                  </Badge>
                ))}
            </div>
          ) : null}
        </div>

        <div className="grid grid-cols-2 gap-4">
          <div className="space-y-1.5">
            <Label className="text-xs font-medium text-slate-700">Age Range</Label>
            <div className="flex items-center gap-2">
              <Input type="number" min={13} max={65} className="h-9 text-sm w-20" value={form.ageMin} onChange={(event) => onChange({ ageMin: Number(event.target.value) })} />
              <span className="text-slate-400 text-sm">-</span>
              <Input type="number" min={13} max={65} className="h-9 text-sm w-20" value={form.ageMax} onChange={(event) => onChange({ ageMax: Number(event.target.value) })} />
            </div>
          </div>

          <div className="space-y-1.5">
            <Label className="text-xs font-medium text-slate-700">Gender</Label>
            <div className="flex rounded-md overflow-hidden border border-slate-300 w-fit">
              {(["ALL", "MALE", "FEMALE"] as const).map((gender) => (
                <button
                  key={gender}
                  type="button"
                  onClick={() => onChange({ gender })}
                  className={`px-3 py-1.5 text-xs font-medium transition-colors ${
                    form.gender === gender ? "bg-blue-600 text-white" : "bg-white text-slate-600 hover:bg-slate-50"
                  } ${gender !== "ALL" ? "border-l border-slate-300" : ""}`}
                >
                  {gender === "ALL" ? "All" : gender.charAt(0) + gender.slice(1).toLowerCase()}
                </button>
              ))}
            </div>
          </div>
        </div>

        <div className="space-y-2">
          <Label className="text-xs font-medium text-slate-700">Placement Mode</Label>
          <div className="flex rounded-md overflow-hidden border border-slate-300 w-fit">
            {(["AUTOMATIC", "MANUAL"] as const).map((mode) => (
              <button
                key={mode}
                type="button"
                onClick={() => onChange({ placementMode: mode })}
                className={`px-4 py-1.5 text-xs font-medium transition-colors ${
                  form.placementMode === mode ? "bg-blue-600 text-white" : "bg-white text-slate-600 hover:bg-slate-50"
                } ${mode === "MANUAL" ? "border-l border-slate-300" : ""}`}
              >
                {mode.charAt(0) + mode.slice(1).toLowerCase()}
              </button>
            ))}
          </div>

          {form.placementMode === "MANUAL" ? (
            <div className="bg-slate-50 border border-slate-200 rounded-lg p-3 space-y-3">
              <p className="text-[11px] text-slate-500">Manual placement values must map cleanly to backend payload fields.</p>
              <div className="space-y-2">
                <p className="text-xs font-medium text-slate-700">Publisher Platforms</p>
                <div className="flex flex-wrap gap-3">
                  {publisherPlatformOptions.map((platform) => (
                    <label key={platform} className="flex items-center gap-1.5 text-xs text-slate-600 cursor-pointer">
                      <Checkbox checked={form.publisherPlatforms.includes(platform)} onCheckedChange={() => togglePlatform(platform)} />
                      {platform}
                    </label>
                  ))}
                </div>
              </div>
              <div className="space-y-2">
                <p className="text-xs font-medium text-slate-700">Facebook Positions</p>
                <div className="flex flex-wrap gap-3">
                  {fbPositionOptions.map((position) => (
                    <label key={position} className="flex items-center gap-1.5 text-xs text-slate-600 cursor-pointer">
                      <Checkbox checked={form.facebookPositions.includes(position)} onCheckedChange={() => toggleFbPos(position)} />
                      {position}
                    </label>
                  ))}
                </div>
              </div>
              <div className="space-y-2">
                <p className="text-xs font-medium text-slate-700">Instagram Positions</p>
                <div className="flex flex-wrap gap-3">
                  {igPositionOptions.map((position) => (
                    <label key={position} className="flex items-center gap-1.5 text-xs text-slate-600 cursor-pointer">
                      <Checkbox checked={form.instagramPositions.includes(position)} onCheckedChange={() => toggleIgPos(position)} />
                      {position}
                    </label>
                  ))}
                </div>
              </div>
            </div>
          ) : null}
        </div>

        <div className="space-y-1.5 opacity-50">
          <Label className="text-xs font-medium text-slate-700">Custom Audience <span className="text-[10px] bg-slate-200 text-slate-500 px-1.5 py-0.5 rounded font-normal ml-1">Coming soon</span></Label>
          <Input disabled placeholder="Custom audience selection" className="h-9 text-sm" />
        </div>
      </CardContent>
    </Card>
  )
}
