"use client"

import { useEffect, useRef, useState } from "react"
import type { TikTokAppMappingDto, TikTokTargetingOptionDto } from "@/types/tiktok-ads"
import type { TikTokRequestFormState } from "./types"

function normalizeToken(value: string) {
  return value
    .trim()
    .replace(/[^A-Za-z0-9]+/g, "_")
    .replace(/_+/g, "_")
    .replace(/^_+|_+$/g, "")
    .toUpperCase()
}

function buildDateToken() {
  const now = new Date()
  const year = now.getFullYear()
  const month = `${now.getMonth() + 1}`.padStart(2, "0")
  const day = `${now.getDate()}`.padStart(2, "0")
  return `${year}${month}${day}`
}

function buildAppToken(selectedAppMapping?: TikTokAppMappingDto | null, appRowId?: number | null) {
  const rawValue =
    selectedAppMapping?.appDisplayName?.trim()
    || selectedAppMapping?.appId?.trim()
    || (appRowId ? `App${appRowId}` : "")

  return rawValue ? normalizeToken(rawValue) : ""
}

function buildPlatformToken(selectedAppMapping?: TikTokAppMappingDto | null) {
  const normalized = selectedAppMapping?.appPlatform?.trim().toUpperCase()
  if (normalized === "ANDROID" || normalized === "IOS") return normalized
  return normalized ? normalizeToken(normalized) : "APP"
}

function buildObjectiveToken(objective: string) {
  const normalized = objective.trim().toUpperCase()
  if (!normalized) return ""
  if (normalized === "APP_PROMOTION") return "APPPROMO"
  return normalizeToken(normalized.replace(/^APP_/, "APP").replaceAll("_", ""))
}

function buildFormatToken(format: string) {
  switch (format) {
    case "SINGLE_IMAGE":
      return "IMG"
    case "CAROUSEL":
      return "CAROUSEL"
    default:
      return "VID"
  }
}

function buildLocationToken(locationIds: string[], locations?: TikTokTargetingOptionDto[]) {
  if (locationIds.length === 0) return ""
  const labels = locationIds.map((id) => {
    const option = locations?.find((item) => item.key === id)
    return option?.countryCode || option?.label || id
  })
  const tokens = Array.from(new Set(labels.map(normalizeToken).filter(Boolean)))
  if (tokens.length <= 3) return tokens.join("-")
  return `GEO${tokens.length}`
}

function buildAgeToken(ageGroups: string[]) {
  if (ageGroups.length === 0) return "ALLAGE"
  if (ageGroups.length > 3) return `AGE${ageGroups.length}`
  return ageGroups.map((item) => item.replace(/^AGE_/, "").replace("_", "-")).join("-")
}

function buildGenderToken(gender: string) {
  switch (gender) {
    case "GENDER_MALE":
      return "M"
    case "GENDER_FEMALE":
      return "F"
    default:
      return "ALL"
  }
}

function buildPlacementToken(form: TikTokRequestFormState) {
  if (form.adGroup.placementType === "PLACEMENT_TYPE_AUTOMATIC") return "AUTO"
  const tokens = form.adGroup.placements.map((placement) => normalizeToken(placement.replace(/^PLACEMENT_/, ""))).filter(Boolean)
  if (tokens.length === 0) return "MANUAL"
  if (tokens.length <= 3) return `MAN-${tokens.join("-")}`
  return `MAN${tokens.length}`
}

export function buildCampaignName(form: TikTokRequestFormState, selectedAppMapping?: TikTokAppMappingDto | null, locations?: TikTokTargetingOptionDto[]) {
  const appToken = buildAppToken(selectedAppMapping, form.appRowId)
  const geoToken = buildLocationToken(form.adGroup.locationIds, locations)
  const platformToken = buildPlatformToken(selectedAppMapping)
  const objectiveToken = buildObjectiveToken(form.campaign.objectiveType)
  if (!appToken || !geoToken || !objectiveToken) return ""
  return [appToken, geoToken, platformToken, objectiveToken, buildDateToken()].join("_")
}

export function buildAdGroupName(form: TikTokRequestFormState, locations?: TikTokTargetingOptionDto[]) {
  const geoToken = buildLocationToken(form.adGroup.locationIds, locations)
  if (!geoToken) return ""
  return [geoToken, buildAgeToken(form.adGroup.ageGroups), buildGenderToken(form.adGroup.gender), buildPlacementToken(form)].join("_")
}

export function buildAdName(form: TikTokRequestFormState) {
  const adGroupToken = normalizeToken(form.adGroup.adGroupName)
  if (!adGroupToken) return ""
  return [adGroupToken, buildFormatToken(form.ad.adFormat)].join("_")
}

export function buildCreativeAdName(form: TikTokRequestFormState, creative: TikTokRequestFormState["ad"], index = 0) {
  const adGroupToken = normalizeToken(form.adGroup.adGroupName)
  if (!adGroupToken) return ""
  const base = [adGroupToken, buildFormatToken(creative.adFormat)].join("_")
  return index > 0 ? `${base}_${index + 1}` : base
}

export function useAutoGeneratedNameField(currentValue: string, generatedValue: string, onApply: (value: string) => void) {
  const [isAutoEnabled, setIsAutoEnabled] = useState(true)
  const lastGeneratedNameRef = useRef("")

  useEffect(() => {
    const currentName = currentValue.trim()
    const lastGeneratedName = lastGeneratedNameRef.current.trim()
    if (!currentName || currentName === generatedValue || (lastGeneratedName && currentName === lastGeneratedName)) {
      setIsAutoEnabled(true)
      return
    }
    setIsAutoEnabled(false)
  }, [currentValue, generatedValue])

  useEffect(() => {
    if (!isAutoEnabled) return
    const currentName = currentValue.trim()
    const lastGeneratedName = lastGeneratedNameRef.current.trim()
    const looksManual = !!currentName && currentName !== generatedValue && (!lastGeneratedName || currentName !== lastGeneratedName)
    if (looksManual) return
    if (!generatedValue) {
      lastGeneratedNameRef.current = ""
      return
    }
    if (currentName === generatedValue) {
      lastGeneratedNameRef.current = generatedValue
      return
    }
    lastGeneratedNameRef.current = generatedValue
    onApply(generatedValue)
  }, [currentValue, generatedValue, isAutoEnabled, onApply])

  const applyGeneratedName = () => {
    setIsAutoEnabled(true)
    lastGeneratedNameRef.current = generatedValue
    onApply(generatedValue)
  }

  const markManual = () => setIsAutoEnabled(false)

  return {
    isAutoEnabled,
    setIsAutoEnabled,
    applyGeneratedName,
    markManual,
  }
}
