"use client"

import { useMemo, useState } from "react"
import { ChevronRight, ChevronsUpDown, Wand2, X } from "lucide-react"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { Checkbox } from "@/components/ui/checkbox"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { Popover, PopoverContent, PopoverTrigger } from "@/components/ui/popover"
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select"
import { Switch } from "@/components/ui/switch"
import { cn } from "@/lib/utils"
import type { TikTokOptionDto, TikTokReferenceResponseDto, TikTokTargetingOptionDto, TikTokTargetingOptionsResponseDto } from "@/types/tiktok-ads"
import { buildAdGroupName, useAutoGeneratedNameField } from "./naming"
import { TargetingMultiSelect } from "./searchable-select"
import { SectionShell } from "./section-shell"
import type { TikTokRequestFormState } from "./types"
import { optionLabel } from "./types"

interface Props {
  form: TikTokRequestFormState
  reference: TikTokReferenceResponseDto
  targetingOptions?: TikTokTargetingOptionsResponseDto | null
  targetingLoading?: boolean
  onChange: (patch: Partial<TikTokRequestFormState>) => void
}

function toggleValue(values: string[], value: string, checked: boolean) {
  return checked ? Array.from(new Set([...values, value])) : values.filter((item) => item !== value)
}

function OptionChecks({ options, values, onValuesChange }: { options: TikTokOptionDto[]; values: string[]; onValuesChange: (values: string[]) => void }) {
  return (
    <div className="grid gap-2 sm:grid-cols-2">
      {options.map((option) => (
        <label key={option.key} className="flex min-h-10 items-center gap-2 rounded-md border bg-white px-3 py-2 text-sm">
          <Checkbox checked={values.includes(option.key)} onCheckedChange={(checked) => onValuesChange(toggleValue(values, option.key, checked === true))} />
          <span className="min-w-0 truncate">{optionLabel(option)}</span>
        </label>
      ))}
    </div>
  )
}

interface LocationNode {
  option: TikTokTargetingOptionDto
  children: LocationNode[]
}

function sortLocationNodes(nodes: LocationNode[]) {
  nodes.sort((first, second) => first.option.label.localeCompare(second.option.label) || first.option.key.localeCompare(second.option.key))
  nodes.forEach((node) => sortLocationNodes(node.children))
}

function buildLocationTree(options: TikTokTargetingOptionDto[]) {
  const nodes = new Map<string, LocationNode>()
  options.forEach((option) => nodes.set(option.key, { option, children: [] }))

  const roots: LocationNode[] = []
  nodes.forEach((node) => {
    const parentId = node.option.parentId?.trim()
    const parent = parentId && parentId !== node.option.key ? nodes.get(parentId) : undefined
    if (parent) parent.children.push(node)
    else roots.push(node)
  })

  sortLocationNodes(roots)
  return roots
}

function locationSearchText(option: TikTokTargetingOptionDto) {
  return `${option.label} ${option.key} ${option.countryCode ?? ""} ${option.level ?? ""} ${option.path ?? ""}`.toLowerCase()
}

function filterLocationTree(nodes: LocationNode[], query: string): LocationNode[] {
  const term = query.trim().toLowerCase()
  if (!term) return nodes

  return nodes.flatMap((node) => {
    const filteredChildren = filterLocationTree(node.children, term)
    if (locationSearchText(node.option).includes(term) || filteredChildren.length > 0) {
      return [{ ...node, children: filteredChildren }]
    }
    return []
  })
}

function isCountryNode(option: TikTokTargetingOptionDto) {
  const level = option.level?.toUpperCase() ?? ""
  return level.includes("COUNTRY") || !option.parentId
}

function locationSubtitle(option: TikTokTargetingOptionDto) {
  const path = option.path?.trim()
  if (path && path.toLowerCase() !== option.label.trim().toLowerCase()) return path

  const level = option.level?.replace(/^TO_/, "").replace(/_/g, " ").toLowerCase()
  return level && !isCountryNode(option) ? level : ""
}

function LocationTreeMultiSelect({
  values,
  options,
  placeholder,
  searchPlaceholder,
  emptyMessage,
  disabled = false,
  onValuesChange,
}: {
  values: string[]
  options: TikTokTargetingOptionDto[]
  placeholder: string
  searchPlaceholder: string
  emptyMessage: string
  disabled?: boolean
  onValuesChange: (values: string[]) => void
}) {
  const [open, setOpen] = useState(false)
  const [query, setQuery] = useState("")
  const [expanded, setExpanded] = useState<Set<string>>(() => new Set(["6252001"]))
  const tree = useMemo(() => buildLocationTree(options), [options])
  const filteredTree = useMemo(() => filterLocationTree(tree, query), [query, tree])
  const optionByKey = useMemo(() => new Map(options.map((option) => [option.key, option])), [options])
  const selectedOptions = useMemo(
    () => values.map((value) => optionByKey.get(value) ?? { key: value, label: "Unknown location", type: "location" }),
    [optionByKey, values],
  )

  function toggle(value: string) {
    onValuesChange(values.includes(value) ? values.filter((item) => item !== value) : [...values, value])
  }

  function remove(value: string) {
    onValuesChange(values.filter((item) => item !== value))
  }

  function toggleExpanded(value: string) {
    setExpanded((current) => {
      const next = new Set(current)
      if (next.has(value)) next.delete(value)
      else next.add(value)
      return next
    })
  }

  function renderNode(node: LocationNode, depth = 0) {
    const isSelected = values.includes(node.option.key)
    const hasChildren = node.children.length > 0
    const isExpanded = query.trim() || expanded.has(node.option.key)
    const subtitle = locationSubtitle(node.option)

    return (
      <div key={node.option.key}>
        <div className="flex min-h-9 items-center gap-2 px-2 py-1.5 text-sm hover:bg-slate-50" style={{ paddingLeft: 8 + depth * 22 }}>
          {hasChildren ? (
            <button type="button" className="rounded-sm p-0.5 text-slate-500 hover:bg-slate-100 hover:text-slate-800" onClick={() => toggleExpanded(node.option.key)}>
              <ChevronRight className={cn("h-4 w-4 transition-transform", isExpanded && "rotate-90")} />
            </button>
          ) : (
            <span className="h-5 w-5" />
          )}
          <Checkbox checked={isSelected} onCheckedChange={() => toggle(node.option.key)} />
          <button type="button" className="min-w-0 flex-1 text-left" onClick={() => toggle(node.option.key)}>
            <span className={cn("block truncate", isCountryNode(node.option) ? "font-medium text-slate-900" : "text-slate-700")}>{node.option.label}</span>
            {subtitle ? <span className="block truncate text-xs text-slate-400">{subtitle}</span> : null}
          </button>
        </div>
        {hasChildren && isExpanded ? node.children.map((child) => renderNode(child, depth + 1)) : null}
      </div>
    )
  }

  return (
    <div className="space-y-2">
      <Popover open={open} onOpenChange={(nextOpen) => !disabled && setOpen(nextOpen)}>
        <PopoverTrigger asChild>
          <Button
            type="button"
            variant="outline"
            role="combobox"
            disabled={disabled}
            className="min-h-10 w-full justify-between bg-white px-3 text-left font-normal"
          >
            <span className={cn("min-w-0 flex-1 truncate", values.length === 0 && "text-slate-500")}>
              {values.length === 0 ? placeholder : `${values.length} selected`}
            </span>
            <ChevronsUpDown className="ml-2 h-4 w-4 shrink-0 opacity-50" />
          </Button>
        </PopoverTrigger>
        <PopoverContent className="w-[--radix-popover-trigger-width] min-w-[420px] p-0" align="start">
          <div className="border-b p-2">
            <Input value={query} onChange={(event) => setQuery(event.target.value)} placeholder={searchPlaceholder} className="h-9" />
          </div>
          <div className="max-h-80 overflow-y-auto py-1">
            {filteredTree.length > 0 ? filteredTree.map((node) => renderNode(node)) : <div className="px-3 py-6 text-center text-sm text-slate-500">{emptyMessage}</div>}
          </div>
        </PopoverContent>
      </Popover>

      {selectedOptions.length > 0 ? (
        <div className="flex flex-wrap gap-1.5">
          {selectedOptions.map((option) => (
            <Badge key={option.key} variant="outline" className="gap-1 rounded-md bg-white px-2 py-1 text-xs">
              <span className="max-w-[180px] truncate">{option.label}</span>
              <button type="button" className="rounded-sm text-slate-400 hover:text-slate-700" onClick={() => remove(option.key)}>
                <X className="h-3 w-3" />
              </button>
            </Badge>
          ))}
        </div>
      ) : null}
    </div>
  )
}

export function AdGroupAudienceSection({ form, reference, targetingOptions, targetingLoading = false, onChange }: Props) {
  const ready = form.adGroup.locationIds.length > 0 && form.adGroup.placementType.length > 0
  const generatedAdGroupName = buildAdGroupName(form, targetingOptions?.locations)
  const { isAutoEnabled, setIsAutoEnabled, applyGeneratedName, markManual } = useAutoGeneratedNameField(
    form.adGroup.adGroupName,
    generatedAdGroupName,
    (value) => onChange({ adGroup: { ...form.adGroup, adGroupName: value } }),
  )

  return (
    <SectionShell
      eyebrow="Ad Group - Audience & Placement"
      title="Audience & Placement"
      description="Configure audience controls, optional audience suggestions, and placements."
      ready={ready}
    >
      <div className="space-y-5">
        <div className="space-y-2">
          <div className="flex items-center justify-between gap-3">
            <Label>Ad group name</Label>
            <div className="flex items-center gap-2 text-xs text-slate-600">
              <Wand2 className="h-3.5 w-3.5 text-slate-400" />
              <span>Auto-generate</span>
              <Switch checked={isAutoEnabled} onCheckedChange={(checked) => { setIsAutoEnabled(checked); if (checked) applyGeneratedName() }} />
            </div>
          </div>
          <Input value={form.adGroup.adGroupName} onChange={(event) => { markManual(); onChange({ adGroup: { ...form.adGroup, adGroupName: event.target.value } }) }} />
          <div className="rounded-md border bg-slate-50 px-3 py-2">
            <p className="text-xs text-slate-500">Pattern: <code className="rounded bg-white px-1 py-0.5">GEO_AGE_GENDER_PLACEMENT</code></p>
            <p className={generatedAdGroupName ? "mt-1 font-mono text-xs text-slate-700" : "mt-1 text-xs italic text-slate-400"}>{generatedAdGroupName || "Select locations to generate an ad group name."}</p>
            {!isAutoEnabled && generatedAdGroupName ? (
              <button type="button" onClick={applyGeneratedName} className="mt-1 text-xs font-medium text-blue-600 hover:text-blue-700">Use generated name</button>
            ) : null}
          </div>
        </div>

        <div className="rounded-md border bg-slate-50 p-4">
          <div className="mb-3 flex items-center justify-between gap-3">
            <div>
              <h3 className="text-sm font-semibold text-slate-900">Audience controls</h3>
              <p className="text-xs text-slate-500">Locations are required and limit who can see the ad.</p>
            </div>
            <Badge variant="outline">{targetingLoading ? "Loading TikTok options" : targetingOptions?.source ?? "fallback"}</Badge>
          </div>
          <LocationTreeMultiSelect
            values={form.adGroup.locationIds}
            options={targetingOptions?.locations ?? []}
            placeholder={targetingLoading ? "Loading locations..." : "Select locations..."}
            searchPlaceholder="Search locations by country, region, or ID..."
            emptyMessage="No locations found."
            disabled={targetingLoading}
            onValuesChange={(values) => onChange({ adGroup: { ...form.adGroup, locationIds: values } })}
          />
          {targetingOptions?.errorMessage ? <p className="mt-2 text-xs text-amber-700">{targetingOptions.errorMessage}</p> : null}
        </div>

        <div className="rounded-md border bg-white p-4">
          <div className="mb-3">
            <h3 className="text-sm font-semibold text-slate-900">Audience suggestions</h3>
            <p className="text-xs text-slate-500">These guide delivery but do not replace TikTok optimization.</p>
          </div>
          <div className="grid gap-4 md:grid-cols-2">
            <div className="space-y-2">
              <Label>Operating systems</Label>
              <OptionChecks options={reference.operatingSystems} values={form.adGroup.operatingSystems} onValuesChange={(values) => onChange({ adGroup: { ...form.adGroup, operatingSystems: values } })} />
            </div>
            <div className="space-y-2">
              <Label>Gender</Label>
              <Select value={form.adGroup.gender} onValueChange={(value) => onChange({ adGroup: { ...form.adGroup, gender: value } })}>
                <SelectTrigger>
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  {reference.genders.map((option) => (
                    <SelectItem key={option.key} value={option.key}>{optionLabel(option)}</SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>
            <div className="space-y-2 md:col-span-2">
              <Label>Age groups</Label>
              <OptionChecks options={reference.ageGroups} values={form.adGroup.ageGroups} onValuesChange={(values) => onChange({ adGroup: { ...form.adGroup, ageGroups: values } })} />
            </div>
            <div className="space-y-2 md:col-span-2">
              <Label>Languages</Label>
              <TargetingMultiSelect
                values={form.adGroup.languages}
                options={targetingOptions?.languages ?? []}
                placeholder={targetingLoading ? "Loading languages..." : "Select languages..."}
                searchPlaceholder="Search languages by name or code..."
                emptyMessage="No languages found."
                disabled={targetingLoading}
                onValuesChange={(values) => onChange({ adGroup: { ...form.adGroup, languages: values } })}
              />
            </div>
          </div>
        </div>

        <div className="rounded-md border bg-white p-4">
          <div className="mb-3 flex items-center justify-between gap-3">
            <div>
              <h3 className="text-sm font-semibold text-slate-900">Placement</h3>
              <p className="text-xs text-slate-500">Automatic placement lets TikTok optimize across available inventory.</p>
            </div>
            <Badge className={form.adGroup.placementType === "PLACEMENT_TYPE_AUTOMATIC" ? "bg-emerald-50 text-emerald-700" : "bg-blue-50 text-blue-700"}>
              {form.adGroup.placementType === "PLACEMENT_TYPE_AUTOMATIC" ? "Automatic" : "Manual"}
            </Badge>
          </div>
          <div className="grid gap-4 md:grid-cols-2">
            <div className="space-y-2">
              <Label>Placement type</Label>
              <Select
                value={form.adGroup.placementType}
                onValueChange={(value) => onChange({
                  adGroup: {
                    ...form.adGroup,
                    placementType: value,
                    placements: value === "PLACEMENT_TYPE_AUTOMATIC" ? [] : form.adGroup.placements,
                  },
                })}
              >
                <SelectTrigger>
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  {reference.placementTypes.map((option) => (
                    <SelectItem key={option.key} value={option.key}>{optionLabel(option)}</SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>
            <div className={form.adGroup.placementType === "PLACEMENT_TYPE_AUTOMATIC" ? "pointer-events-none space-y-2 opacity-50" : "space-y-2"}>
              <Label>Manual placements</Label>
              <OptionChecks options={reference.placements} values={form.adGroup.placements} onValuesChange={(values) => onChange({ adGroup: { ...form.adGroup, placements: values } })} />
            </div>
          </div>
        </div>
      </div>
    </SectionShell>
  )
}
