"use client"

import { Wand2 } from "lucide-react"
import { Badge } from "@/components/ui/badge"
import { Checkbox } from "@/components/ui/checkbox"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select"
import { Switch } from "@/components/ui/switch"
import type { TikTokOptionDto, TikTokReferenceResponseDto, TikTokTargetingOptionsResponseDto } from "@/types/tiktok-ads"
import { buildAdGroupName, useAutoGeneratedNameField } from "./naming"
import { TargetingMultiSelect } from "./searchable-select"
import { SectionShell } from "./section-shell"
import type { TikTokRequestFormState } from "./types"
import { optionLabel } from "./types"

interface Props {
  form: TikTokRequestFormState
  reference: TikTokReferenceResponseDto
  targetingOptions?: TikTokTargetingOptionsResponseDto | null
  targetingLoading?: boolean
  onChange: (patch: Partial<TikTokRequestFormState>) => void
}

function toggleValue(values: string[], value: string, checked: boolean) {
  return checked ? Array.from(new Set([...values, value])) : values.filter((item) => item !== value)
}

function OptionChecks({ options, values, onValuesChange }: { options: TikTokOptionDto[]; values: string[]; onValuesChange: (values: string[]) => void }) {
  return (
    <div className="grid gap-2 sm:grid-cols-2">
      {options.map((option) => (
        <label key={option.key} className="flex min-h-10 items-center gap-2 rounded-md border bg-white px-3 py-2 text-sm">
          <Checkbox checked={values.includes(option.key)} onCheckedChange={(checked) => onValuesChange(toggleValue(values, option.key, checked === true))} />
          <span className="min-w-0 truncate">{optionLabel(option)}</span>
        </label>
      ))}
    </div>
  )
}

export function AdGroupAudienceSection({ form, reference, targetingOptions, targetingLoading = false, onChange }: Props) {
  const ready = form.adGroup.locationIds.length > 0 && form.adGroup.placementType.length > 0
  const generatedAdGroupName = buildAdGroupName(form, targetingOptions?.locations)
  const { isAutoEnabled, setIsAutoEnabled, applyGeneratedName, markManual } = useAutoGeneratedNameField(
    form.adGroup.adGroupName,
    generatedAdGroupName,
    (value) => onChange({ adGroup: { ...form.adGroup, adGroupName: value } }),
  )

  return (
    <SectionShell
      eyebrow="Ad Group - Audience & Placement"
      title="Audience & Placement"
      description="Configure audience controls, optional audience suggestions, and placements."
      ready={ready}
    >
      <div className="space-y-5">
        <div className="space-y-2">
          <div className="flex items-center justify-between gap-3">
            <Label>Ad group name</Label>
            <div className="flex items-center gap-2 text-xs text-slate-600">
              <Wand2 className="h-3.5 w-3.5 text-slate-400" />
              <span>Auto-generate</span>
              <Switch checked={isAutoEnabled} onCheckedChange={(checked) => { setIsAutoEnabled(checked); if (checked) applyGeneratedName() }} />
            </div>
          </div>
          <Input value={form.adGroup.adGroupName} onChange={(event) => { markManual(); onChange({ adGroup: { ...form.adGroup, adGroupName: event.target.value } }) }} />
          <div className="rounded-md border bg-slate-50 px-3 py-2">
            <p className="text-xs text-slate-500">Pattern: <code className="rounded bg-white px-1 py-0.5">GEO_AGE_GENDER_PLACEMENT</code></p>
            <p className={generatedAdGroupName ? "mt-1 font-mono text-xs text-slate-700" : "mt-1 text-xs italic text-slate-400"}>{generatedAdGroupName || "Select locations to generate an ad group name."}</p>
            {!isAutoEnabled && generatedAdGroupName ? (
              <button type="button" onClick={applyGeneratedName} className="mt-1 text-xs font-medium text-blue-600 hover:text-blue-700">Use generated name</button>
            ) : null}
          </div>
        </div>

        <div className="rounded-md border bg-slate-50 p-4">
          <div className="mb-3 flex items-center justify-between gap-3">
            <div>
              <h3 className="text-sm font-semibold text-slate-900">Audience controls</h3>
              <p className="text-xs text-slate-500">Locations are required and limit who can see the ad.</p>
            </div>
            <Badge variant="outline">{targetingLoading ? "Loading TikTok options" : targetingOptions?.source ?? "fallback"}</Badge>
          </div>
          <TargetingMultiSelect
            values={form.adGroup.locationIds}
            options={targetingOptions?.locations ?? []}
            placeholder={targetingLoading ? "Loading locations..." : "Select locations..."}
            searchPlaceholder="Search locations by country, region, or ID..."
            emptyMessage="No locations found."
            disabled={targetingLoading}
            onValuesChange={(values) => onChange({ adGroup: { ...form.adGroup, locationIds: values } })}
          />
          {targetingOptions?.errorMessage ? <p className="mt-2 text-xs text-amber-700">{targetingOptions.errorMessage}</p> : null}
        </div>

        <div className="rounded-md border bg-white p-4">
          <div className="mb-3">
            <h3 className="text-sm font-semibold text-slate-900">Audience suggestions</h3>
            <p className="text-xs text-slate-500">These guide delivery but do not replace TikTok optimization.</p>
          </div>
          <div className="grid gap-4 md:grid-cols-2">
            <div className="space-y-2">
              <Label>Operating systems</Label>
              <OptionChecks options={reference.operatingSystems} values={form.adGroup.operatingSystems} onValuesChange={(values) => onChange({ adGroup: { ...form.adGroup, operatingSystems: values } })} />
            </div>
            <div className="space-y-2">
              <Label>Gender</Label>
              <Select value={form.adGroup.gender} onValueChange={(value) => onChange({ adGroup: { ...form.adGroup, gender: value } })}>
                <SelectTrigger>
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  {reference.genders.map((option) => (
                    <SelectItem key={option.key} value={option.key}>{optionLabel(option)}</SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>
            <div className="space-y-2 md:col-span-2">
              <Label>Age groups</Label>
              <OptionChecks options={reference.ageGroups} values={form.adGroup.ageGroups} onValuesChange={(values) => onChange({ adGroup: { ...form.adGroup, ageGroups: values } })} />
            </div>
            <div className="space-y-2 md:col-span-2">
              <Label>Languages</Label>
              <TargetingMultiSelect
                values={form.adGroup.languages}
                options={targetingOptions?.languages ?? []}
                placeholder={targetingLoading ? "Loading languages..." : "Select languages..."}
                searchPlaceholder="Search languages by name or code..."
                emptyMessage="No languages found."
                disabled={targetingLoading}
                onValuesChange={(values) => onChange({ adGroup: { ...form.adGroup, languages: values } })}
              />
            </div>
          </div>
        </div>

        <div className="rounded-md border bg-white p-4">
          <div className="mb-3 flex items-center justify-between gap-3">
            <div>
              <h3 className="text-sm font-semibold text-slate-900">Placement</h3>
              <p className="text-xs text-slate-500">Automatic placement lets TikTok optimize across available inventory.</p>
            </div>
            <Badge className={form.adGroup.placementType === "PLACEMENT_TYPE_AUTOMATIC" ? "bg-emerald-50 text-emerald-700" : "bg-blue-50 text-blue-700"}>
              {form.adGroup.placementType === "PLACEMENT_TYPE_AUTOMATIC" ? "Automatic" : "Manual"}
            </Badge>
          </div>
          <div className="grid gap-4 md:grid-cols-2">
            <div className="space-y-2">
              <Label>Placement type</Label>
              <Select
                value={form.adGroup.placementType}
                onValueChange={(value) => onChange({
                  adGroup: {
                    ...form.adGroup,
                    placementType: value,
                    placements: value === "PLACEMENT_TYPE_AUTOMATIC" ? [] : form.adGroup.placements,
                  },
                })}
              >
                <SelectTrigger>
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  {reference.placementTypes.map((option) => (
                    <SelectItem key={option.key} value={option.key}>{optionLabel(option)}</SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>
            <div className={form.adGroup.placementType === "PLACEMENT_TYPE_AUTOMATIC" ? "pointer-events-none space-y-2 opacity-50" : "space-y-2"}>
              <Label>Manual placements</Label>
              <OptionChecks options={reference.placements} values={form.adGroup.placements} onValuesChange={(values) => onChange({ adGroup: { ...form.adGroup, placements: values } })} />
            </div>
          </div>
        </div>
      </div>
    </SectionShell>
  )
}
