"use client"

import { Wand2 } from "lucide-react"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select"
import { Switch } from "@/components/ui/switch"
import { Textarea } from "@/components/ui/textarea"
import type { TikTokReferenceResponseDto } from "@/types/tiktok-ads"
import { buildAdName, useAutoGeneratedNameField } from "./naming"
import { SectionShell } from "./section-shell"
import type { TikTokRequestFormState } from "./types"
import { optionLabel } from "./types"

interface Props {
  form: TikTokRequestFormState
  reference: TikTokReferenceResponseDto
  onChange: (patch: Partial<TikTokRequestFormState>) => void
}

export function AdSection({ form, reference, onChange }: Props) {
  const ready = Boolean(form.ad.adName.trim() && (form.ad.adTexts?.some((item) => item.trim()) || form.ad.adText?.trim()) && form.ad.callToAction && form.ad.landingPageUrl?.trim())
  const generatedAdName = buildAdName(form)
  const { isAutoEnabled, setIsAutoEnabled, applyGeneratedName, markManual } = useAutoGeneratedNameField(
    form.ad.adName,
    generatedAdName,
    (value) => onChange({ ad: { ...form.ad, adName: value } }),
  )

  return (
    <SectionShell
      eyebrow="Ad"
      title="Ad Copy & Destination"
      description="Complete ad name, copy, CTA, and destination URL."
      ready={ready}
    >
      <div className="grid gap-4 md:grid-cols-2">
        <div className="space-y-2 md:col-span-2">
          <div className="flex flex-wrap items-center justify-between gap-3">
            <Label>Ad name</Label>
            <div className="flex items-center gap-2 text-xs text-muted-foreground">
              <Wand2 className="h-3.5 w-3.5 text-muted-foreground" />
              <span>Auto-generate</span>
              <Switch checked={isAutoEnabled} onCheckedChange={(checked) => { setIsAutoEnabled(checked); if (checked) applyGeneratedName() }} />
            </div>
          </div>
          <Input value={form.ad.adName} onChange={(event) => { markManual(); onChange({ ad: { ...form.ad, adName: event.target.value } }) }} />
          <div className="rounded-md border bg-muted/40 px-3 py-2">
            <p className="text-xs text-muted-foreground">Pattern: <code className="rounded bg-background px-1 py-0.5">ADGROUP_FORMAT</code></p>
            <p className={generatedAdName ? "mt-1 font-mono text-xs text-foreground" : "mt-1 text-xs italic text-muted-foreground"}>{generatedAdName || "Enter an ad group name to generate an ad name."}</p>
            {!isAutoEnabled && generatedAdName ? (
              <button type="button" onClick={applyGeneratedName} className="mt-1 text-xs font-medium text-primary hover:text-primary/80">Use generated name</button>
            ) : null}
          </div>
        </div>
        <div className="space-y-2">
          <Label>Call to action</Label>
          <Select value={form.ad.callToAction ?? "INSTALL_NOW"} onValueChange={(value) => onChange({ ad: { ...form.ad, callToAction: value } })}>
            <SelectTrigger>
              <SelectValue />
            </SelectTrigger>
            <SelectContent>
              {reference.callToActions.map((option) => (
                <SelectItem key={option.key} value={option.key}>{optionLabel(option)}</SelectItem>
              ))}
            </SelectContent>
          </Select>
        </div>
        <div className="space-y-2 md:col-span-2">
          <Label>Ad text</Label>
          <Textarea rows={4} value={(form.ad.adTexts?.length ? form.ad.adTexts : form.ad.adText ? [form.ad.adText] : []).join("\n")} onChange={(event) => { const adTexts = event.target.value.split(/\r?\n/).map((item) => item.trim()).filter(Boolean).slice(0, 5); onChange({ ad: { ...form.ad, adText: adTexts[0] ?? "", adTexts } }) }} />
        </div>
        <div className="space-y-2">
          <Label>Landing page URL</Label>
          <Input value={form.ad.landingPageUrl ?? ""} onChange={(event) => onChange({ ad: { ...form.ad, landingPageUrl: event.target.value } })} />
        </div>
        <div className="space-y-2">
          <Label>Tracking URL</Label>
          <Input value={form.ad.trackingUrl ?? ""} onChange={(event) => onChange({ ad: { ...form.ad, trackingUrl: event.target.value } })} />
        </div>
      </div>
    </SectionShell>
  )
}

