"use client"

import { Wand2 } from "lucide-react"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select"
import { Switch } from "@/components/ui/switch"
import type { TikTokAppMappingDto, TikTokReferenceResponseDto, TikTokTargetingOptionDto } from "@/types/tiktok-ads"
import { buildCampaignName, useAutoGeneratedNameField } from "./naming"
import { SectionShell } from "./section-shell"
import type { TikTokRequestFormState } from "./types"
import { optionLabel } from "./types"

interface Props {
  form: TikTokRequestFormState
  reference: TikTokReferenceResponseDto
  selectedAppMapping?: TikTokAppMappingDto | null
  locations?: TikTokTargetingOptionDto[]
  onChange: (patch: Partial<TikTokRequestFormState>) => void
}

function numberOrUndefined(value: string) {
  return value === "" ? undefined : Number(value)
}

export function CampaignSettingsSection({ form, reference, selectedAppMapping, locations, onChange }: Props) {
  const ready = Boolean(form.campaign.campaignName.trim() && form.campaign.objectiveType && form.campaign.budgetMode && Number(form.campaign.budget ?? 0) > 0)
  const generatedCampaignName = buildCampaignName(form, selectedAppMapping, locations)
  const { isAutoEnabled, setIsAutoEnabled, applyGeneratedName, markManual } = useAutoGeneratedNameField(
    form.campaign.campaignName,
    generatedCampaignName,
    (value) => onChange({ campaign: { ...form.campaign, campaignName: value } }),
  )

  return (
    <SectionShell
      eyebrow="Campaign Settings"
      title="Campaign"
      description="Set campaign objective and campaign-level budget."
      ready={ready}
    >
      <div className="grid min-w-0 gap-4 md:grid-cols-2">
        <div className="min-w-0 space-y-2 md:col-span-2">
          <div className="flex flex-col items-start gap-2 sm:flex-row sm:items-center sm:justify-between sm:gap-3">
            <Label>Campaign name</Label>
            <div className="flex shrink-0 items-center gap-2 text-xs text-muted-foreground">
              <Wand2 className="h-3.5 w-3.5 text-muted-foreground" />
              <span>Auto-generate</span>
              <Switch checked={isAutoEnabled} onCheckedChange={(checked) => { setIsAutoEnabled(checked); if (checked) applyGeneratedName() }} />
            </div>
          </div>
          <Input
            value={form.campaign.campaignName}
            onChange={(event) => { markManual(); onChange({ campaign: { ...form.campaign, campaignName: event.target.value } }) }}
            placeholder="APP_GEO_PLATFORM_OBJECTIVE_YYYYMMDD"
          />
          <div className="min-w-0 overflow-hidden rounded-md border bg-muted/40 px-3 py-2">
            <p className="text-xs text-muted-foreground">Pattern: <code className="inline-block max-w-full break-all rounded bg-background px-1 py-0.5 align-bottom">APP_GEO_PLATFORM_OBJECTIVE_YYYYMMDD</code></p>
            <p className={generatedCampaignName ? "mt-1 break-all font-mono text-xs text-foreground" : "mt-1 text-xs italic text-muted-foreground"}>{generatedCampaignName || "Select app and location to generate a campaign name."}</p>
            {!isAutoEnabled && generatedCampaignName ? (
              <button type="button" onClick={applyGeneratedName} className="mt-1 text-xs font-medium text-primary hover:text-primary/80">Use generated name</button>
            ) : null}
          </div>
        </div>
        <div className="min-w-0 space-y-2">
          <Label>Objective</Label>
          <Select value={form.campaign.objectiveType} onValueChange={(value) => onChange({ campaign: { ...form.campaign, objectiveType: value } })}>
            <SelectTrigger className="w-full min-w-0">
              <SelectValue />
            </SelectTrigger>
            <SelectContent>
              {reference.objectives.map((option) => (
                <SelectItem key={option.key} value={option.key}>{optionLabel(option)}</SelectItem>
              ))}
            </SelectContent>
          </Select>
        </div>
        <div className="min-w-0 space-y-2">
          <Label>Campaign budget mode</Label>
          <Select value={form.campaign.budgetMode} onValueChange={(value) => onChange({ campaign: { ...form.campaign, budgetMode: value } })}>
            <SelectTrigger className="w-full min-w-0">
              <SelectValue />
            </SelectTrigger>
            <SelectContent>
              {reference.budgetModes.map((option) => (
                <SelectItem key={option.key} value={option.key}>{optionLabel(option)}</SelectItem>
              ))}
            </SelectContent>
          </Select>
        </div>
        <div className="min-w-0 space-y-2">
          <Label>Campaign budget</Label>
          <Input
            min={50}
            step="0.01"
            type="number"
            value={form.campaign.budget ?? ""}
            onChange={(event) => onChange({ campaign: { ...form.campaign, budget: numberOrUndefined(event.target.value) } })}
          />
          <p className="text-xs text-muted-foreground">TikTok requires a minimum budget of $50.</p>
        </div>
      </div>
    </SectionShell>
  )
}

