-- Seed data for silver.dim_country
-- Map ISO 3166-1 alpha-2 codes to country names
-- country_name_firebase: Tên từ Firebase GA4 (có thể khác chuẩn ISO)
-- region: APAC, EMEA, LATAM, NA, AFRICA
-- tier: T1 (high eCPM), T2 (medium), T3 (low)

DELETE FROM silver.dim_country WHERE 1=1;

INSERT INTO silver.dim_country (country_code, country_name, country_name_firebase, region, tier, _updated_at) VALUES
-- T1 Countries (High eCPM)
('US', 'United States', 'United States', 'NA', 'T1', NOW()),
('GB', 'United Kingdom', 'United Kingdom', 'EMEA', 'T1', NOW()),
('CA', 'Canada', 'Canada', 'NA', 'T1', NOW()),
('AU', 'Australia', 'Australia', 'APAC', 'T1', NOW()),
('DE', 'Germany', 'Germany', 'EMEA', 'T1', NOW()),
('FR', 'France', 'France', 'EMEA', 'T1', NOW()),
('JP', 'Japan', 'Japan', 'APAC', 'T1', NOW()),
('KR', 'South Korea', 'South Korea', 'APAC', 'T1', NOW()),
('CH', 'Switzerland', 'Switzerland', 'EMEA', 'T1', NOW()),
('NO', 'Norway', 'Norway', 'EMEA', 'T1', NOW()),
('SE', 'Sweden', 'Sweden', 'EMEA', 'T1', NOW()),
('DK', 'Denmark', 'Denmark', 'EMEA', 'T1', NOW()),
('NL', 'Netherlands', 'Netherlands', 'EMEA', 'T1', NOW()),
('BE', 'Belgium', 'Belgium', 'EMEA', 'T1', NOW()),
('AT', 'Austria', 'Austria', 'EMEA', 'T1', NOW()),
('NZ', 'New Zealand', 'New Zealand', 'APAC', 'T1', NOW()),
('IE', 'Ireland', 'Ireland', 'EMEA', 'T1', NOW()),
('FI', 'Finland', 'Finland', 'EMEA', 'T1', NOW()),
('SG', 'Singapore', 'Singapore', 'APAC', 'T1', NOW()),
('LU', 'Luxembourg', 'Luxembourg', 'EMEA', 'T1', NOW()),

-- T2 Countries (Medium eCPM)
('IT', 'Italy', 'Italy', 'EMEA', 'T2', NOW()),
('ES', 'Spain', 'Spain', 'EMEA', 'T2', NOW()),
('PT', 'Portugal', 'Portugal', 'EMEA', 'T2', NOW()),
('TW', 'Taiwan', 'Taiwan', 'APAC', 'T2', NOW()),
('HK', 'Hong Kong', 'Hong Kong', 'APAC', 'T2', NOW()),
('IL', 'Israel', 'Israel', 'EMEA', 'T2', NOW()),
('AE', 'United Arab Emirates', 'United Arab Emirates', 'EMEA', 'T2', NOW()),
('SA', 'Saudi Arabia', 'Saudi Arabia', 'EMEA', 'T2', NOW()),
('QA', 'Qatar', 'Qatar', 'EMEA', 'T2', NOW()),
('KW', 'Kuwait', 'Kuwait', 'EMEA', 'T2', NOW()),
('BH', 'Bahrain', 'Bahrain', 'EMEA', 'T2', NOW()),
('OM', 'Oman', 'Oman', 'EMEA', 'T2', NOW()),
('JO', 'Jordan', 'Jordan', 'EMEA', 'T2', NOW()),
('CZ', 'Czech Republic', 'Czechia', 'EMEA', 'T2', NOW()),
('PL', 'Poland', 'Poland', 'EMEA', 'T2', NOW()),
('HU', 'Hungary', 'Hungary', 'EMEA', 'T2', NOW()),
('GR', 'Greece', 'Greece', 'EMEA', 'T2', NOW()),
('RO', 'Romania', 'Romania', 'EMEA', 'T2', NOW()),
('BG', 'Bulgaria', 'Bulgaria', 'EMEA', 'T2', NOW()),
('HR', 'Croatia', 'Croatia', 'EMEA', 'T2', NOW()),
('SI', 'Slovenia', 'Slovenia', 'EMEA', 'T2', NOW()),
('SK', 'Slovakia', 'Slovakia', 'EMEA', 'T2', NOW()),
('EE', 'Estonia', 'Estonia', 'EMEA', 'T2', NOW()),
('LV', 'Latvia', 'Latvia', 'EMEA', 'T2', NOW()),
('LT', 'Lithuania', 'Lithuania', 'EMEA', 'T2', NOW()),
('CY', 'Cyprus', 'Cyprus', 'EMEA', 'T2', NOW()),
('MT', 'Malta', 'Malta', 'EMEA', 'T2', NOW()),
('MY', 'Malaysia', 'Malaysia', 'APAC', 'T2', NOW()),
('TH', 'Thailand', 'Thailand', 'APAC', 'T2', NOW()),
('BR', 'Brazil', 'Brazil', 'LATAM', 'T2', NOW()),
('MX', 'Mexico', 'Mexico', 'LATAM', 'T2', NOW()),
('AR', 'Argentina', 'Argentina', 'LATAM', 'T2', NOW()),
('CL', 'Chile', 'Chile', 'LATAM', 'T2', NOW()),
('CO', 'Colombia', 'Colombia', 'LATAM', 'T2', NOW()),
('PE', 'Peru', 'Peru', 'LATAM', 'T2', NOW()),
('ZA', 'South Africa', 'South Africa', 'AFRICA', 'T2', NOW()),
('TR', 'Turkey', 'Türkiye', 'EMEA', 'T2', NOW()),
('RU', 'Russia', 'Russia', 'EMEA', 'T2', NOW()),
('UA', 'Ukraine', 'Ukraine', 'EMEA', 'T2', NOW()),

-- T3 Countries (Lower eCPM but high volume)
('IN', 'India', 'India', 'APAC', 'T3', NOW()),
('ID', 'Indonesia', 'Indonesia', 'APAC', 'T3', NOW()),
('PH', 'Philippines', 'Philippines', 'APAC', 'T3', NOW()),
('VN', 'Vietnam', 'Vietnam', 'APAC', 'T3', NOW()),
('PK', 'Pakistan', 'Pakistan', 'APAC', 'T3', NOW()),
('BD', 'Bangladesh', 'Bangladesh', 'APAC', 'T3', NOW()),
('EG', 'Egypt', 'Egypt', 'AFRICA', 'T3', NOW()),
('NG', 'Nigeria', 'Nigeria', 'AFRICA', 'T3', NOW()),
('KE', 'Kenya', 'Kenya', 'AFRICA', 'T3', NOW()),
('GH', 'Ghana', 'Ghana', 'AFRICA', 'T3', NOW()),
('TZ', 'Tanzania', 'Tanzania', 'AFRICA', 'T3', NOW()),
('UG', 'Uganda', 'Uganda', 'AFRICA', 'T3', NOW()),
('ET', 'Ethiopia', 'Ethiopia', 'AFRICA', 'T3', NOW()),
('MA', 'Morocco', 'Morocco', 'AFRICA', 'T3', NOW()),
('DZ', 'Algeria', 'Algeria', 'AFRICA', 'T3', NOW()),
('TN', 'Tunisia', 'Tunisia', 'AFRICA', 'T3', NOW()),
('IQ', 'Iraq', 'Iraq', 'EMEA', 'T3', NOW()),
('IR', 'Iran', 'Iran', 'EMEA', 'T3', NOW()),
('LB', 'Lebanon', 'Lebanon', 'EMEA', 'T3', NOW()),
('SY', 'Syria', 'Syria', 'EMEA', 'T3', NOW()),
('YE', 'Yemen', 'Yemen', 'EMEA', 'T3', NOW()),
('AF', 'Afghanistan', 'Afghanistan', 'APAC', 'T3', NOW()),
('MM', 'Myanmar', 'Myanmar (Burma)', 'APAC', 'T3', NOW()),
('KH', 'Cambodia', 'Cambodia', 'APAC', 'T3', NOW()),
('LA', 'Laos', 'Laos', 'APAC', 'T3', NOW()),
('NP', 'Nepal', 'Nepal', 'APAC', 'T3', NOW()),
('LK', 'Sri Lanka', 'Sri Lanka', 'APAC', 'T3', NOW()),
('MN', 'Mongolia', 'Mongolia', 'APAC', 'T3', NOW()),
('KZ', 'Kazakhstan', 'Kazakhstan', 'APAC', 'T3', NOW()),
('UZ', 'Uzbekistan', 'Uzbekistan', 'APAC', 'T3', NOW()),
('KG', 'Kyrgyzstan', 'Kyrgyzstan', 'APAC', 'T3', NOW()),
('TJ', 'Tajikistan', 'Tajikistan', 'APAC', 'T3', NOW()),
('TM', 'Turkmenistan', 'Turkmenistan', 'APAC', 'T3', NOW()),
('AZ', 'Azerbaijan', 'Azerbaijan', 'APAC', 'T3', NOW()),
('GE', 'Georgia', 'Georgia', 'EMEA', 'T3', NOW()),
('AM', 'Armenia', 'Armenia', 'EMEA', 'T3', NOW()),
('BY', 'Belarus', 'Belarus', 'EMEA', 'T3', NOW()),
('MD', 'Moldova', 'Moldova', 'EMEA', 'T3', NOW()),
('RS', 'Serbia', 'Serbia', 'EMEA', 'T3', NOW()),
('BA', 'Bosnia and Herzegovina', 'Bosnia & Herzegovina', 'EMEA', 'T3', NOW()),
('ME', 'Montenegro', 'Montenegro', 'EMEA', 'T3', NOW()),
('MK', 'North Macedonia', 'North Macedonia', 'EMEA', 'T3', NOW()),
('AL', 'Albania', 'Albania', 'EMEA', 'T3', NOW()),
('XK', 'Kosovo', 'Kosovo', 'EMEA', 'T3', NOW()),

-- LATAM T3
('EC', 'Ecuador', 'Ecuador', 'LATAM', 'T3', NOW()),
('VE', 'Venezuela', 'Venezuela', 'LATAM', 'T3', NOW()),
('BO', 'Bolivia', 'Bolivia', 'LATAM', 'T3', NOW()),
('PY', 'Paraguay', 'Paraguay', 'LATAM', 'T3', NOW()),
('UY', 'Uruguay', 'Uruguay', 'LATAM', 'T3', NOW()),
('PA', 'Panama', 'Panama', 'LATAM', 'T3', NOW()),
('CR', 'Costa Rica', 'Costa Rica', 'LATAM', 'T3', NOW()),
('GT', 'Guatemala', 'Guatemala', 'LATAM', 'T3', NOW()),
('HN', 'Honduras', 'Honduras', 'LATAM', 'T3', NOW()),
('SV', 'El Salvador', 'El Salvador', 'LATAM', 'T3', NOW()),
('NI', 'Nicaragua', 'Nicaragua', 'LATAM', 'T3', NOW()),
('DO', 'Dominican Republic', 'Dominican Republic', 'LATAM', 'T3', NOW()),
('PR', 'Puerto Rico', 'Puerto Rico', 'LATAM', 'T2', NOW()),
('CU', 'Cuba', 'Cuba', 'LATAM', 'T3', NOW()),
('JM', 'Jamaica', 'Jamaica', 'LATAM', 'T3', NOW()),
('HT', 'Haiti', 'Haiti', 'LATAM', 'T3', NOW()),
('TT', 'Trinidad and Tobago', 'Trinidad & Tobago', 'LATAM', 'T3', NOW()),
('BS', 'Bahamas', 'Bahamas', 'LATAM', 'T3', NOW()),
('BB', 'Barbados', 'Barbados', 'LATAM', 'T3', NOW()),
('BZ', 'Belize', 'Belize', 'LATAM', 'T3', NOW()),
('GY', 'Guyana', 'Guyana', 'LATAM', 'T3', NOW()),
('SR', 'Suriname', 'Suriname', 'LATAM', 'T3', NOW()),
('GF', 'French Guiana', 'French Guiana', 'LATAM', 'T3', NOW()),

-- Africa T3
('ZA', 'South Africa', 'South Africa', 'AFRICA', 'T2', NOW()),
('CM', 'Cameroon', 'Cameroon', 'AFRICA', 'T3', NOW()),
('CI', 'Ivory Coast', 'Côte d''Ivoire', 'AFRICA', 'T3', NOW()),
('SN', 'Senegal', 'Senegal', 'AFRICA', 'T3', NOW()),
('ZM', 'Zambia', 'Zambia', 'AFRICA', 'T3', NOW()),
('ZW', 'Zimbabwe', 'Zimbabwe', 'AFRICA', 'T3', NOW()),
('AO', 'Angola', 'Angola', 'AFRICA', 'T3', NOW()),
('MZ', 'Mozambique', 'Mozambique', 'AFRICA', 'T3', NOW()),
('BW', 'Botswana', 'Botswana', 'AFRICA', 'T3', NOW()),
('NA', 'Namibia', 'Namibia', 'AFRICA', 'T3', NOW()),
('RW', 'Rwanda', 'Rwanda', 'AFRICA', 'T3', NOW()),
('SD', 'Sudan', 'Sudan', 'AFRICA', 'T3', NOW()),
('SS', 'South Sudan', 'South Sudan', 'AFRICA', 'T3', NOW()),
('LY', 'Libya', 'Libya', 'AFRICA', 'T3', NOW()),
('CD', 'DR Congo', 'Congo - Kinshasa', 'AFRICA', 'T3', NOW()),
('CG', 'Congo', 'Congo - Brazzaville', 'AFRICA', 'T3', NOW()),
('GA', 'Gabon', 'Gabon', 'AFRICA', 'T3', NOW()),
('ML', 'Mali', 'Mali', 'AFRICA', 'T3', NOW()),
('NE', 'Niger', 'Niger', 'AFRICA', 'T3', NOW()),
('BF', 'Burkina Faso', 'Burkina Faso', 'AFRICA', 'T3', NOW()),
('TD', 'Chad', 'Chad', 'AFRICA', 'T3', NOW()),
('MR', 'Mauritania', 'Mauritania', 'AFRICA', 'T3', NOW()),
('GN', 'Guinea', 'Guinea', 'AFRICA', 'T3', NOW()),
('SL', 'Sierra Leone', 'Sierra Leone', 'AFRICA', 'T3', NOW()),
('LR', 'Liberia', 'Liberia', 'AFRICA', 'T3', NOW()),
('TG', 'Togo', 'Togo', 'AFRICA', 'T3', NOW()),
('BJ', 'Benin', 'Benin', 'AFRICA', 'T3', NOW()),
('GM', 'Gambia', 'Gambia', 'AFRICA', 'T3', NOW()),
('GW', 'Guinea-Bissau', 'Guinea-Bissau', 'AFRICA', 'T3', NOW()),
('CV', 'Cape Verde', 'Cape Verde', 'AFRICA', 'T3', NOW()),
('MU', 'Mauritius', 'Mauritius', 'AFRICA', 'T3', NOW()),
('SC', 'Seychelles', 'Seychelles', 'AFRICA', 'T3', NOW()),
('MG', 'Madagascar', 'Madagascar', 'AFRICA', 'T3', NOW()),
('MW', 'Malawi', 'Malawi', 'AFRICA', 'T3', NOW()),
('LS', 'Lesotho', 'Lesotho', 'AFRICA', 'T3', NOW()),
('SZ', 'Eswatini', 'Eswatini', 'AFRICA', 'T3', NOW()),
('BI', 'Burundi', 'Burundi', 'AFRICA', 'T3', NOW()),
('DJ', 'Djibouti', 'Djibouti', 'AFRICA', 'T3', NOW()),
('ER', 'Eritrea', 'Eritrea', 'AFRICA', 'T3', NOW()),
('SO', 'Somalia', 'Somalia', 'AFRICA', 'T3', NOW()),
('CF', 'Central African Republic', 'Central African Republic', 'AFRICA', 'T3', NOW()),
('GQ', 'Equatorial Guinea', 'Equatorial Guinea', 'AFRICA', 'T3', NOW()),
('ST', 'Sao Tome and Principe', 'São Tomé & Príncipe', 'AFRICA', 'T3', NOW()),
('RE', 'Reunion', 'Réunion', 'AFRICA', 'T3', NOW()),
('YT', 'Mayotte', 'Mayotte', 'AFRICA', 'T3', NOW()),

-- Pacific Islands
('FJ', 'Fiji', 'Fiji', 'APAC', 'T3', NOW()),
('PG', 'Papua New Guinea', 'Papua New Guinea', 'APAC', 'T3', NOW()),
('SB', 'Solomon Islands', 'Solomon Islands', 'APAC', 'T3', NOW()),
('VU', 'Vanuatu', 'Vanuatu', 'APAC', 'T3', NOW()),
('NC', 'New Caledonia', 'New Caledonia', 'APAC', 'T3', NOW()),
('PF', 'French Polynesia', 'French Polynesia', 'APAC', 'T3', NOW()),
('WS', 'Samoa', 'Samoa', 'APAC', 'T3', NOW()),
('TO', 'Tonga', 'Tonga', 'APAC', 'T3', NOW()),
('FM', 'Micronesia', 'Micronesia', 'APAC', 'T3', NOW()),
('MH', 'Marshall Islands', 'Marshall Islands', 'APAC', 'T3', NOW()),
('PW', 'Palau', 'Palau', 'APAC', 'T3', NOW()),
('KI', 'Kiribati', 'Kiribati', 'APAC', 'T3', NOW()),
('NR', 'Nauru', 'Nauru', 'APAC', 'T3', NOW()),
('TV', 'Tuvalu', 'Tuvalu', 'APAC', 'T3', NOW()),
('CK', 'Cook Islands', 'Cook Islands', 'APAC', 'T3', NOW()),
('NU', 'Niue', 'Niue', 'APAC', 'T3', NOW()),
('TK', 'Tokelau', 'Tokelau', 'APAC', 'T3', NOW()),
('WF', 'Wallis and Futuna', 'Wallis & Futuna', 'APAC', 'T3', NOW()),
('AS', 'American Samoa', 'American Samoa', 'APAC', 'T3', NOW()),
('GU', 'Guam', 'Guam', 'APAC', 'T3', NOW()),
('MP', 'Northern Mariana Islands', 'Northern Mariana Islands', 'APAC', 'T3', NOW()),

-- Caribbean & Atlantic Islands
('AG', 'Antigua and Barbuda', 'Antigua & Barbuda', 'LATAM', 'T3', NOW()),
('DM', 'Dominica', 'Dominica', 'LATAM', 'T3', NOW()),
('GD', 'Grenada', 'Grenada', 'LATAM', 'T3', NOW()),
('KN', 'Saint Kitts and Nevis', 'St. Kitts & Nevis', 'LATAM', 'T3', NOW()),
('LC', 'Saint Lucia', 'St. Lucia', 'LATAM', 'T3', NOW()),
('VC', 'Saint Vincent and the Grenadines', 'St. Vincent & Grenadines', 'LATAM', 'T3', NOW()),
('AW', 'Aruba', 'Aruba', 'LATAM', 'T3', NOW()),
('CW', 'Curacao', 'Curaçao', 'LATAM', 'T3', NOW()),
('SX', 'Sint Maarten', 'Sint Maarten', 'LATAM', 'T3', NOW()),
('BQ', 'Caribbean Netherlands', 'Caribbean Netherlands', 'LATAM', 'T3', NOW()),
('AI', 'Anguilla', 'Anguilla', 'LATAM', 'T3', NOW()),
('VG', 'British Virgin Islands', 'British Virgin Islands', 'LATAM', 'T3', NOW()),
('VI', 'U.S. Virgin Islands', 'U.S. Virgin Islands', 'LATAM', 'T3', NOW()),
('KY', 'Cayman Islands', 'Cayman Islands', 'LATAM', 'T3', NOW()),
('TC', 'Turks and Caicos Islands', 'Turks & Caicos Islands', 'LATAM', 'T3', NOW()),
('MS', 'Montserrat', 'Montserrat', 'LATAM', 'T3', NOW()),
('BM', 'Bermuda', 'Bermuda', 'NA', 'T2', NOW()),
('GL', 'Greenland', 'Greenland', 'NA', 'T3', NOW()),
('PM', 'Saint Pierre and Miquelon', 'St. Pierre & Miquelon', 'NA', 'T3', NOW()),
('FK', 'Falkland Islands', 'Falkland Islands (Islas Malvinas)', 'LATAM', 'T3', NOW()),
('GP', 'Guadeloupe', 'Guadeloupe', 'LATAM', 'T3', NOW()),
('MQ', 'Martinique', 'Martinique', 'LATAM', 'T3', NOW()),
('BL', 'Saint Barthelemy', 'St. Barthélemy', 'LATAM', 'T3', NOW()),
('MF', 'Saint Martin', 'St. Martin', 'LATAM', 'T3', NOW()),

-- European Microstates & Territories
('AD', 'Andorra', 'Andorra', 'EMEA', 'T2', NOW()),
('MC', 'Monaco', 'Monaco', 'EMEA', 'T1', NOW()),
('SM', 'San Marino', 'San Marino', 'EMEA', 'T2', NOW()),
('VA', 'Vatican City', 'Vatican City', 'EMEA', 'T2', NOW()),
('LI', 'Liechtenstein', 'Liechtenstein', 'EMEA', 'T1', NOW()),
('GI', 'Gibraltar', 'Gibraltar', 'EMEA', 'T2', NOW()),
('IM', 'Isle of Man', 'Isle of Man', 'EMEA', 'T2', NOW()),
('JE', 'Jersey', 'Jersey', 'EMEA', 'T2', NOW()),
('GG', 'Guernsey', 'Guernsey', 'EMEA', 'T2', NOW()),
('FO', 'Faroe Islands', 'Faroe Islands', 'EMEA', 'T2', NOW()),
('AX', 'Aland Islands', 'Åland Islands', 'EMEA', 'T2', NOW()),
('SJ', 'Svalbard and Jan Mayen', 'Svalbard & Jan Mayen', 'EMEA', 'T3', NOW()),
('IS', 'Iceland', 'Iceland', 'EMEA', 'T1', NOW()),

-- Asia Special Regions
('MO', 'Macau', 'Macao', 'APAC', 'T2', NOW()),
('BN', 'Brunei', 'Brunei', 'APAC', 'T2', NOW()),
('TL', 'Timor-Leste', 'Timor-Leste', 'APAC', 'T3', NOW()),
('BT', 'Bhutan', 'Bhutan', 'APAC', 'T3', NOW()),
('MV', 'Maldives', 'Maldives', 'APAC', 'T3', NOW()),
('CN', 'China', 'China', 'APAC', 'T2', NOW()),
('KP', 'North Korea', 'North Korea', 'APAC', 'T3', NOW()),

-- Middle East
('PS', 'Palestine', 'Palestine', 'EMEA', 'T3', NOW()),
('EH', 'Western Sahara', 'Western Sahara', 'AFRICA', 'T3', NOW()),

-- Remote territories
('IO', 'British Indian Ocean Territory', 'British Indian Ocean Territory', 'APAC', 'T3', NOW()),
('CC', 'Cocos (Keeling) Islands', 'Cocos (Keeling) Islands', 'APAC', 'T3', NOW()),
('CX', 'Christmas Island', 'Christmas Island', 'APAC', 'T3', NOW()),
('NF', 'Norfolk Island', 'Norfolk Island', 'APAC', 'T3', NOW()),
('HM', 'Heard Island and McDonald Islands', 'Heard & McDonald Islands', 'APAC', 'T3', NOW()),
('PN', 'Pitcairn Islands', 'Pitcairn Islands', 'APAC', 'T3', NOW()),
('SH', 'Saint Helena', 'St. Helena', 'AFRICA', 'T3', NOW()),
('AQ', 'Antarctica', 'Antarctica', 'OTHER', 'T3', NOW()),
('TF', 'French Southern Territories', 'French Southern Territories', 'OTHER', 'T3', NOW()),
('BV', 'Bouvet Island', 'Bouvet Island', 'OTHER', 'T3', NOW()),
('GS', 'South Georgia and the South Sandwich Islands', 'South Georgia & South Sandwich Islands', 'OTHER', 'T3', NOW()),

-- Unknown/Unspecified
('ZZ', 'Unknown', 'Unknown', 'OTHER', 'T3', NOW()),

-- Comoros (missing from original list but in AdMob data)
('KM', 'Comoros', 'Comoros', 'AFRICA', 'T3', NOW());

-- Verify count
SELECT COUNT(*) AS total_countries FROM silver.dim_country;
